### ISSUE TITLE
Deprecated Notices

### ISSUE THREAD

**Issue by maechler** [AOEpeople/crawler#107]
Some cli classes throw a deprecation notice using PHP 7 because they are not using __construct as constructor method name.

Core: Error handler (BE): PHP Runtime Deprecation Notice: Methods with the same name as their class will not be constructors in a future version of PHP; tx_crawler_cli_im has a deprecated constructor in typo3conf/ext/crawler/cli/class.tx_crawler_cli_im.php line 38

**Comment by maechler** [comment]
Closing here because pull request has been merged: https://github.com/AOEpeople/crawler/pull/108

Thanks!

**Comment by tomasnorre** [comment]
Thanks for your contribution.
