### ISSUE TITLE
[BUG] Workspaces not installed

### ISSUE THREAD

**Issue by ogrosko** [AOEpeople/crawler#109]
If Workspaces management extension is not installed in typo3
Crawler configuration page throws an error:

`Field sys_workspace_uid of table tx_crawler_configuration reference to foreign table sys_workspace, but this table is not defined in TCA`

**Comment by tomasnorre** [comment]
Hi,

This is fixed with follow commit: 
https://github.com/AOEpeople/crawler/commit/dacb06df29a8df424fe1dba2cdd859c24181a821

we didn't release a new version to TER yet, but it's fixed.

**Comment by ogrosko** [comment]
When you are planing release new version to TER?
Thanks

**Comment by tomasnorre** [comment]
I can check the code-base and do it somewhen this week.

**Comment by tomasnorre** [comment]
@ogrosko I just release a new version 5.0.5 which contains this fix.
https://typo3.org/extensions/repository/view/crawler
