### ISSUE TITLE
Crawling causes "trustedHostsPattern" exception

### ISSUE THREAD

**Issue by thommyhh** [AOEpeople/crawler#110]
Crawling does not work anymore with 5.0.5, as you removed (break change!!!) the fsockopen which make a more real http request than the direct requests.

The direct requests fake the environment. First the fake is incomplete, e.g. the SERVER_PORT is missing which leads to the "trustedHostsPattern" exception. Even with this fixed, the fake does not handle the case, the frontend returns a 30x redirect from "/index.php?id=5" to "/about-us/", from a url extension.

Please revert the changes asap to make the crawling work like before.

Breaking changes must not be made in major or minor version changes. This can only be included in a 6.0.0 release!!!

**Comment by tomasnorre** [comment]
@thommyhh 
Thanks for your bug-report.. Will look into this asap.

**Comment by tomasnorre** [comment]
Is related to followup PR #104

**Comment by tomasnorre** [comment]
@thommyhh 

We have made a reverse commit and released a new version 5.0.6, we have cherry-picked this in to a development branch that will be used for 6.0.0. 

Thanks for reporting, we will close this issue now.
