### ISSUE TITLE
[BUG] No TypoScript template found! error

### ISSUE THREAD

**Issue by ogrosko** [AOEpeople/crawler#111]
Updating crawler extension to v5.0.5
I'm getting error: `No TypoScript template found!` in BE module WEB -> Info -> Some page

With wersion 5.0.4 it works with no problems

**Comment by tomasnorre** [comment]
Thanks for reporting @ogrosko, we got some other major problems reported too.

#110

**Comment by maechler** [comment]
You have to edit the crawler configuration in the extension manager and set the variable: 
basic.PageUidRootTypoScript

That solved that problem for me. However #110 is a real problem for us too.

**Comment by tomasnorre** [comment]
@maechler That's true i forgot about that change.. 

Better get the documentation up to date.. 

Thanks for helping each other.

**Comment by ogrosko** [comment]
@maechler thanks for the hint it solve my problem

As mentioned I have problem with #110

**Comment by tomasnorre** [comment]
This was already introduced in 5.0.4 so no reverse commit will be created , we will update the documentation though. 

We have added this information to the wiki page:
https://github.com/AOEpeople/crawler/wiki/Known-issues
