### ISSUE TITLE
Extension Manager

### ISSUE THREAD

**Issue by vixe76** [AOEpeople/crawler#115]
After each install or uninstall of extensions the folllowing exception will be thrown ...

Could not scan for classes inside "/var/www/html/typo3conf/ext/crawler/.Build/vendor/typo3/cms/typo3/sysext/core/Tests/" which does not appear to be a file nor a folder

crawler 5.0.6
TYPO3 7.6.10

**Comment by tomasnorre** [comment]
Thanks @vixe76 we will have a look.. 

Do you install the extension with composer ?

**Comment by tomasnorre** [comment]
This is fixed with latest master.
