### ISSUE TITLE
Updating to 5.0.7

### ISSUE THREAD

**Issue by hartundweich** [AOEpeople/crawler#120]
When updating crawler extension via extension manager to V 5.0.7 after the update process the following line appears on top of the extension manager:

Could not scan for classes inside "/home/.sites/97/site6275980/web/typo3conf/ext/crawler/.Build/vendor/typo3/cms/typo3/sysext/core/Tests/" which does not appear to be a file nor a folder

I think that could be a bug, because the directory ".Build" does not exist. 

I don't know if it has any effects on the scheduler jobs - but when I run Crawler Queue Flush and Crawler Queue, my index is still available - as far as I remember after thes two jobs the index fomerly gets cleared and nothing was found when using the search form?

**Comment by tomasnorre** [comment]
@hartundweich 

This should not be a problem anymore, are you sure the cache is properly cleared..?

The "TYPO3\\CMS\\Core\\Tests\\": ".Build/vendor/typo3/cms/typo3/sysext/core/Tests/" is moved from the autoload to the autoload-dev and therefor this shouldn't be a problem anymore.

**Comment by hartundweich** [comment]
@tomasnorre 
It happens direct after the upgrade where we should see a green message of success on top of the extension manager, instead the red one is shown - so no chance to clear the cache to avoid this message.
Tetsted with Typo3 7.6.10 PHP 5.6 and PHP 7.0 upgrade from 5.0.6 --> 5.0.7

**Comment by tomasnorre** [comment]
Thanks for the information @hartundweich,

I'll look into this.

**Comment by tomasnorre** [comment]
@hartundweich 

Was the extension installed with composer or with file-upload at first ? before you did the update through the extension manager ?

**Comment by hartundweich** [comment]
The extension was first installed the classical way with the extension manager - as this site is hosted on a webserver with no possibility to use composer installation

**Comment by tomasnorre** [comment]
@hartundweich 

Thanks for the clarification.. Will have a look.

**Comment by tomasnorre** [comment]
@hartundweich Can you check if this still is a problem with latest release https://github.com/AOEpeople/crawler/releases/tag/5.1.2

**Comment by hartundweich** [comment]
Update yesterday from 5.1.1 to 5.1.2 was successful without any problems - so I think this task can be closed.

**Comment by tomasnorre** [comment]
Thanks a lot for your update @hartundweich and thanks for your contribution.
