### ISSUE TITLE
Scheduler Tasks broken after upgrade to 5.1.0

### ISSUE THREAD

**Issue by srotsch** [AOEpeople/crawler#142]
After upgrading to 5.1.0, already existing scheduler tasks are broken as the class names have changed due to namespacing.

<img width="1369" alt="task_class" src="https://cloud.githubusercontent.com/assets/1445999/20348960/72d8aacc-ac08-11e6-8494-d4b880d3ca96.png">

**Comment by tomasnorre** [comment]
This should be solvable with same technique as in the EXT:news for the 6x branch. 
https://github.com/georgringer/news/tree/6x/Migrations/Code

**Comment by rvock** [comment]
This issue still exists with Crawler 5.1.1, if crawler is installed via composer.
`Migrations/Code/ClassAliasMap.php` is not loaded in composer-mode.

I think, you need to add keys to your `composer.json` to fix this:
https://github.com/TYPO3/class-alias-loader#user-content-configuration-in-composerjson

**Comment by tomasnorre** [comment]
Closed as new issue is opened #154, makes the tracking easier.
