### ISSUE TITLE
[BUG] #1442236317: MenuItem "" is not valid (More information)

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#148]
* TYPO3 7.6.12 (Perhaps lower versions as well, but not 6.2.x)

When clicking at the Info-Module, the exception is thrown
#1442236317: MenuItem "" is not valid (More information)
![exceptionthrown](https://cloud.githubusercontent.com/assets/1212481/20364105/35175b2c-ac42-11e6-8966-7ea75f000800.png)

**Comment by CDRO** [comment]
I'd like to reopen this issue since it seems to have reappeared in 5.1.2, can anybody else confirm this?

**Comment by tomasnorre** [comment]
Let us know if you have other issues.
