### ISSUE TITLE
Language labels are missing on TYPO3 8.5

### ISSUE THREAD

**Issue by michadu** [AOEpeople/crawler#187]
In https://forge.typo3.org/issues/78647 the language files of sys ext:lang are moved to new directories.
The crawler extension has to be fixed for TYPO3 8.5 (and newer) according to the documentation of the TYPO3 core: "Deprecation: #78647 - Move language files from EXT:lang/locallang_* to Resources/Private/Language"

**Comment by tomasnorre** [comment]
Thanks for you input, we will look into this.

EXT:Crawler is not officially supported, but we will take care.

**Comment by tomasnorre** [comment]
This is solved within the TYPO3_8 branch, so I'll close this ticket.

**Comment by tmotyl** [comment]
AFIAK it was deprecated in v8, so the old labels will still work, the only thing to do is to change from xml to xlf:
EXT:lang/locallang_general.xml => EXT:lang/locallang_general.xlf

**Comment by tomasnorre** [comment]
Thanks for letting us know @tmotyl, I'll check it. 

It's already done in the TYPO3_8 branch. I'll reopen till I have confirmed it's done.

**Comment by tomasnorre** [comment]
It will be covered in #139, so we will close this issue.
