### ISSUE TITLE
Crawler queue scheduler task loses settings on configuration error

### ISSUE THREAD

**Issue by cweiske** [AOEpeople/crawler#190]
I wanted to create a new scheduler task of type "crawler queue", set "start page: 1" and the depth but failed to select a configuration records.

After saving, an error message was shown - and the previously made settings for start page and depth were lost:

> There is no configuration record selected, please choose at least one or more!

----
This is with crawler version 5.1.2 on TYPO3 7.6.15.

**Comment by tomasnorre** [comment]
Can you paste the error message that might help reproducing.

**Comment by cweiske** [comment]
"There is no configuration record selected, please choose at least one or more!"

**Comment by tomasnorre** [comment]
Sorry, didn't see that in your first comment.

**Comment by tomasnorre** [comment]
I've never seen this before, but will try to reproduce.

**Comment by tomasnorre** [comment]
@cweiske I cannot reproduce what you are reporting. I might get it wrong.

Any chance you can do a screencast recording the problem?

I get the "Warnings i expect" and correct the errors in my scheduler config, and save.. Then everything is fine.

**Comment by cweiske** [comment]
screencast: http://hidden.cweiske.de/scheduler-crawler-queue.ogv

**Comment by tomasnorre** [comment]
Thanks, the problem is that you don't have a crawler configuration and therefore you cannot select one.  You have to create a Crawler Configuration. At least one on the your root/start page.
https://docs.typo3.org/typo3cms/extensions/crawler/ExtCrawler/Configuration/ConfigurationRecords/Index.html

**Comment by tomasnorre** [comment]
This is not a bug/problem, i'll close this issue.

**Comment by cweiske** [comment]
sigh.

This problem still happens if I have a crawler configuration but do not select one. The values in the other fields are lost then.

**Comment by tomasnorre** [comment]
Yeah. That's true, but that is not a crawler issue it's a scheduler issue as i get it.. 

But i'll check.

**Comment by cweiske** [comment]
"Normal" scheduler fields like the interval are pre-filled again when I have an error.

So I think that it's a problem with the custom fields that crawler adds to the scheduler form.

**Comment by cweiske** [comment]
please reopen.

**Comment by tomasnorre** [comment]
@cweiske I now have a Pull Request ready, could you do me a favor and test the branch for me?
https://github.com/AOEpeople/crawler/tree/issue/190

Thanks.

**Comment by tomasnorre** [comment]
Resolved with PR #284
