### ISSUE TITLE
Info > Site Crawler > Start Crawling: Warn when no configuration selected

### ISSUE THREAD

**Issue by cweiske** [AOEpeople/crawler#191]
When visiting Info > Site Crawler > Start Crawling, simply clicking "Crawl URLs" does nothing - it only tells you

> 0 URLs submitted. 

It took a while until I found that you have to select a crawler configuration before clicking on "Crawl URLs".

There should be a warning that no configuration has been selected, or the "Crawl URLs" button should be disabled when no configuration is selected.

----

Happened with TYPO3 7.6.15 and crawler 5.1.2

![2017-01-30 typo3 crawler start manually](https://cloud.githubusercontent.com/assets/59036/22422332/1120568a-e6ec-11e6-85d7-05938744653f.png)

**Comment by tomasnorre** [comment]
Thanks for your input.

**Comment by cweiske** [comment]
1. I did not recognize the text in the table as error message, especially since it has been there even before I clicked "crawl URLs".
2. There is only one configuration here, and it's not easily recognizable in that size-1-select field that it is not selected at all.
3. I thought the table below the buttons are some kind of statistics and have no direct relation with the form above.

**Comment by tomasnorre** [comment]
Thanks for you input. We will take it into consideration, so that we can improve the UX/UI.
