### ISSUE TITLE
[BUGFIX] Pages with force ssl should be added with ssl to queue.

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#194]
Please check commit: 
https://github.com/AOEpeople/crawler/commit/1b951117269f3f431c4131e3352a2ae419d38c56

**Comment by lochmueller** [comment]
Note: The field 'url_scheme' is dropped in the last TYPO3 release

**Comment by tomasnorre** [comment]
Thanks for the update @lochmueller.

**Comment by tomasnorre** [comment]
This should already be resolved. But not in official release yet.
