### ISSUE TITLE
Crawling process "Refresh" button loses page ID

### ISSUE THREAD

**Issue by cweiske** [AOEpeople/crawler#198]
In Web > Info > Site Crawler > Crawling process, pressing the "Refresh" button loses information about the page selected in the page tree.

When trying to switch back to the crawler log, I get a "Please select a page in the pagetree" message instead of the previous crawl log.

Before pressing "Refresh":
![2017-03-27 crawler refresh 1](https://cloud.githubusercontent.com/assets/59036/24356265/945cfeb6-12f9-11e7-879b-afa99855dc2e.png)

After pressing "Refresh":
![2017-03-27 crawler refresh 2](https://cloud.githubusercontent.com/assets/59036/24356300/b343c1c0-12f9-11e7-8d14-1e8872083f7d.png)

**Comment by tomasnorre** [comment]
@cweiske Thanks for reporting, we will have a look.

**Comment by tomasnorre** [comment]
I can reproduce this with:

TYPO3 8.7.8
Crawler: TYPO3_8 Branch, so most likely still a problem in the master as well.
