### ISSUE TITLE
HTTP Authentication support

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#20]
It would be very nice to have a HTTP Authentication support for the crawler, so websites (intranet mainly) that are protected by a htaccess authentication could be crawled too, especially if it's not possible to exclude the server itself from the authentication procedure.

Migrated from: https://forge.typo3.org/issues/47595

**Comment by ArminVieweg** [comment]
This is already possible. Just configure as base url something like that `http://user:pass@www.mydomain.com/`

**Comment by tomasnorre** [comment]
Thanks for your input, then we perhaps just needs to update the manual, to make users aware of this option..

**Comment by tomasnorre** [comment]
Fixed with PR #61
