### ISSUE TITLE
Logic "Use realurl urls "

### ISSUE THREAD

**Issue by hacksch** [AOEpeople/crawler#201]
I'm not sure if we need the functionality "Use realurl urls".
The field was hidden for a long time in the crawler configuration. Was enabled again because of a displayCond error in TYPO3 8 (https://github.com/AOEpeople/crawler/commit/e4283786b3d0526d578e3a19c88c78404f94f28e).

When the functionality is not necessary we should remove the complete logic

**Comment by tomasnorre** [comment]
We will not spent time on this as the Pretty Url concept is build-in in TYPO3 9LTS.
