### ISSUE TITLE
BE Info Module in TYPO3 8 LTS

### ISSUE THREAD

**Issue by dklimpel** [AOEpeople/crawler#206]
Call to undefined method TYPO3\CMS\Backend\Template\DocumentTemplate::spacer
[Deprecation: #71153 -  #DocumentTemplate->spacer()](https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.6/Deprecation-71153-DocumentTemplateSpacer.html)

In: crawler/modfunc1/class.tx_crawler_modfunc1.php on line 225

**Comment by tomasnorre** [comment]
Hi @dklimpel 

did you try the TYPO3_8 branch ?
https://github.com/AOEpeople/crawler/tree/TYPO3_8

**Comment by dklimpel** [comment]
Hi @tomasnorre,

no. With TYPO3_8 branch it is better.
Thx.

**Comment by tomasnorre** [comment]
Super.. Thanks for letting us now. I'll close this issue.
