### ISSUE TITLE
TYPO3 Crawler is loading till internal server error 500 comes up

### ISSUE THREAD

**Issue by MatthiasGwiozda** [AOEpeople/crawler#207]
I configured the crawler (Version 5.1.3) on multiple TYPO3 instances (the Configuration and the TYPO3 Version [7.6.20] are always the same). I am using PHP 7.0.15.

Sometimes its working and sometimes I have this problem: After all the [Configurations ](http://xavier.perseguers.ch/en/tutorials/typo3/articles/indexed-search-crawler.html) are made I want to start crawling in Web --> Info --> Site Crawler --> Start Crawling. When I select a page in the pagetree and klick on: "Start Crawling" then it is loading 10 - 15 minutes and afterwards I get a Server Error (500). This makes it impossible to use the crawler to crawl pages.

Thanks in advance.

**Comment by tomasnorre** [comment]
ok.. We will have to look into that.. 

Thanks for reporting.

**Comment by MatthiasGwiozda** [comment]
Finally I found the solution. I have to use the CGI Version of PHP (In this case 7.0.20)
