### ISSUE TITLE
This results in an error on TYPO3 8.7

### ISSUE THREAD

**Issue by featdd** [AOEpeople/crawler#208]
https://github.com/AOEpeople/crawler/blob/bee13f75982e339069ba346d5bc12c0f9e8f397a/Configuration/TCA/tx_crawler_configuration.php#L145

Creating a new configuration results in:
`#1481381950: Unknown condition rule type "FALSE" with display condition "FALSE"".`

**Comment by tomasnorre** [comment]
@featdd can you please try the TYPO3_8 Branch?

**Comment by featdd** [comment]
didn't saw it, will try it out next time, thx

**Comment by tomasnorre** [comment]
No Problem, let me know if it doesn't work. 

We are working on a rewrite, but it's not always going as fast as one want to.

**Comment by featdd** [comment]
I know dat feel bro, I helped myself with a wget spider yesterday, and will work on it next friday again.

**Comment by joka123** [comment]
i got the same issue.
branch_typo3_8 works for me.

**Comment by ses** [comment]
for the TYPO3 8.7.7 we use the "master" or the "TYPO3_8" Branch?

**Comment by tomasnorre** [comment]
@ses the TYPO3_8 branch.

**Comment by ingeniumdesign** [comment]
okay, thanks!

**Comment by tomasnorre** [comment]
I've closed this Issue as it looks like it's working with the TYPO3_8 branch.
