### ISSUE TITLE
ProcessCleanUpHook.php::isOsWindows() wrong condition

### ISSUE THREAD

**Issue by samowitsch** [AOEpeople/crawler#209]
Hi. In ProcessCleanUpHook.php::isOsWindows() is a wrong condition.
I think there should be
`        if (TYPO3_OS === 'WIN') {
            return true;
        }`
instead of 
`        if (TYPO3_OS === '') {
            return true;
        }`
See also TYPO3 core SystemEnvironmentBuilder::getTypo3Os()

regards

**Comment by tomasnorre** [comment]
Thanks. Will take a look.

**Comment by tomasnorre** [comment]
Can you perhaps make a pull request ?

**Comment by samowitsch** [comment]
https://github.com/AOEpeople/crawler/pull/210

**Comment by tomasnorre** [comment]
Thanks a lot.
