### ISSUE TITLE
Hidden records should be ignored

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#22]
I have a page where I display data records that are organized in a sysfolder. I'm using the following configuration to crawl the different contents (page uid is 13, sysfolder uid is 15):

tx_crawler.crawlerCfg.paramSets {
    items = &tx_myext[items]=[_TABLE:tt_myext_items;_PID:15]
    items {
        pidsOnly = 13
        cHash = 1
        procInstrFilter = tx_indexedsearch_reindex
    }
}
The problem: Hidden records in the sysfolder are still added to the queue and later on indexed as empty page, because the hidden content can not be shown. This will also result in entries in search results for users. These results will lead the user to an empty page, which is pretty bad.

Expected behavior: Hidden records should be ignored when building the initial crawler queue.

It seems that a similar problem is described in #7455, but that bug is closed.

IMPORTANT: See comments/discussion here: https://forge.typo3.org/issues/43655

**Comment by fabtho** [comment]
This is not  bug. Its just undocumented. just add this ```[_TABLE:tt_myext_items;_PID:15, _WHERE: and hidden = 0]``` 

Just tested this for tt_news and its working. Read the source here:

https://github.com/TYPO3-extensions/crawler/blob/master/class.tx_crawler_lib.php#L752

**Comment by tomasnorre** [comment]
Fixed with PR #61
