### ISSUE TITLE
Can't install extension with php 7.1

### ISSUE THREAD

**Issue by medarob** [AOEpeople/crawler#221]
Hi,

I wanted to install the crawler extension but I got an dependency error because I use php 7.1:
Your PHP version is higher than allowed. You can use PHP versions 5.3.0 - 7.0.99

Can I ignore this?

Thank you :)

**Comment by tomasnorre** [comment]
I cannot promise that this will work.. But i think it should. (Haven't tested this)

Installing by composer ? you can use --ignore-platform-reqs 
https://getcomposer.org/doc/03-cli.md

**Comment by tomasnorre** [comment]
@medarob The problem comes from ext_emconf.php and not from composer as i expected, so my suggestion will not help.. 

I'll address this issue asap as i have proven that the crawler still works with other PHP versions. 

Thanks for reporting.

**Comment by tomasnorre** [comment]
Issue fixed with #228
