### ISSUE TITLE
TYPO3 4.5 scheduler namespace fatal error

### ISSUE THREAD

**Issue by t3easy** [AOEpeople/crawler#26]
The extension is defined as compatible with TYPO3 4.5, but if I try to open the scheduler I get

*PHP Fatal error: Class 'TYPO3\CMS\Scheduler\Task\AbstractTask' not found in /.../typo3conf/ext/crawler/scheduler/class.tx_crawler_scheduler_im.php on line 32*

because you used the TYPO3 6.2+ namespace classes.

Environment TYPO3 4.5.41
PHP 5.5.9

**Comment by rsatwork** [comment]
I can confirm this problem.
