### ISSUE TITLE
[BUG] Crawler only crawls first level

### ISSUE THREAD

**Issue by SylviaMoschner** [AOEpeople/crawler#261]
Hello,
I have updated to TYPO3 v.8.7.8 and crawler version 6.0.0.

I had the problem that crawler never crawled pages no matter which depth I used in my configuration.
I debugged through the code and found out that it was missing the argument to expand the whole tree.

I changed the following file crawler/Classes/Controller/CrawlerController and added the following line beneath line 736 and 1737 (don't know if neccassary on any other object)
$tree->expandAll = 1;

That was it. After it the crawler worked as fine as before the update.

**Comment by dahaupt** [comment]
Hey there, I am experiencing the same issue and your fix is working fine. 👍 

Hoping for a fast bugfix as I really need the crawler :/

**Comment by tomasnorre** [comment]
Thanks for reporting @SylviaMoschner and for comfirming @dahaupt. 

We will be looking into this asap, we are still on christmas holiday, so cannot promise when a bugfix release will be available.

**Comment by tomasnorre** [comment]
@SylviaMoschner @dahaupt I can confirm the problem, but not sure about the solution yet, will have to look into potential side effects.

So far, no one jump to my attention. 

Thanks for reporting.

**Comment by tomasnorre** [comment]
I can also confirm that this happened between the TYPO3_8 branch and the 6.0.0 release.

**Comment by ulrikkold** [comment]
I'm experiencing the same problem on a TYPO3 v7.6.23 - that is, if I'm reading this correctly. I have not confirmed the proposed solution.

**Comment by tomasnorre** [comment]
Thanks for confirming.. 
Also the version 6.0.0 @ulrikkold ? Or which crawler version ?

**Comment by ulrikkold** [comment]
Yep, that's crawler v6.0.0
