### ISSUE TITLE
[CLEANUP] Update Documentation

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#263]
From Slack: https://typo3.slack.com/archives/C087NGBKM/p1515405892000454

I'm missing any explanations and/or recommendations for setting up the Scheduler tasks:

Crawler Queue Flush (crawler)
- Frequency
- Flush mode

Crawler queue (crawler)
- Frequency
- Start page
- Depth

Crawler Run (crawler)
- Frequency
- Allow Parallel Execution ?
- Sleep time
- Sleep after finish
- Count in a run

Settings like 'Sleep time' and some others are also set in Extension Config? e.g. 'basic.sleepTime'? 

An antother question is: Do i need to flush all index tables before reindexing with crawler?

**Comment by tomasnorre** [comment]
Comment from @sypets in issue #327 

I'm missing some common usecases / howtos / best practices for effectively using crawler. It is often mentioned that crawler is commonly used in combination with indexed_search to index pages or for cache warmup. What's a good setup for those usecases? May be a little beyond the scope of docs for crawler, but I'd much rather see this documented here, where it can be maintained by the community than in some blog.

**Comment by jwittorf** [comment]
Hi, any news on this? I'm using the default "indexedsearch" but how can I use the same configuration record to "create" the cache for the same pages?

**Comment by tomasnorre** [comment]
No I didn't get further with this. My focus is at the TYPO3V9 release at the moment (for a while).

Pull requests are more than welcome.

**Comment by jwittorf** [comment]
Okay, thanks for your efforts! I was just wondering why the pages get reindexed for indexed_search but at the same time won't get "recrawled" for the TYPO3 cache. Do I need another extension for this?

**Comment by tomasnorre** [comment]
No, The crawler would be an option for this.
Feel free to reach out on Slack, then we can go over you setup together.

**Comment by jwittorf** [comment]
I finally managed to get back into the issue, would you mind adding me to the slack channel? julian.wittorf@student.fh-kiel.de

**Comment by tomasnorre** [comment]
What do you mean add you to the slack channel? 

It's the official #TYPO3 Slack 
https://my.typo3.org/index.php?id=35

You can join the #ext-crawler channel there.
