### ISSUE TITLE
_WHERE: seems to be ignored typo3 8.7.9 / crawler 6.0.1

### ISSUE THREAD

**Issue by kuhschnappel** [AOEpeople/crawler#265]
This Configuration 

`&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news;_PID:57, _WHERE: and hidden = 0]`

seems to be Ignored. As Result News Entrys which are hidden would be crawled.

**Comment by tomasnorre** [comment]
@kuhschnappel I have been able to reproduce the issue: 

TYPO3: 8.7.9 
Crawler: 6.1.0

Will dig into this.
