### ISSUE TITLE
[FEATURE] Crawl only new or modified pages

### ISSUE THREAD

**Issue by dahaupt** [AOEpeople/crawler#271]
**Feature request:**
It would be awesome if we would be able to **crawl only new or modified pages** in dependency to the `SYS_LASTCHANGED` value of the `pages` table and the last successful crawling run-time of a page. So the indexing configuration should get an option to get this behavior. 

**Current behavior:**
In my researches, I wasn't able to find a way archiving this behavior. Probably the `WHERE ` clause in an indexing configuration is able to archive this, but I am not sure how to do that.

I'm thankful for any thoughts on this one and I appreciate the great work you guys did so far with this extension 👍 🥇

**Comment by tomasnorre** [comment]
@dahaupt Thanks for your input, and thanks for your appreciation. 

What we usually do is we use a hook, cannot remember from the top of my head which, to automatically add the page to the crawler queue on edit. 

This would also be the implementation I would suggest at first here.

I like your idea and will discuss it with @srotsch.

**Comment by dahaupt** [comment]
@tomasnorre Sounds great to add this feature right into the crawler! I'm available to help with occurring troubles.

**Comment by tomasnorre** [comment]
Sorry for having this stalled that long. Would be interested in helping adding this feature to the 9.x release of the crawler @dahaupt ?

**Comment by tomasnorre** [comment]
Resolved with #613
