### ISSUE TITLE
[BUG] When creating new crawler configuration record error is served

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#273]
When creating a new crawler configuration record, the field "process_instruction_filter" doesn't have the default value.  

I'm pretty sure this is due to mysql strict-mode 

TYPO3: 8.7.x
PHP: 7.0.27

**Steps to reproduce:**

1. Create new crawler configuration record
2. Fill out "name" and "Page Id of TypoScript root template" the only 2 required fields.
3. Press save (and you will see the error like in screenshot) 

> 2: SQL error: 'Field 'processing_instruction_filter' doesn't have a default value' (tx_crawler_configuration:NEW5a8b130055a6c965056649)

![screen shot 2018-02-19 at 19 10 37](https://user-images.githubusercontent.com/1212481/36391854-b171f6a2-15a8-11e8-9c4d-ee9afabe5716.png)

**Comment by tomasnorre** [comment]
I cannot reproduce this inside the Crawler Devbox, will try with a different installation later.

**Comment by tomasnorre** [comment]
I've tried on a different system tonight, and cannot reproduce.. 

I'll close this issue as it's reported by me and I cannot reproduce it anymore.

**Comment by aschmutt** [comment]
I can confirm this error, had it with a fresh composer installation today. 
It is a SQL configuration error: 
There are some fields in tx_crawler_configuration that are "NOT NULL" but without default value (like 0 or ''). 
Solution: remove "NOT NULL" or add DEFAULT "" to ext_tables.sql

**Comment by tomasnorre** [comment]
@aschmutt Thanks for your feedback, can you please provide me with a way to reproduce this.

Then I'll look into this asap.

**Comment by aschmutt** [comment]
I am not sure what is the problem, but it could be STRICT mode. This is what I get for my database: 
`
SHOW VARIABLES LIKE 'sql_mode' 

ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
`
2 ways to reproduce:
- Install extension, try to add first configuration entry in TYPO3 Backend -> same SQL error as in first post
- phpmyadmin -> add record, error: 
`
INSERT INTO tx_crawler_configuration (uid, pid, tstamp, crdate, cruser_id, deleted, hidden, name, processing_instruction_filter, processing_instruction_parameters_ts, configuration, base_url, sys_domain_base_url, begroups, fegroups, realurl, chash, exclude, root_template_pid) VALUES (NULL, '0', '0', '0', '0', '0', '0', 'test', '', '', '', 'http://localhost:8000', '', '0', '0', '0', '0', '', '1')

MySQL meldet: Dokumentation
#1364 - Feld 'pidsonly' hat keinen Vorgabewert
`

**Comment by tomasnorre** [comment]
@aschmutt Thanks for the Update, think it's strict mode related to.. 

Will have a look.

**Comment by samowitsch** [comment]
Same problem here after upgrading/migrating an instance to newer versions. MySql before was v5.6.37.

TYPO3: 8.7.19
Crawler: 6.1.2
MySql: 5.7.23

**Comment by samowitsch** [comment]
I tested this solution https://serverpilot.io/docs/how-to-disable-strict-mode-in-mysql-5-7 and this worked for me but i would prefer another solution if possible 😆

**Comment by tomasnorre** [comment]
@samowitsch Shouldn't this fix the language-label problem ? 
https://github.com/AOEpeople/crawler/commit/c0822de43943e1bd4f8d145b554f97cf95f19054

Or is this something else.

Which version on TYPO3 are you on.

**Comment by tomasnorre** [comment]
According to TYPO3 7.6 this path for the label is correct.

**Comment by samowitsch** [comment]
> @samowitsch Shouldn't this fix the language-label problem ?
> [c0822de](https://github.com/AOEpeople/crawler/commit/c0822de43943e1bd4f8d145b554f97cf95f19054)
> 
> Or is this something else.
> 
> Still on TYPO3 8.7?

I am working in 8.7

**Comment by samowitsch** [comment]
But we are loosing main topic 😆 What to do with the SQL error? Is my solution https://github.com/AOEpeople/crawler/issues/273#issuecomment-424269132 suitable? Or is it better to change the definition in ext_tables.sql to avoid this error?

**Comment by tomasnorre** [comment]
I was not trying to move around the main topic, was trying to separating them as they are not the same. 

I don't like approach of disabling the MySQL Strict mode, think the ext_tables.sql would be a better fix.

**Comment by TheJotob** [comment]
This doesn't resolve the issue for me. Since now pidsonly doesn't make any problems anymore but the original mentioned field `processing_instruction_filter` still does.
I could fix it in the same way as for `pidsonly` though (see PR #381 )

**Comment by tomasnorre** [comment]
I've merged it.
