### ISSUE TITLE
[DOCUMENTATION] tutorial, how to set up a crawler configuration for the "news" extensions

### ISSUE THREAD

**Issue by medarob** [AOEpeople/crawler#277]
Hi,

I use the indexedsearch 7.6.23 with the crawler extensions 5.2.1 and so far, the indexing is working. I also use the news extension by Georg Ringer and I would like to create a crawler configuration, which can crawl the news entries so that I can find my news (which are displayed on a news detail page) via the indexedsearch extension. This is not possible with the standard crawler configuration.

I can't find any tutorial how to create a working example for the news extension. Maybe it's possible to update the documentation with some examples, so that it's easy to create other configurations for other common extensions (for example: sf_event_mgt, ... )?

Thank you

**Comment by tomasnorre** [comment]
Hi @medarob 

Please check this section in the documentation, 
https://docs.typo3.org/typo3cms/extensions/crawler/ExtCrawler/Configuration/PageTsconfigReference(txCrawlercrawlercfg)/Index.html#page-tsconfig-reference-tx-crawler-crawlercfg

It can be done like that. If you have access to slack here is a NEWS example.
https://typo3.slack.com/archives/C087NGBKM/p1515747656000044
```
&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news;_PID:57,_WHERE: and hidden = 0]
```

**Comment by medarob** [comment]
Thank you. That worked, however, might it be possible to expand it a little bit.. for example I have a multidomain setup in typo3 with different websites and one folder for news. Each news is assigned one or more categories, depending on which website the news are displayed on.

If I use the instruction above, the indexedsearch plugin finds every news article, even news which are assigned to other websites. That's obvious because I don't filter by category in the crawler configuration.

Is it possible to include more table columns (in my example I need the categories which are stored in the table sys_category) to the crawler instruction above?
I'm not sure if I have to include the sys_category table somewhere or if I have to add something to the _WHERE clause...

I also think, I would need different crawler-news-configurations for each website.

**Comment by tomasnorre** [comment]
This should do the trick for you:
&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news;_PID:57,_WHERE: and hidden = 0 and categories = <categori_id>]

I don't know the News extension from the top of my head, but categories is plural, but and integer field in DB, so cannot say how categories are map. My suggestion might not work. But you can dig into this. 

I also think you would need a crawler-configuration per site, it's at least best practise due to domain-names etc.
