### ISSUE TITLE
crawler 6.1.1 - pdf indexing doesn't work

### ISSUE THREAD

**Issue by blueamerican** [AOEpeople/crawler#278]
TYPO3 8.7.10
ind. search 8.7.10

maybe reltated issue #262
medarob:
"I also noticed that the file indexing (pdf, jpg,.. ) has stopped working. Maybe this is related to the error?"

**Comment by tomasnorre** [comment]
Hi @blueamerican 

PDF Indexing? Sounds more like a indexed search problem than crawler? 
Can you elaborate a little more on how you experience the problem and how to reproduce?

**Comment by blueamerican** [comment]
after deleting the indexed results and reindexing, it worked.

**Comment by tomasnorre** [comment]
ok. Thanks for following up on this. Let us know if you find other issues.
