### ISSUE TITLE
Wrong development requirement with "typo3/cms"

### ISSUE THREAD

**Issue by nimayneb** [AOEpeople/crawler#280]
Why is the dependency of TYPO3 mentioned in the "require-dev" section and also as a complete TYPO3 package (deprecated)? This breaks the composer installation with a root dependency of "typo3/cms-core" (TYPO3-9-compliance), because composer installs "typo3/cms" as complete package dependency (not desired) and that leads to:
```
$ vendor/bin/typo3cms install:generatepackagestates
```
```
[ UnexpectedValueException ]                                                                                                                          
    The package "crawler" depends on "core" which is not present in the system.
```

**Solution:**
Please remove the dependency of "typo3/cms" inside "require-dev" section.

**Comment by nimayneb** [comment]
Currently, I'm trying to create a minimal example to narrow down the problem.

But maybe that helps:
https://github.com/symfony/symfony/issues/26757

**Comment by tomasnorre** [comment]
Thanks @nimayneb will have a look into that.

**Comment by nimayneb** [comment]
A minimal setup has shown that it is not subject to definition "require-dev" in this extension.

My modest suggestion is to include a conflict section with "symfony/finder" version "4.0.7"...

**Comment by nimayneb** [comment]
Better approach:
```
"conflict": {
    "symfony/finder": "4.0.7"
  },
```

**Comment by tomasnorre** [comment]
Sorry I don't get that ? What would that fix in the Crawler extension?

**Comment by nimayneb** [comment]
Then you can close the issue because it was a wrong assumption, that it was due to the "typo3/cms" in the "require-dev" section.

The error message was misleading:
```The package "crawler" depends on "core" which is not present in the system.```

**Comment by tomasnorre** [comment]
ok. Thanks for investigating. Please let us know if you have other issues. 

Have a nice weekend.
