### ISSUE TITLE
When i click on select real url option for crawl then i start the clrawling show Class 'tx_realurl' not found error could you let me how to resolve.

### ISSUE THREAD

**Issue by anujaunds** [AOEpeople/crawler#282]

**Comment by tomasnorre** [comment]
Which RealURL version are you using.. RealURL 2 is not supported yet.

**Comment by anujaunds** [comment]
I used RealUrl 2.3.2 version and latest version of typo3

**Comment by tomasnorre** [comment]
Then that's the problem. I'll close this issue, and refer to #88 as it's a duplet then.
