### ISSUE TITLE
[BUG] CrawlerController::getUrlsForPageRow Argument is NULL

### ISSUE THREAD

**Issue by r3h6** [AOEpeople/crawler#283]
Oops, an error occurred: Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageRow() must be of the type array, null given, called in /var/www/vendor/typo3/cms/typo3/sysex

Got once this error when executing the scheduler, but could nor reproduce it.

**Comment by tomasnorre** [comment]
Thanks for reporting @r3h6.

As it's not reproducible it's difficult for us to proceed.. In case you find a way to reproduce, please let us know. 

Can you as minimum provide us with: 

TYPO3 Version
Crawler Version
PHP Version

Thanks

**Comment by r3h6** [comment]
TYPO3: 8.7
PHP: 7.2.3-1+ubuntu14.04.1
crawler: 6.1.1

**Comment by tomasnorre** [comment]
@r3h6 I expect this to be related to the issue #279 ? Cann this be closed as well ?

**Comment by r3h6** [comment]
I close this issue because so far it was not reproducable.

**Comment by tomasnorre** [comment]
Thanks.

**Comment by cweiske** [comment]
Today I got the same error:
> TypeError: Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageRow() must be of the type array, null given, called in /var/www/typo3/public/typo3/sysext/indexed_search/Classes/Hook/CrawlerHook.php on line 438

TYPO3 10.4.34
PHP 7.4.28
crawler 11.0.7
