### ISSUE TITLE
Backend Call Add Scheduler Task & Web > Info Create Error

### ISSUE THREAD

**Issue by Asfga** [AOEpeople/crawler#286]
Hope I am right here if not then I am sorry. I'm new to TYPO3 and wanted to try out indexed search & crawler extension but for whatever reason it doesn't work. I'm using TYPO3 Version 9.1.0, Crawler 6.1.1, Indexed Search 9.1.0 and Scheduler 9.1.0.

If I click on the scheduler icon in the backend and then click on add task, the following error message is shown:

`Call to a member function exec_SELECTquery() on null `

The log says this:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function exec_SELECTquery() on null | Error thrown in file ...\typo3conf\ext\crawler\Classes\Task\CrawlerQueueTaskAdditionalFieldProvider.php in line 168. Requested URL: http://localhost/typo3/index.php?route=%%2Fsystem%%2FtxschedulerM1%%2F&token=5da8fa958c19402f614ad05f538cae7f9c0448e4&CMD=add `

Didn't found a problem like this on the web, hope you have a solution for it.

Another thing is when I click on Web > Info I get this error:

`Call to undefined method AOE\Crawler\Backend\BackendModule::incLocalLang()`

The log:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method AOE\Crawler\Backend\BackendModule::incLocalLang() | Error thrown in file ...\typo3conf\ext\crawler\Classes\Backend\BackendModule.php in line 169. Requested URL: http://localhost/typo3/index.php?route=%%2Fweb%%2Finfo%%2F&token=9ea2052470cf43b8e25b70ed2b2a2a72cdc5b5bd`

Hope you can help me! ;)

**Comment by tomasnorre** [comment]
The Crawler extension is not TYPO3 compatible yet. 

As far as I know is the exec_SELECTquery() etc. migrated to Doctrine, and therefor it's not compatible. 

We don't have a schedule for the 9.x compatible version yet. Sorry.

**Comment by Asfga** [comment]
Thanks that was the thing I overlooked.
