### ISSUE TITLE
Incompatible with Indexed_search

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#3]
From the last release of 4.0.0, we got this error reported:

https://forge.typo3.org/issues/55106#note-17

Hi all,
I've installed and tried today the crawler latest dev version https://git.typo3.org/TYPO3CMS/Extensions/crawler.git/snapshot/20bfb07561b5e15f2324fd84751c633cb049dacd.zip on Typo3 6.2.7, PHP 5.5.9.
Unfortunately it doesn't seem to want to queue anything.

This is my process (following mostly the howto: http://xavier.perseguers.ch/tutoriels/typo3/articles/indexed-search-crawler.html) :
add a crawler record at the page tree root named simple-indexing
truncate all concerned mysql tables to have something clean
go to a given normal page with Web > info and have a look at Indexed Search (OK no entries)
stay in Web > info, but choose now Site crawler
choose the simple-indexing, and clic on Update and then on Crawl URLs
Here: Update refreshes the page but Count stays at zero.
Crawl URLs leads to another page and we can see "0 URL submitted".
I've done the same process this morning with the 3.5.0 crawler extension on the TER: the Count goes to 1, and I had "1 URL submitted", but starting the job manually has given no indexing results. It's how I've seen the current bug report here, and why I would to find a crawler running with my Typo3 version.

Thanks for your help.

Migrated from: https://forge.typo3.org/issues/68949

**Comment by tmotyl** [comment]
I'm using crawler 5.0.3 with TYPO3 6.2.19, and it's working fine.

**Comment by tomasnorre** [comment]
Thanks @tmotyl  for the information, it's an old ticket back from forge, so more for verification.. I close the ticket as you have confirmed it's not an issue anymore..
