### ISSUE TITLE
[Bug] error in log updating from 5.2.1 -> 6.1.2

### ISSUE THREAD

**Issue by medarob** [AOEpeople/crawler#301]
Hi,

I got an error in my log file after I updated the crawler extension from 5.2.1 to the newest version 6.1.2.
I use Typo3 7.6.27 and PHP 7.1.

That was the error message:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method AOE\Crawler\Utility\BackendUtility::registerIcons() | Error thrown in file /var/www/user.name/typo3conf/ext/crawler/ext_localconf.php in line 11. Requested URL: http://[myurl]/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=b7f6d3a23f1ae561ea073d2073c6c94e1b6015e9&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bextension%5D=crawler&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bversion%5D=6.1.2&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bformat%5D=json&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=updateExtension&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=Download&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bversion%5D=6.1.2 

Not sure if this will have any effect on the system but I thought I let you know...

**Comment by tomasnorre** [comment]
@medarob Are you using compose mode?

**Comment by medarob** [comment]
No, I updated the extension via TER.

**Comment by tomasnorre** [comment]
I sounds like a caching issue to me. 

The registerIcons was implemented just before the 6.0.0 was releases. Can you please try clear the PHP-Caches? Usually I uninstall the about-extension and reinstall it to have the cache "really"-cleared.

**Comment by medarob** [comment]
So, you mean I should roll back to 5.2.1, deactivate and activate the "Help > About" extension and update to 6.2.1 again?

So far, the error occured only once. Indexing of the sites seems to work with the scheduler task.

However, I noticed that the PDF (and image) file indexing has stopped working again... It worked with 5.2.1 (that was the reason I was still using it) but now, PDFs and images are not indexed, even if I run the crawler scheduler a second time.

**Comment by tomasnorre** [comment]
Keep your updated version, and uninstall and install the about module. Then the Icons should be back as expected.

**Comment by tomasnorre** [comment]
@medarob Do you have an update on this ?

**Comment by medarob** [comment]
The icons seems to work but indexing of PDF files and images doesn't work anymore.
They are not shown in the Indexing module.

**Comment by tomasnorre** [comment]
We haven't changed anything in regards to indexing. I'll close this issue, can you please open a new one with a describtion on how to reproduce this Problems with PDF and Images? 
And please let us know which index you mean, is it indexed_search ?
