### ISSUE TITLE
indexing issue with crawler extension

### ISSUE THREAD

**Issue by anujaunds** [AOEpeople/crawler#306]
HI,
 Could you help me for indexing page url with crawler extension. I have faced some problem with indexed_search in typo3 (8.7.10). It is only indexing the default language page. Currently i have selected three language on my website like English, German and Chinense. I already installed the crawl extension but faced same issue. Could you please let me the solution

**Comment by tomasnorre** [comment]
Hi @anujaunds 

You need to be more specific otherwise we will not be able to help you. 

What are your problems and how to reproduce them ?

**Comment by anujaunds** [comment]
Hi Tomasnoree,

i am creating a new website in typo3 with three language like: English, German and chinense. I will try to reindex my all page with the help of crawler. but i am unable to reindex my all page with different language id. I create Crawler with crawle option with root page and then i run crawler function from typo3>info. but after complete the process i  check in indexing option then pages are not indexed. could you let me how i solved this problem.

**Comment by tomasnorre** [comment]
@anujaunds 

You have to configure the languages in the Crawler config.
https://docs.typo3.org/typo3cms/extensions/crawler/ExtCrawler/Configuration/ConfigurationRecords/Index.html

**Comment by anujaunds** [comment]
![screen](https://user-images.githubusercontent.com/38660798/41089890-33941126-6a43-11e8-99ee-a9d7bbdb99ee.png)
I already follow these step to configure my crawler extenstion

**Comment by tomasnorre** [comment]
@anujaunds Which errors do you get and when ? 

A need more information to be able to help.. I still don't know what the error is. 

Please add steps to reproduce.

**Comment by anujaunds** [comment]
it's working properly When i Start the crawling. but it doesn't  indexded all pages. Please see the screenshot
![index](https://user-images.githubusercontent.com/38660798/41239149-02ca5732-6d98-11e8-8113-52a319deec40.png)

**Comment by anujaunds** [comment]
First i was setup index crawl with the help of documentation and then start crawling and selected index  . After select index then click on crawl url  then visible two button Continue and Continue and Show Log then click on Continue and Show Log button After that i click on Add Process button for start the process. After some Crawling process complete then i check the  page index but here maximum page are not index. i have attached the screen shot, please check 

![show-crawllog](https://user-images.githubusercontent.com/38660798/41240658-5e1b1358-6d9b-11e8-94fd-bfc9e5678e97.png)
![start-crawling](https://user-images.githubusercontent.com/38660798/41240660-5e3bf6f4-6d9b-11e8-8de6-84b76547b15a.png)
![start-process](https://user-images.githubusercontent.com/38660798/41240662-5eb957d4-6d9b-11e8-89d9-a574741c49f0.png)
![update-click](https://user-images.githubusercontent.com/38660798/41240668-608a151c-6d9b-11e8-9aea-e845fd1840b2.png)

**Comment by tomasnorre** [comment]
Thanks for the additional information @anujaunds. I'll look into this, please be patient, I will leave for holiday in a few days, so cannot promise any answer right away.

**Comment by tomasnorre** [comment]
As version 6.7+ of the Crawler will only get security fixes and bug fixes added, I'll close your issue.

If you think it's still an issue please verify with dev-master and open a new issue.
Please refer to the old issue in that case.

Thanks
