### ISSUE TITLE
PHP Warning in CrawlerController in CLI mode

### ISSUE THREAD

**Issue by echavaillaz** [AOEpeople/crawler#307]
Hi,

When trying to run a Crawler task (For example "Crawler queue"), I got an  error : 

`Execution of task "Crawler queue (crawler)" failed with the following message: PHP Warning: explode() expects parameter 2 to be string, array given in /var/www/www.domain.tld/httpsdocs/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php line 821`

The problem comes from the line 618 `$res[$key]['paramParsed'] = $this->parseParams($values);`

Thanks,
Eric

**Comment by tomasnorre** [comment]
Thanks for the information @echavaillaz 

I'll have a look at it. 

Please let me know which TYPO3 version and Crawler version.

**Comment by echavaillaz** [comment]
Last TER version for Crawler and TYPO3 7.6.28.
Thanks!

**Comment by tomasnorre** [comment]
Thanks for the additional information @echavaillaz , will look into this, please be patient, I'll leave for holidays soon, so I cannot promise a response right away.

**Comment by echavaillaz** [comment]
No problem, I have found a way to bypass the warning yet. But I think it is a real bug you have to resolve here.

Nice holidays!

**Comment by tomasnorre** [comment]
You're more than welcome to provide a bugfix for this. Pull request are happily reviewed :)

**Comment by tomasnorre** [comment]
@echavaillaz Can you please paste me the exact command you are running from CLI?

**Comment by echavaillaz** [comment]
My solution is naive so I don't think a pull request is the right way now. But I could investigate a little more if you need my help.

For the command, there is several way to have the warning, for example, simply when running the task from the backend module or with A CRON command on the server.

Thanks

**Comment by tomasnorre** [comment]
ok. You wrote CLI mode in the title, so expected it to be from CLI.

**Comment by tomasnorre** [comment]
It's logic that we have a conflict here: 

`
 if (is_array($values)) {
                        ....
                        code-removed
                        ....
                            $res[$key]['paramParsed'] = $this->parseParams($values);
`

`
/**
     * Parse GET vars of input Query into array with key=>value pairs
     *
     * @param string $inputQuery Input query string
     * @return array
     */
    public function parseParams($inputQuery)
    {
        // Extract all GET parameters into an ARRAY:
        $paramKeyValues = [];
        $GETparams = explode('&', $inputQuery);
       ....
      code-removed
       .... 
    }
`

We a checking if we have an array, and parsing that to a function that expects a string, which again uses the explode (that also expects a string) 

I'll look into this.

**Comment by tomasnorre** [comment]
@echavaillaz Can you provide me with you crawler-configuration.. Would like to see how you have configured the crawler.

**Comment by echavaillaz** [comment]
What do you want to see exactly?
And indeed there is a logical issue here.

**Comment by tomasnorre** [comment]
I don't need it, found a way to reproduce :)

**Comment by nicodh** [comment]
I tapped into the same issue when trying to configure the parameters for the news extension.
The provided parameter are not expanded:

`tx_crawler.crawlerCfg.paramSets {
   news = &tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news;_PID:103;_WHERE: AND hidden = 0 ]

   news {
             procInstrFilter = tx_indexedsearch_reindex
   }
}`

When I analyzed the Controller I found that expandParameters is never called with the first line of configuration (news=&tx_news...) since there is a condition  
https://github.com/AOEpeople/crawler/blob/master/Classes/Controller/CrawlerController.php#L596
which is false for that line ($value is a string)

**Comment by tomasnorre** [comment]
Thanks for the detailed information @nicodh, I think you are right.. I'll look into this.
