### ISSUE TITLE
BackendModule reports error from crawling

### ISSUE THREAD

**Issue by pniederlag** [AOEpeople/crawler#317]
Hi,
the backend module always reports an error from the crawling. Diving in the code I think headers as well as the content reflect a correct crawling action.

However in  getResStatus($vv) of the Backend Module there is a call ` if (is_array($requestResult))` to determine the status of the request. Unfortunatly $requestResult is not an array so I end up with an 'Error:' in the `else` part.

https://github.com/AOEpeople/crawler/blob/189014e6d5cf6da510f0ef74c5b48391de2fc708/Classes/Backend/BackendModule.php#L886

**Comment by tomasnorre** [comment]
Hi @pniederlag 

Which TYPO3 version, and can you provide me with steps to reproduce ?

**Comment by pniederlag** [comment]
TYPO3 8.7.13

Unfortunatly I even can't reproduce it myself.

Things that might have changed in between and could have been part of the problem:

- baseUrl was still pointing to a different installation (local clone was not properly reconfigured)
- indexing configuration record for indexed_search used a "database" type for table pages instead of the "pagetree" type record

I'll keep an eye on it but maybe it was really just misconfiguration.

**Comment by pniederlag** [comment]
The reverse-proxy is likely to "choke" unexpected http headers... Do we have a list of headers that are required for the crawler to work correctly?

Funny enough, the content is availble as I can see in the $resStatus which is populated from $requestContent['content'] (which yields the correct html of our frontend).  Just for some reason somewhere something is taking the wrong route ...

**Comment by tomasnorre** [comment]
These are the headers set by the crawler: 
https://github.com/AOEpeople/crawler/blob/189014e6d5cf6da510f0ef74c5b48391de2fc708/Classes/Controller/CrawlerController.php#L1638

**Comment by tomasnorre** [comment]
I haven't been able to reproduce this yet @pniederlag .

Is this still a problem for you ?

**Comment by pniederlag** [comment]
@tomasnorre thx for getting back on this, highly appreciated.

It seems it was really a problem on our side with the reverse proxy not passing the proper headers to the backend. As we now bypass the reverse-proxy for crawling everything works fine.

**Comment by tomasnorre** [comment]
Super.. Happy to hear.
