### ISSUE TITLE
Compatibility with TYPO3 9.5

### ISSUE THREAD

**Issue by pixelbrackets** [AOEpeople/crawler#319]
Are there plans to make this extension compatible with TYPO3 9.5?

**Comment by tomasnorre** [comment]
Yes, We are planning on this, but we didn't get that far yet..
And unfortunately we don't have a time plan yet.

**Comment by tomasnorre** [comment]
I'm closing this issue as there are no concrete todo in it. 

I'll create issue for the Upgrade, when I have it all on my Radar, what needs to be done.
