### ISSUE TITLE
[DOCS] Add howto / best practices for specific use cases (e.g. indexing, cache warmup)

### ISSUE THREAD

**Issue by sypets** [AOEpeople/crawler#327]
I'm missing some common usecases / howtos / best practices for effectively using crawler. It is often mentioned that crawler is commonly used in combination with indexed_search to index pages or for cache warmup. What's a good setup for those usecases? May be a little beyond the scope of docs for crawler, but I'd much rather see this documented here, where it can be maintained by the community than in some blog.

**Comment by tomasnorre** [comment]
Related to #263.

I'll add this comment to the related issue, and close this issue.
