### ISSUE TITLE
[FEATURE] Use GuzzleHttp insted of custom fsockopen code

### ISSUE THREAD

**Issue by WebsiteDeveloper** [AOEpeople/crawler#330]
Was there ever a diskussion about using GuzzleHttp for the Frontend Requests to make the code cleaner and use libraries already included in typo3 core?

**Comment by WebsiteDeveloper** [comment]
I would be more than happy to contribute if needed :)

**Comment by tomasnorre** [comment]
Hi, 

I don't recall that discussion about using the GuzzleHttp instead, but we have been discussing using only direkt requests instead, and also planning to do it somewhen when we get so far. 

I would be happy to evaluate the GuzzleHttp implementation, so if you have the time it would be cool with a Pull Request covering that.

**Comment by WebsiteDeveloper** [comment]
Alright i think i'll put up a PR
As to compatibility i would say i'll implement the current request solution as a fallback für 7.6 because GuzzleHttp got included in 8.1

**Comment by tomasnorre** [comment]
@WebsiteDeveloper If you still want to do this, I would recommend doing it for the TYPO3V9 branch instead.

We then keep as is for the V7 and V8 compatible versions. 

PRs for both are of course welcome.

**Comment by tomasnorre** [comment]
Resolved with #457, but only for typo3v9 branch. 
Will not make it to 7 and 8 compatible versions.
