### ISSUE TITLE
Fatal error: Class 'tx_realurl' not found (TYPO3 8.7.20, realurl 2.4.0)

### ISSUE THREAD

**Issue by sdesign6** [AOEpeople/crawler#331]
I read some of the releated issues #87 #131 to the bug.
Is there a realistic chance or some progress to bring the crawling features of realurls back to TYPO3 8.7.x?  

Thx
Sven

**Comment by tomasnorre** [comment]
Hi, 

There are always options. Can you please post your comment in the #87 as it's a duplicate to that, the only difference is the TYPO3 version. 

Feel free to submit a Pull Request, if you want to help us getting forward with this topic.
