### ISSUE TITLE
pollSuccess

### ISSUE THREAD

**Issue by s-diez** [AOEpeople/crawler#336]
Hi,

I had some problems to work with "pollSuccess".

Is the following code in \AOE\Crawler\Hooks\TsfeHook::fe_eofe correct? You check for `$params['pObj']->applicationData['tx_crawler']['content']['parameters']['procInstructions']` but the information about active procInstructions normally resides in `$params['pObj']->applicationData['tx_crawler']['parameters']['procInstructions']`.

https://github.com/AOEpeople/crawler/blob/708d8565f80029cf63e300e02fa2f38f4b77ea17/Classes/Hooks/TsfeHook.php#L124-L132

**Comment by tomasnorre** [comment]
Can you please provide us with: 
Crawler Version, TYPO3 Version and PHP Version. 

Thanks

**Comment by s-diez** [comment]
Sure. And thanks for the fast reply.

Crawler: 6.2.0
Typo3: 8.7.24
PHP: 7.1.6

**Comment by tomasnorre** [comment]
I think you are right, but will have to dig into this. 

I'll see if I can provide tests for the code, it's one of the parts not covered by tests :( 

FYI: I lead me to another mistake - Folder/Namespace was wrong for the Classes/Task tests. 
Thanks

**Comment by tomasnorre** [comment]
@s-diez Can you very if it works with your suggested change? That would help my verification process. 

Thanks

**Comment by s-diez** [comment]
Yes changing the if statement in Line 126 to 

```php
if (is_array($params['pObj']->applicationData['tx_crawler']['parameters']['procInstructions']) && in_array($pollable, $params['pObj']->applicationData['tx_crawler']['parameters']['procInstructions'])) {
```

Triggers an error as expected if I do not set the success flag for my procInstruction.

**Comment by tomasnorre** [comment]
Thanks, Then it for sure sounds like you are right. 

As mentioned will see if I can prove this with unit/functional tests as well.

**Comment by tomasnorre** [comment]
I've started writing Tests for this class, hopefully I'll be done in the near future so this can be adjusted and merged.

**Comment by tomasnorre** [comment]
Hi @s-diez 

Would it be possible that you could help writing tests for this? It would be really helpful to me. 
It would be great if you could take care of both 6.7.x (TYPO3 7 & 8) version. 

but also the new 9.0.0 (TYPO3 9 & 10) version.

**Comment by s-diez** [comment]
Hi @tomasnorre 

I can try to take a look at it. I have very little experience with tests in TYPO3. But it will probably take some time. I'll write again when I have started and can give more informed feedback whether I can contribute and when.

**Comment by tomasnorre** [comment]
Thanks. I have experience with the tests, but this area is troubling me. 
So perhaps joined forces could be a solution. 

Let me know if you need anything from me.

**Comment by tomasnorre** [comment]
Still relevant
