### ISSUE TITLE
trim() expects parameter 1 to be string

### ISSUE THREAD

**Issue by rreichen** [AOEpeople/crawler#341]
starting the crawler I get the folowing error message:
"Core: Error handler (BE): PHP Warning: trim() expects parameter 1 to be string, object given in /srv/www/vhosts/typo3/cms/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php line 2223" 
I tried the following workaround:
   if (gettype($conf) == "string") {$parameter = trim($conf);} else {$parameter = $conf;	}
instead of:
   $parameter = trim($conf);
So the described error was gone and I got annother one in  ../sysext/core/Classes/Utility/GeneralUtility.php 
   at line 1302: "explode() expects parameter 2 to be string"
   at line 1318: "array_map(): Argument #2 should be an array"
Now I need professional help.

**Comment by rreichen** [comment]
add on to #341
I forgot telling my versions: They are:
TYPO3 version 8.7.24
crawler Version: 6.3.0

**Comment by adrienjacob** [comment]
Same here with 8.7.24 and crawler 6.3.0... no problem with 6.2.0

**Comment by rreichen** [comment]
At my Installation there is also no problem with 6.2.0.
Now I changed my Workaround at line 2223:
if (gettype($conf) == "string") {
  $parameter = trim($conf); 
  return ($parameter != '' ? GeneralUtility::trimExplode(',', $parameter) : []);
}
without knowing about any consequences I think it works fine. 
I hope to get a professional feedback!

**Comment by chris246** [comment]
Same issue here.  
Same versions as @adrienjacob

**Comment by tomasnorre** [comment]
Thanks for your input.. Would be happy to review a Pull Request.

**Comment by tomasnorre** [comment]
This is a regression introduced in 6.3.0 I'll fix this asap. 

Thanks for reporting

**Comment by tomasnorre** [comment]
The function call is deprecated.. 

Did you already switch to the new commandController ? Are are you still using the "old" way? 

It's for sure a bug, that I introduced, but will check how to fix this at best and asap.

**Comment by tomasnorre** [comment]
@rreichen 

Can you please test this fix? 

```
    /**
     * Obtains configuration keys from the CLI arguments
     *
     * @param QueueCommandLineController $cliObj
     * @return array
     *
     * @deprecated since crawler v6.3.0, will be removed in crawler v7.0.0.
     */
    protected function getConfigurationKeys(QueueCommandLineController $cliObj)
    {
        $parameter = trim($cliObj->cli_argValue('-conf'));
        return ($parameter != '' ? GeneralUtility::trimExplode(',', $parameter) : []);
    }
```

This was a change that should never have been made. 

Appreciate your feedback.

**Comment by rreichen** [comment]
@tomasnorre

Oh yes. I tested it and I didn't see any errors. So I think your fix is successful.

You wrote, this fix would be removed in nexed version v7.0.0. On the supposition that  the function "getConfigurationKeys" in v6.3.0 is the new one, I ask me what to change on my configuration for using it in future without having the described problems again? Are there any Informations?

**Comment by tomasnorre** [comment]
@rreichen Thanks for testing.

The Documentation isn't adjusted yet.. 

But you would need to run it with the CommandController (typo3-console) instead.

I'll update the documentation.

**Comment by tomasnorre** [comment]
The will be a new crawler version release later this morning with the fix. 

Thanks for all who participated in fixing, testing, reviewing etc.

**Comment by infabo** [comment]
Is this still an issue? I have this excact error and I cant find any info about this in the documentation.

```
 vendor/bin/typo3 crawler:buildqueue --page 3

Uncaught TYPO3 Exception trim() expects parameter 1 to be string, null given
thrown in file /home/vs183nap/www/releases/375/private/typo3conf/ext/crawler/Classes/Command/BuildQueueCommand.php
in line 209
```

**Comment by infabo** [comment]
typo3 v9 branch

**Comment by tomasnorre** [comment]
I would need to check that. Could you please open a new issue, and reference this one? 

I would like to keep the issue for master and typo3v9 separated, as the code base differs quite a lot currently.
