### ISSUE TITLE
Branch typo3v9 already functional?

### ISSUE THREAD

**Issue by Raemy92** [AOEpeople/crawler#344]
Hi

I just wanted to ask if your branch "typo3v9" is already working on Typo3 9.5? Since it doesn't seem that indexed_search works well without crawler.

**Comment by tomasnorre** [comment]
@Raemy92 Unfortunately not.. It's a work in progress branch.

The Index search should work without the crawler, but you need to accept indexing over frontend calls. Don't remember exactly how the setting is called. 

But as I recall it, it's in the extension settings for indexed_search.

**Comment by Raemy92** [comment]
@tomasnorre thanks for your reply. We  had to disable indexing in frontend because of this error: https://forge.typo3.org/issues/84541

**Comment by tomasnorre** [comment]
Sorry to hear that it's not working out for you. 

I cannot promise anything about the development of a TYPO3 V9 compatible version. I working on it in my spare time only.
