### ISSUE TITLE
Make commands and tasks compatible with TYPO3 9

### ISSUE THREAD

**Issue by CDRO** [AOEpeople/crawler#349]
#The TYPO3 `CommandLineController` is deprecated, instead it is proposed to use the Symfony commands or use Extbase Command Controllers, which are already depreacated in TYPO3 9.

My proposal would be to update the commands to use Symfony.

Subsequently, the Scheduler Task Classes have to be updated too (of course) to use the new classes.

Everything can be started in cli as Symfony commands so this would also deprecate the `cli` folder and the calls to `cli_dispatch.phpsh`.

TODO list:

- [ ] Make all CLI commands compatible with Symfony
- [ ] Adapt scheuler tasks to update the way the cli is called
- [ ] Remove `cli` folder
- [ ] Update documentation

**Comment by tomasnorre** [comment]
This is already changed to use the CommandController from the TYPO3 Console:
https://github.com/AOEpeople/crawler/commit/fb7f1a4705f4bf3dbe08707c8fe92d493140542e

But Perhaps some of your todos are still valid. Can you please check against master, what still open.. Create new issues, and refer to this issue. Thanks.

**Comment by CDRO** [comment]
I merged the changes and put up a PR for it.
