### ISSUE TITLE
AJAX Call in CE Content Menu throws PHP Fatal Error

### ISSUE THREAD

**Issue by pvanhemmen** [AOEpeople/crawler#35]
TYPO3 7.6
crawler 5.0

With the crawler extension installed the CE context menu stops working and throws a PHP Fatal Error each time it is clicked. From the log:

```Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP Catchable Fatal Error: Argument 1 passed to tx_crawler_contextMenu::main() must be an instance of clickMenu, instance of TYPO3\CMS\Backend\ClickMenu\ClickMenu given, called in /var/www/staging.example.org/typo3_src-7.6.0/typo3/sysext/backend/Classes/ClickMenu/ClickMenu.php on line 488 and defined in /var/www/staging.example.org/public/typo3conf/ext/crawler/class.tx_crawler_contextMenu.php line 43 | TYPO3\CMS\Core\Error\Exception thrown in file /var/www/staging.example.org/typo3_src-7.6.0/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111. Requested URL: http://staging.example.org/typo3/index.php?ajaxID=%2Fajax%2Fcontext-menu&ajaxToken=a3774c8d3796a751e31882c20de9e5c4c582a53b&table=tt_content&uid=227&listFr=1 ```

Hope that helps!

**Comment by tomasnorre** [comment]
From Slack: https://typo3.slack.com/archives/cig-crawler/p1447668840000009

PHP Catchable Fatal Error: Argument 1 passed to tx_crawler_contextMenu::main() must be an instance of clickMenu, instance of TYPO3\CMS\Backend\ClickMenu\ClickMenu given, called in /Applications/XAMPP/xamppfiles/htdocs/wat/typo3_src/typo3/sysext/backend/Classes/ClickMenu/ClickMenu.php on line 488 and defined in /Applications/XAMPP/xamppfiles/htdocs/wat/typo3conf/ext/crawler/class.tx_crawler_contextMenu.php line 43

**Comment by tomasnorre** [comment]
Please also check this.. 
From Slack: https://typo3.slack.com/archives/cig-crawler/p1447668559000003
