### ISSUE TITLE
Report: Remove DLOG Checks

### ISSUE THREAD

**Issue by CDRO** [AOEpeople/crawler#358]
The DLOG checks have to be removed as this is a hard breaking change in TYPO3 9.

In the same step the logging should be switched to the standard Logging as well.

**Comment by tomasnorre** [comment]
I'll update the description.. Have prepared some "backlog" for the update. Will do it tomorrow or Friday.

**Comment by CDRO** [comment]
I've already done some of it, but I screwed up the commit...

Find attached the patch:
[358.patch.gz](https://github.com/AOEpeople/crawler/files/3208610/358.patch.gz)

**Comment by tomasnorre** [comment]
Resolved
