### ISSUE TITLE
[DEPRECATION] Use of static class method call "TYPO3\CMS\Backend\Utility\BackendUtility::deleteClause()"

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#369]
**Please based a PR on the typo3v9 branch**
https://github.com/AOEpeople/crawler/tree/typo3v9

https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-83118-DeleteClauseMethods.html

See:
https://report.typo3-crawler.com/

*Files*
Classes/Controller/CrawlerController.php

PS: We would like to thank anyone helping out with the TYPO3V9 Compatibility, please add your name to CONTRIBUTERS.md, as some of the merges can harm the history and your credits can be lost.

**Comment by tstahn** [comment]
This seems to be resolved. Neither the current report nor the code base of the `typo3v9` branch mentions `TYPO3\CMS\Backend\Utility\BackendUtility::deleteClause()` at any point.

**Comment by tomasnorre** [comment]
Is fixed in  https://github.com/AOEpeople/crawler/commit/c462d929f79630ff9fae8adf51fa410960d3fbe1
