### ISSUE TITLE
Crawling Processes Page information getting into failure url when you click on any of the buttons there (Typo3 7.6.0)

### ISSUE THREAD

**Issue by julianstefanov** [AOEpeople/crawler#37]
When you get to the Backend Info page, then select the Site Crawler information page and then select the "Crawling Processes" from the Page information select box you got 3 buttons:
"Refresh", "Enable crawling" and "Show finished and terminated processes".
If you click on any of them, the right typo3 backend iframe window loading the index of the typo3 backend.
Look at the screenshots:
1 screen: the exact page where the buttons are
2 screen: the result when you click on any of them

![1](https://cloud.githubusercontent.com/assets/12820618/11236965/3572cbbc-8ddd-11e5-908d-71d4bece5a1b.png)

![2](https://cloud.githubusercontent.com/assets/12820618/11236966/39cc76cc-8ddd-11e5-8180-b810a37ef783.png)

**Comment by tomasnorre** [comment]
Thanks for letting us know, I'll take a look.

**Comment by tomasnorre** [comment]
I can confirm this issue.. I'll dig more into it. 
Thanks for reporting.
