### ISSUE TITLE
[BUG] Requirement for PHP extension posix fails on Windows

### ISSUE THREAD

**Issue by pixelbrackets** [AOEpeople/crawler#384]
Hey,

the package requires the PHP extension posix `"ext-posix": "*"`. However if the package is installed on Windows then Composer will fail due to a missing PHP extension "posix".

The problem is, that it is not possible to install »posix« on Windows, as stated on https://www.php.net/manual/en/intro.posix.php
>     Note: This extension is not available on Windows platforms.

Is it possible to remove this as a dependency, and only use it in the package if the system provides it?

![image003](https://user-images.githubusercontent.com/1592995/61374045-aa2d3f00-a89b-11e9-89b0-8fb5752bde70.jpg)

**Comment by tomasnorre** [comment]
That sounds reasonable.

Would you be able to provide a Pull Request, then I would be happy to review and merge.

Thanks in advance.

**Comment by tomasnorre** [comment]
I think is code-wise already ok, it's just a matter of moving the composer requirement to suggestion instead. Then we should be good to go.

That's at least how I read it.

**Comment by tomasnorre** [comment]
Closed with #386
