### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by Hobokens** [AOEpeople/crawler#405]
Hi,
after upgrading crawler to version 6.6.2 in a TYPO3 Installation 8.7.27 I get the following error with crawler run.

`Core: Exception handler (CLI): Uncaught TYPO3 Exception: Call to undefined method AOE\Crawler\Domain\Repository\ProcessRepository::findByUid() | Error thrown in file /html/typo3/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php in line 2390  `

Regards
Hobokens

**Comment by tomasnorre** [comment]
Triggering from backend in the scheduler ? 
I had this issue with 6.6.0 and 6.6.1 but not with 6.6.2. 

Could it be caching problem?

**Comment by Hobokens** [comment]
Sorry, it was my fault. I missed to upate to version 6.6.2.
Thanks for your great extension.

**Comment by tomasnorre** [comment]
You're welcome, let me know if you're having any problems.
