### ISSUE TITLE
[BUGFIX] Unknown column 'tx_crawler_process.uid' in 'where clause'

### ISSUE THREAD

**Issue by Ceremony64** [AOEpeople/crawler#408]
I have an issue with version 6.6.2 on Typo3 v8.7.27 where it'll stop processing pages right away and end with the following error:
```add process 3a5a13f1eb (1/15)
TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException: Unknown column 'tx_crawler_process.uid' in 'where clause'
Unprocessed Items remaining:168 (3a5a13f1eb)
```

I believe `uid` should be `process_id`, but I'm not entirely sure where exactly in the code, this issue occurs, as it doesn't output a trace on error unfortunately.

EDIT: I suspect line 2391 in CrawlerController.php is at fault:
`$this->processRepository->findByUid`
findByUid queries the Uid after all and not the process_id.

**Comment by tomasnorre** [comment]
Thanks for you report, will look into this asap, as we also encountered a bug regarding crawling with UserGroups.

Can you give me steps how to reproduce this?

**Comment by tomasnorre** [comment]
@Ceremony64 Could you test if this is also an issue with the CommandController by using the `typo3cms`

**Comment by tomasnorre** [comment]
@Ceremony64 Could you please test and verify?
https://github.com/AOEpeople/crawler/pull/411

**Comment by Ceremony64** [comment]
Will do tomorrow!

**Comment by Ceremony64** [comment]
Well... This one is kinda fixed: I did a run with a 5 page limit. Upon parsing the first page, it now generates a new process every time, overwriting the last and does another 5 pages, thus fetching every page in the queue instead of stopping after the first 5.

The issue seems to be, that while the query to find the process completes with results, all results are basically clean processes with no values set:
```
array(10) {
    ["row"] => NULL
    ["processId"] => string(0) ""
    ["active"]  => bool(false)
    ["ttl"] => int(0)
    ["assignedItemsCount"] => int(0)
    ["deleted"] => bool(false)
    ["systemProcessId"] => string(0) ""
    ["queueRepository"] => NULL
    ["uid"] =>int(0)
    ["pid"] =>int(0)
  }
```

**Comment by tomasnorre** [comment]
Yes please create a new issue for this.. I'm preparing a release right now.. So will not enter before the next, but will release again when there is a fix.
