### ISSUE TITLE
[BUGFIX] "Pids only" ignored since 6.6.0

### ISSUE THREAD

**Issue by Ceremony64** [AOEpeople/crawler#409]
Crawling a specific page(s) by specifying "Pids only" in the Crawler Configuration is broken with version 6.6.0 and up. The setting gets ignored and instead, every page in the tree is crawled.

Thus, if you use this to configure indexing news entries of the news extension, it now indexes cartesian product of every page with every available news entry.

In my case, instead of indexing around 500 news entries, I ended up indexing over 80000 page-news-combinations

P.S. running typo3 8.7.27

**Comment by tomasnorre** [comment]
Thanks for letting us know, will look into this asap. As mentioned in #408, we would need to do a new release soonish anyway.

So this is really helpful.

**Comment by tomasnorre** [comment]
@Ceremony64 Could you please test with `master`.

I found another issue yesterday, when trying to debug this, and this might solve both problems, at least I cannot reproduce it.

**Comment by tomasnorre** [comment]
@Ceremony64 If I go back to the 6.6.2 version, I have the Issue you mentioned too.

So would expect it to be solved, but can you please verify?

**Comment by Ceremony64** [comment]
This seems fixed for me as well! :+1:
