### ISSUE TITLE
[BUG] Crawler limitation "Count in a run" does not work

### ISSUE THREAD

**Issue by Ceremony64** [AOEpeople/crawler#413]
I did a "Crawler Run" with a 5 page limit (Count in a run). Upon parsing the first page, the crawler generates a new crawler process and assigns it another 5 pages, overwriting the last 4 unhandled pages in the queue as well. Thus after each page-fetch, a new process gets spawned and the page fetch-limit resets every time. In the end, every page gets fetched instead of stopping after grabbing the first 5.

The issue seems to be, that while the query to find the process completes with results, all results are basically clean processes with no values set:
```
array(10) {
    ["row"] => NULL
    ["processId"] => string(0) ""
    ["active"]  => bool(false)
    ["ttl"] => int(0)
    ["assignedItemsCount"] => int(0)
    ["deleted"] => bool(false)
    ["systemProcessId"] => string(0) ""
    ["queueRepository"] => NULL
    ["uid"] =>int(0)
    ["pid"] =>int(0)
  }
```

Checking the raw query results (`$query->execute(true)`) does show the missing values. they are just not being assigned to the model correctly...

_Originally posted by @Ceremony64 in https://github.com/AOEpeople/crawler/issues/408#issuecomment-523381985_

**Comment by tomasnorre** [comment]
Do you have a twitter handle?

**Comment by Ceremony64** [comment]
Nah, sorry, I don't use twitter

**Comment by tomasnorre** [comment]
Ok.: Just wanted to mention you i the Thank you note.

**Comment by Ceremony64** [comment]
No need :) but thanks :D

**Comment by tomasnorre** [comment]
TYPO3 Slack ?

**Comment by Ceremony64** [comment]
Errr... nope, don't think so? At least I never used Slack, only their bugtracker: https://forge.typo3.org/users/41611

**Comment by tomasnorre** [comment]
No Problem.

**Comment by tomasnorre** [comment]
Do you have steps to reproduce this? 

Running in CLI context, backend?

PS: I delete our comments on twitter/slack to have the issue more clean.

**Comment by Ceremony64** [comment]
I merely had a queue list of a few hundred pages and configured "Crawler Run" with a 5 "Count in a run" limit. I then executed it via CLI scheduler and looked at the database while it was running. Thats how I noticed it just wouldn't stop and just create new processes and new queue (re-)assignments. Afterwards, I looked at the new findByProcessId method and noticed the empty Process objects

**Comment by tomasnorre** [comment]
Thanks. 

Would you be able to do a Pull request on this?

**Comment by Ceremony64** [comment]
I looked a bit into the empty QueryResult Process object(s), but didn't get anywhere. It seems like it isn't calling the datamapper at all to assign the query results to the Process-object(s). No clue why...

**Comment by tomasnorre** [comment]
ok, i'll try to debug this.

**Comment by tomasnorre** [comment]
When "fixing" the findByProcessId() then the process get added.
But the process list below doesn't get updated correctly.

I'll dig more into this to figure out what the Problem is.

This would need to go into the TYPO3V9 branch as well.

**Comment by tomasnorre** [comment]
@Ceremony64 Could you please test PR #437? 

This covers the fix for TYPO3V7 and V8.
I'll do a separate issue for the TYPO3V9.

**Comment by tomasnorre** [comment]
This is merged into master, can you please verify @Ceremony64, thanks.

**Comment by Ceremony64** [comment]
Nope, it's still not working correctly and ignoring the per-run limitation:
With a limitation of 5, it correctly assigns 5 items of queue to a single process, but after completing all 5, it just creates a new process and assigns it another 5.

**Comment by tomasnorre** [comment]
ok. Then I might have misunderstood you. I'll reopen the issue.

But do I understand you correctly, that you can continue with the current dev-master soon 6.6.4 release, and not have big issues atm?

I will look into this changed behavior later then (not later today), have enough on my plate atm.

**Comment by Ceremony64** [comment]
Well, the behavior changed slightly, so it did do something. It's just more than one bug.

Also, I just tested it again: Apparently this (new) issue only occurs when run via CLI and not by pressing "run" in the Typo3 backend. Via the webinterface, it stops processing after the limit has been reached. Via CLI, it just creates a new process with a new queue limit once a process finishes.

Aside from that, it seems to work, crawling just fine

**Comment by tomasnorre** [comment]
Thanks for you feedback. Will dig into it again.

**Comment by Ceremony64** [comment]
One more thing: Running the task via CLI will never end and cause a 100% load on a single thread.

**Comment by tomasnorre** [comment]
oh.. That's not good. 
Thanks for letting us know.

**Comment by tomasnorre** [comment]
@Ceremony64 
Do you start it with the `cli_dispatcher` or with `typo3cms crawler:crawlqueue` ?

**Comment by tomasnorre** [comment]
I just tested with teh `typo3cms crawler:crawlqueue` and cannot reproduce what you are mentioning.

Can you please provide step by step on how to reproduce the issue? 
Thanks.

**Comment by Ceremony64** [comment]
I used the cli_dispatcher

**Comment by tomasnorre** [comment]
Thanks. 

Can you please try to test with the `typo3cms crawler:crawlqueue`, the cli_dispatcher is deprecated, and will be removed in version 7.0.0.

I'm not saying i won't fix it for cli_dispatcher, I just want you to test it with the `typo3cms` too.

**Comment by Ceremony64** [comment]
I need to correct my previous statement: I didn't use cli_dispatcher nor typo3cms crawler:crawlquue, instead, I started the scheduler (which only had a single active job, the "Crawler Run"):
`php /path/to/webfolder/typo3/sysext/core/bin/typo3 scheduler:run`

typo3cms crawler:crawlqueue seems to be only available on typo3 with composer, so for me that would be `/sysext/core/bin/typo3 crawler:crawlqueue` instead. However, crawler doesn't seem to be registered as it is not listed among the available registered commands...

**Comment by tomasnorre** [comment]
I think you are into something there.

The cliPath calculation is expecting composer which isn't also present. I would need to figure out how to do this differently. 

The `php /path/to/webfolder/typo3/sysext/core/bin/typo3 scheduler:run` shouldn't be a problem either. But the it's the same as triggering it from backend over the scheduler-module.

**Comment by Ceremony64** [comment]
FYI, the crawler is listed under legacy commands:
```
Using old "cliKeys" ($GLOBALS[TYPO3_CONF_VARS][SC_OPTIONS][GLOBAL][cliKeys]) is marked as deprecated and will be removed in TYPO3 v9:
Old entrypoint keys available:
  crawler
  crawler_flush
  crawler_im
  crawler_multiprocess
  extbase
  lowlevel_cleaner
  scheduler
```
those commands seem to only work with cli_dispatch tho... Should I also test cli_dispatch? It is deprecated after all and Typo3 v7 will be also be dropped soon anyway, so I don't think spending more time on a an already declared dead functionality is time well spent ^^

**Comment by tomasnorre** [comment]
I agree on that, but want to help people, when they have problems with the crawler.

**Comment by tomasnorre** [comment]
As we are trying to move forward and focus on the newer TYPO3 versions 9 & 10.
We will stop feature development of the older versions like 6.7.x 

We will still try to handle bugs and security issues will still have high priority.

I'll close this issue for now. 
If any questions or concerns please reach out to me, then we will talk about it, and figure out a solution together.

Thanks
