### ISSUE TITLE
[BUG] ClickMenu code not working

### ISSUE THREAD

**Issue by bmack** [AOEpeople/crawler#429]
The CrawlerClickMenu is not refactored for v9 yet. Either remove it or adapt it (also the registration process). 

We can have a look at EXT:impexp and their registration for the clickmenu. Should be fairly doable for bringing it up to v9.

**Comment by tomasnorre** [comment]
We have removed it for the TYPO3V8, so can be removed here as well.

**Comment by tomasnorre** [comment]
The is merged with #430
