### ISSUE TITLE
Rename the CLI user

### ISSUE THREAD

**Issue by stucki** [AOEpeople/crawler#439]
The user which is needed to run the CLI jobs has been renamed in TYPO3 8.7:  
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.6/Feature-79240-SingleCliUserForCliCommands.html

Tasks:
- All occurences in EXT:crawler need to be changed.
- Ensure compatibility with older versions (or add a conflict with TYPO3 v7 and below).
- Remove admin permission check / ignore the fact that the new `_cli_` user has admin permissions out of the box.

**Comment by tgaertner** [comment]
+1 for this reason the "typo3 crawler:buildQueue" Command doesn't work at all.
Btw. the documentation needs a lot of updates.

**Comment by tomasnorre** [comment]
I thought the documentation was ok on this point, but I would need to check, perhaps it's only updated in TYPO3V9 branch. 

Regarding the cli user name change please see the comment in #440

**Comment by tgaertner** [comment]
Mh I think I messed something up - got that one with the cli-user but can you check docs for the CommandController calls...

In docs:master it says: 
`$ vendor/bin/typo3 crawler:buildqueue [--startpage <page-id>] ...` but param --startpage is called "page" in source-code of 9.0.0-dev.

In docs:dev-master this section is completely gone. Don't get this (and don't get this call working) - sorry.

If this is a real issue I can open a new Ticket.

**Comment by tomasnorre** [comment]
Please open a new issue, then I'll check it.

**Comment by tomasnorre** [comment]
As we are trying to move forward and focus on the newer TYPO3 versions 9 & 10.
We will stop feature development of the older versions like 6.7.x 

We will still try to handle bugs and security issues will still have high priority.

I'll close this issue for now. 
If any questions or concerns please reach out to me, then we will talk about it, and figure out a solution together.

Thanks
