### ISSUE TITLE
[BUG] Process Progress in backend, stopping after 1 entry crawled

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#444]
This is "only" a problem with "make direct requests" the Guzzle variant works as expected.

**Comment by tomasnorre** [comment]
Looks like this isn't a problem anymore after fixing #463 

Can someone please verify?

**Comment by tstahn** [comment]
If that's what we're talking about, it doesn't seem to be an issue anymore, see

![Bildschirmfoto 2019-10-21 um 21 29 20](https://user-images.githubusercontent.com/32361706/67236637-f6af8a00-f449-11e9-8302-a6cb2713b78a.png)

**Comment by tomasnorre** [comment]
As this is confirmed I will close this issue.
