### ISSUE TITLE
Crawling Processes Page Information - Refresh button does not work as expected in TYPO3 6.2

### ISSUE THREAD

**Issue by vdespa** [AOEpeople/crawler#45]
This is related to the change made in relation to this issue #37 (52c7b2d99d6d9e29b32506c19c3652cdd1ebb961).

The commit introduces a regression. 

Steps to reproduce in crawler version 5.0.1, TYPO3 6.2 or 7.6.2:

1. Add pages to the crawler queue (5-10 pages)
2. Manually start crawling processes (Add process)
3. Click reload (maybe multiple times).
4. When the processes are finished and exit, you will start seeing the error (because instead of refreshing you keep adding processes):

![screen shot 2016-01-20 at 16 54 42](https://cloud.githubusercontent.com/assets/1197635/12454196/c46ef184-bf96-11e5-86ce-bcd752e7075f.png)

It seems that the action which is executed on "Refresh" is still "Add process" or most probably the last executed task.

**Comment by tomasnorre** [comment]
Hmm.. Will have a look, just updated today in another project. Will have to check tomorrow.. 

Thanks for reporting.
