### ISSUE TITLE
[BUG] Crawling Depth not respected

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#464]
Steps to reproduce:

1. Add a new crawler configuration, only set the name
2. Go to the crawler
3. Select the Top page, and Infinite in depth
4. Press "update" or "crawl urls" 
5. Count will be one, should be higher as subpages should be crawled too.

**Comment by tomasnorre** [comment]
I'm not sure yet, think this is related to a false configured Site Configuration in my Devbox.

**Comment by tstahn** [comment]
Hi @tomasnorre, I gave this a quick go with one of my TYPO3 9 projects and the current `typo3v9`. Following your steps, it seems to work absolutely fine for me:

![Bildschirmfoto 2019-10-17 um 09 02 16](https://user-images.githubusercontent.com/32361706/66985961-2feca080-f0be-11e9-81e2-1a0e94e243c6.png)

**Comment by tomasnorre** [comment]
I have full ddev.site domain as my URL.

**Comment by tomasnorre** [comment]
It works on my setup now too.

I'll switch the task, to be Update Troubleshooting instead.
Till Then: 

The Problem was the Upgrade Wizards Slugs wasn't done.

**Comment by tomasnorre** [comment]
I'll close this as it wasn't a bug, but a missing Upgrade Wizard step.

I've updated the documentations Troubleshooting, to help other in the future.
