### ISSUE TITLE
Regression - Crawler cannot create new processes

### ISSUE THREAD

**Issue by vdespa** [AOEpeople/crawler#47]
It seems that the commit 656cd90 introduced a regression. Occurs in TYPO3 6 & 7 LTS.

**Steps to reproduce:**

1. Add pages to the crawler queue
2. In BE, go to the Process Overview and add try to start a new process
3. The process will not start and an error will appear.

![screen shot 2016-01-22 at 09 21 02](https://cloud.githubusercontent.com/assets/1197635/12505710/988c391a-c0e9-11e5-8c97-f3793740a35d.png)

Or

1. Add pages to the crawler queue
2. In the Scheduler, create and start the Crawler Run task.
3. Two PHP warnings will occur but no entries from the queue will be executed.

![screen shot 2016-01-22 at 09 25 09](https://cloud.githubusercontent.com/assets/1197635/12505816/582812d0-c0ea-11e5-8f65-b559a089aed8.png)

**Comment by tomasnorre** [comment]
Hi @vdespa 

I cannot reproduce this with current master either on 6.2.15 or on 7.6.2 

Can you please check again?
