### ISSUE TITLE
[BUG] ContextMenu is not working in TYPO3 9LTS

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#471]
## Bug Report

**Current Behavior**
When I right-click at a page in page-tree i don't see the more > Crawl option

**Expected behavior/output**
When I right-click at a page in page-tree I expect to see the more > crawl option

**Environment**
- Crawler version(s): dev-typo3v9
- TYPO3 version(s): 9.5.10

**Comment by tstahn** [comment]
Hey @tomasnorre, as far as I understand the code and the documentation the »Crawl« context menu item is added to `tx_crawler_configuration` records, and was never meant to work on `pages`.

see my local environment (in which this works as intended by the way):
![Bildschirmfoto 2019-10-21 um 22 30 38](https://user-images.githubusercontent.com/32361706/67241000-e354ec80-f452-11e9-83fa-15ec3d019e96.png)

Documentation:
https://docs.typo3.org/p/aoepeople/crawler/master/en-us/ExecutingTheQueue/AddingEntriesToTheQueueByContextMenue/Index.html

Do you want us to add it to pages as well, or is the existing solution sufficient?

**Comment by tomasnorre** [comment]
No it's fine as is.. 

Just though it was different in the current-master, but it isn't.

We will keep it as is, and if a Feature Request comes in we can evaluate again.
