### ISSUE TITLE
[BUG] Process States Information uncompleted

### ISSUE THREAD

**Issue by rreichen** [AOEpeople/crawler#473]
## Bug Report

At Backend-Page "Info" the crawler Information-table "Process States" is  uncompleted. So the two colums "Time first item" and "Time last item" are not filled and column "Runtime" shows 0. 

My Environment
- Crawler version: 6.6.5
- TYPO3 version: 8.7.28

**Comment by rreichen** [comment]
![crawler_process_states](https://user-images.githubusercontent.com/18324572/67943688-e2eaed00-fbda-11e9-8032-de552d4d6ce3.jpg)

**Comment by tomasnorre** [comment]
Thanks for you information. Will look into this. I have a similar setup that I can test on.

**Comment by tomasnorre** [comment]
I can confirm this. Will look into this. Thanks for reporting @rreichen.

Do you have a possibility to debug and create a PR for this?

**Comment by tomasnorre** [comment]
@rreichen Can you please test the branch?
https://github.com/AOEpeople/crawler/tree/issue/473

If you report ok, i'll have it merged.

**Comment by rreichen** [comment]
Hallo Tomas,

I tested it, and it is OK. All process information fields are filled now.

Thanks - Roland

Von: Tomas Norre Mikkelsen [mailto:notifications@github.com]
Gesendet: Freitag, 8. November 2019 08:47
An: AOEpeople/crawler <crawler@noreply.github.com>
Cc: Reichenauer, Roland <Roland.Reichenauer@RHEINGAU-TAUNUS.DE>; Mention <mention@noreply.github.com>
Betreff: Re: [AOEpeople/crawler] [BUG] Process States Information uncompleted (#473)


@rreichen<https://github.com/rreichen> Can you please test the branch?
https://github.com/AOEpeople/crawler/tree/issue/473

If you report ok, i'll have it merged.

**Comment by tomasnorre** [comment]
I'll reopen as it isn't merged yet.
