### ISSUE TITLE
Respect configuration from TSconfig when creating scheduler task

### ISSUE THREAD

**Issue by DanielSiepmann** [AOEpeople/crawler#478]
## Bug Report

**Current Behavior**
No configuration from TSconfig is shown when creating a new scheduler task to create a queue. Only records from DB are listed.

**Expected behavior/output**
The available select options should also list available configurations from TSconfig.

**Environment**
- Crawler version(s): 5.2.0 (tested) master (by inspecting code)
- TYPO3 version(s): 6.2 (should not be tight to TYPO3, it is internal)
- Is your TYPO3 installation set up with Composer (Composer Mode): no (should not matter)

**Possible Solution**
Adjust https://github.com/AOEpeople/crawler/blob/6.7.0/Classes/Task/CrawlerQueueTaskAdditionalFieldProvider.php#L99 to also fetch available TSconfig options.

NOTE: This introduces the need to have them globally defined. Adding them on sub pages would make it necessary to iterate over all pages including static TSconfig or having inline TSconfig. Maybe one could document to only support rootpages or something like that.

**Comment by tomasnorre** [comment]
Thanks for your report @DanielSiepmann.
I'll look into this and make sure we find a solution for dev-master and typo3v9 branch.

**Comment by tomasnorre** [comment]
Hi @DanielSiepmann,

After switching to the Symfony Command Controller for the Scheduler tasks, the crawler configuration isn't selected from a generade select box anymore. 

but it's a plain text field, so you can add whatever configuration you have. 
Does this solve your problem?

**Comment by DanielSiepmann** [comment]
Sure, thank you. Don't know which project needed this, I just reported it because it sounded like an missing but expected feature.
A free text field of course solves the issue. Thank you for taking care.

**Comment by tomasnorre** [comment]
Thanks for you feedback. Will keep it in mind, if I need to change the implementation sometime.
