### ISSUE TITLE
[FEATURE] add _RECURSIVE option to the subpartParams Configuration of the lookup _TABLE instructions

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#479]
## Bug Report

Please check if this also applies for the typo3v9 branch.
https://github.com/AOEpeople/crawler/pull/477

**Comment by tomasnorre** [comment]
@vzz3 Do you have the possibility to check if this also applies to the typo3v9 branch ?

**Comment by vzz3** [comment]
I can probably implement that for the typo3v9 branch as well. However, I don't know how I should test it. Does the head of the typo3v9 branch already run under TYPO3 9 LTE or should I test with TYPO3 8 LTE?

**Comment by tomasnorre** [comment]
The typo3v9 branch is already running under TYPO3 9 LTS, so if you have a 9 setup somewhere, it should be fairly easy to test it.

Thanks for helping out. 
There is even a ddev setup for the crawler, so it should be fairly easy to set up for testing.
https://github.com/AOEpeople/crawler-devbox/tree/feature/ddev

**Comment by tomasnorre** [comment]
This is merged, will close the issue. 
Thanks @vzz3
