### ISSUE TITLE
Exeption on creating Configuration Record

### ISSUE THREAD

**Issue by tgaertner** [AOEpeople/crawler#482]
## Bug Report

**Current Behavior**
When I try to create a new crawler configuration record via the list module in the backend I get: 
SQL error: 'Field 'sys_domain_base_url' doesn't have a default value' (tx_crawler_configuration:NEW5ddfd5616b13d570651294)

**Environment**
- Crawler version(s): 9.0.0-dev (dev-typo3v9)
- TYPO3 version(s): 9.5.11
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
Thanks for you report @tgaertner,

I've tried to reproduce this with following steps:

1. List view
2. Create new Crawler Configuration
3. Add Name Only
4. Press save

This works for me.  Do you do anything different than me?
Have you done "Analyse Database" to see if some definitions are not up to date?

**Comment by tgaertner** [comment]
Thanks for the quick response!

DB is up to date. All other records and normal backend work works fine.
Yes I do the same steps. What I don't undersatand is: the field mentioned in the error soes not exist at all...

I'll check this on a plain installation - just in case - and will give feedback on this.

**Comment by tgaertner** [comment]
On a plain composer v9 installation it works. So it must have something to do with my installation. So its not a bug in the crawler - sorry.

If I find the reason I'll let you know if its a conflict or something worthy to mention in the docs.

**Comment by tomasnorre** [comment]
Don't be sorry, I'm always interesting in feedback and it could easily be the crawler being the problem.

Reach out if you find something.

**Comment by tgaertner** [comment]
Found it. I first installed the latest official version 6.7.0.
After that I updated (composer) to current dev-typo3v9 - without deleting the old fields from the db-tables. So there is indeed a field "sys_domain_base_url" from the error-message. 
I don't know if this is helpful to improove something that. Maybe a hint in the docs in section trubbleshooting :-)

**Comment by tomasnorre** [comment]
Thanks for the information, could you make a PR for the

**Comment by tgaertner** [comment]
done.

**Comment by tomasnorre** [comment]
Thanks.
