### ISSUE TITLE
It is not possible to run the BuildQueueCommand from the scheduler at TYPO3 v9

### ISSUE THREAD

**Issue by vzz3** [AOEpeople/crawler#484]
## Bug Report

**Current Behavior**
The native scheduler task `CrawlerQueueTask` was removed in [b7411a3]. I guess it is intended that the automated queue item record creation should be done by executing the `BuildQueueCommand` with the help of the `ExecuteSchedulableCommandTask` from the scheduler extension. However that does not work at the moment because required command _options_ like conf, page, depth... can not be set from the Task interface of the scheduler. 
While the `ExecuteSchedulableCommandTask` provides input fields for Symphony command _arguments_ it does not provide _inputs_ for command options (see: `TYPO3\CMS\Scheduler\Task\ExecuteSchedulableCommandAdditionalFieldProvider`). However the CrawlerQueueTask uses only options and no arguments.

**Expected behavior/output**
It should be possible to schedule the queue item record creation like it was in TYPO3 v8. Therefore, the options  Start page, Depth, Configuration must be maintainable in the scheduler task interface.

**Environment**
- Crawler version: 9.0.0-dev
- TYPO3 version: 9.5.9
- Composer Mode: yes

**Comment by tomasnorre** [comment]
Thanks for  your report, will look into this.

**Comment by tomasnorre** [comment]
@vzz3 you mean the "Execute Console Commands" right ? Otherwise you have a functionality that I don't have in my backend, but could be.

But with the "Execute Console Commands" I can confirm that the AddtionalFields are missing.

**Comment by tomasnorre** [comment]
It's btw. a problem for all 3 Command Controllers for the Crawler, no params are included. Will check this out and fix this.

**Comment by vzz3** [comment]
Yes, exactly! The PHP class name of the Scheduler Task "Execute Console Commands" is `ExecuteSchedulableCommandTask`.

A possible solution could be to extend the classes `ExecuteSchedulableCommandTask` and `ExecuteSchedulableCommandAdditionalFieldProvider` and provide additional input for symfony console command _options_ like it is already implemented for `arguments` (see `ExecuteSchedulableCommandAdditionalFieldProvider->getCommandArgumentFields()`). 
Furthermore, we should write a feature request for the TYPO3 core, where we ask for support of  symfony console command _options_ directly in `ExecuteSchedulableCommandTask`. If this get implemented e.g. for TYPO3 v10 we would not need to maintain this workaround for a long time.

**Comment by tomasnorre** [comment]
Thanks, this patch is related to the issue here.
https://review.typo3.org/c/Packages/TYPO3.CMS/+/61696

**Comment by vzz3** [comment]
Thanks for finding that patch! Really nice that this problem already gets addressed. I will have a look and probably vote for the patch.

**Comment by tomasnorre** [comment]
I wasn't the one finding it. :) asked on slack on the topic, and was referred to it.

**Comment by tomasnorre** [comment]
https://typo3.slack.com/archives/C025BQLFA/p1575359769132000?thread_ts=1575358795.131300&cid=C025BQLFA

**Comment by vzz3** [comment]
I tested the patch. However, it did not work as expected because it was not possible to save changes of the command option. I edited the patch and pushed it to the review server. Unfortunately I'm not sure if I pushed it to the correct branch (or what ever), because my changes did go to a new "review page" (https://review.typo3.org/c/Packages/TYPO3.CMS/+/62548) instead of creating a new change set entry to the review page of Matthias Vogel (https://review.typo3.org/c/Packages/TYPO3.CMS/+/61696)

Another issue I observed during my tests is that the default values of the command options of the `ProcessQueueCommand` are confusing, because the are all zero for a new scheduler Task. I suggest to use the `$crawlerController->extensionSettings['countInARun'|'sleepAfterFinish'|'sleepTime']` as default argument directly in the addOption() cals, instead of overriding the default zeros during execution.

**Comment by tomasnorre** [comment]
Thanks for the additional information. 
Please see if you can get your changes pushed to the right review.

Regarding the default values, I think you are right, that it's a better option.

**Comment by vzz3** [comment]
I have pushed my changes to the TYPO3 master branch (https://review.typo3.org/c/Packages/TYPO3.CMS/+/61696). Now we need reviews ;-)

**Comment by tgaertner** [comment]
This was cherrypicked and is part of 9.5.14

**Comment by tomasnorre** [comment]
Thanks, will test this with the latest TYPO3 Version and bump the version requirements if it works out as expected.

**Comment by tomasnorre** [comment]
This works and is now updated.
