### ISSUE TITLE
[BUG] Force SSL from configuration record doesn't work

### ISSUE THREAD

**Issue by fl3s** [AOEpeople/crawler#492]
Forcing to use HTTPS from the configuration record doesn't work. It is stored as an integer (-1, 0 or 1), but returned from the model as a boolean. Later that boolean is used as an integer again, which gives an incorrect result in a switch. Changing the forceSsl property of the configuration model as well as the return type from boolean to integer solves the problem.

**Comment by tomasnorre** [comment]
Hi @fl3s,
Can you please tell me which versions:

Crawler?
TYPO3?

Thanks

**Comment by fl3s** [comment]
TYPO3 8.7
Crawler 6.7.0

The forceSsl property of the configuration model doesn't correspond with its TCA.

**Comment by tomasnorre** [comment]
Thanks for the additional information. Will look into this.
If you have fix already please add a Pull Request.

**Comment by fl3s** [comment]
https://github.com/AOEpeople/crawler/pull/493

There you go :)

**Comment by tomasnorre** [comment]
You PR is against typo3v9 branch. 
Could you make one for master as well ? I can it simply be cherry-picked ?

**Comment by fl3s** [comment]
Sure, here it is: https://github.com/AOEpeople/crawler/pull/494
