### ISSUE TITLE
typo3 crawler:buildqueue does not work or/and has wrong or missing documentation

### ISSUE THREAD

**Issue by tgaertner** [AOEpeople/crawler#496]
In docs:master it says:
$ vendor/bin/typo3 crawler:buildqueue [--startpage <page-id>] ... but param --startpage is called "page" in source-code of 9.0.0-dev.

In docs:dev-master this section is completely gone. Don't get this (and don't get this call working).

I try a call like this:
`./vendor/bin/typo3 crawler:buildQueue --page 3 --depth 3 --conf main --mode queue`
It results always in output "Putting 0 entries in queue:"

User _cli_ and user _cli_crawler exists. But the "getPagePermsClause" function always returns WHERE-clause "1=0"

**Comment by tomasnorre** [comment]
I'm really sorry for the crappy documentation. 

If you are running version 
you would need to use `typo3cms` binary, it isn't changed for the master branch to use the `typo3` binary instead of the `typo3cms`

This works for me in my TYPO3 8.7 setup with crawler 6.7.0
```
./typo3cms crawler:buildQueue --startpage <pageId> --depth <depth> --conf <configuration-name> --mode queue
```

If you can confirm that this is working for you as well.. I'll make sure that the documentation get updated asap.

**Comment by tgaertner** [comment]
Mh shouldn't it make no difference to use typo or typo3cms binary? If so the eytension should have a requirement for typo3-console.

Anyway, running the command with typo3cms gives me the expected result. BUT this has nothing to do that the param --startpage does not exist - at least in 9.0.0-dev.

My successful command was now this:

`./vendor/bin/typo3 crawler:buildQueue --page 3 --depth 3 --conf main --mode queue`

**Comment by tomasnorre** [comment]
dev-master has a requirement for typo3-console.

We need to focus a little here.

Is this bug report regarding dev-master or typo3v9 branch? 
Can easily be about both. But lets place separate it, as the adjustments and information differs. 

Which version are you running?

**Comment by tgaertner** [comment]
Thats the composer req:
`"aoepeople/crawler": "dev-typo3v9 as 9.0.0-dev"`

**Comment by tomasnorre** [comment]
Thanks.

Then I'll make sure that the documentation get update accordingly, and test the functionality around this issue.

**Comment by tomasnorre** [comment]
Hi @tgaertner 
Is this the documentation part you where talking about? 
https://github.com/AOEpeople/crawler/blob/typo3v9/Documentation/ExecutingTheQueue/RunningViaCommandController/Index.rst

I agree it could be more detailed, but the command that you wrote that was you success cmd, matches the documentation. 

> My successful command was now this:
` ./vendor/bin/typo3 crawler:buildQueue --page 3 --depth 3 --conf main --mode queue`

**Comment by tgaertner** [comment]
Well, I was talking about the rendered Documentation here (this is the place where integrators would search for):
 
master: https://docs.typo3.org/p/aoepeople/crawler/master/en-us/ExecutingTheQueue/RunningViaCommandController/Index.html

dev-master: https://docs.typo3.org/p/aoepeople/crawler/draft/en-us/ExecutingTheQueue/ -> the page does not exist.

But you are right - the version on github:typo3v9 is correct.

**Comment by tgaertner** [comment]
So of cause we are talking here about an (official) unreleased version - so no suprise the documentation is not in docs.typo3.org. 

So actually I was looking into the wrong docs. If you confirm that you can clode that ticket.

**Comment by tomasnorre** [comment]
No worries. The documentation isn't as good as it should be, and I should look into this anyway as the use case you mention isn't working completely.. 

So i'll keep this open and follow up on this.

**Comment by cbunhok** [comment]
Hello @tomasnorre ,
I ran the command `/vendor/bin/typo3 crawler:buildQueue --page 3 --depth 3 --conf main --mode queue`, and I got the error `Uncaught TYPO3 Exception An exception occurred in driver: No such file or directory
thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php`

What configuration steps did I miss or need to add?

**Comment by tomasnorre** [comment]
I've seen this error before, but don't recall in which context. 

Do you run in ddev or which setup do you have?

**Comment by tgaertner** [comment]
Mh could be a missing DB Configuration in CLI context. Are you able to run for example  `./vendor/bin/typo3 syslog:list ` ?? If you load DB Settings via Application Context you have to set the context also for CLI.

**Comment by cbunhok** [comment]
@tomasnorre I think Mr @tgaertner hit my point. By adding the DB setting for the CLI context, I can run that command.
Thank you so much @tgaertner .

Anyway Mr. @tgaertner , I have a question how do you set the scheduler to run that command at the back-end?

**Comment by tgaertner** [comment]
Actually I can't answer your question because I also found no way, except a custom script or custom cron-job. @tomasnorre this would be indeed helpful to have (or to know how this can be done).

Anyway it would be very helpful if you could please ask questions in the TYPO3-Slack-Channel #ext-crawler. There more people can help and the answer helps a wider audience. If you find an issue in the functionality or the documentation feel free to open a new issue here on github. Thanks a lot.

**Comment by tomasnorre** [comment]
I'm not sure which job you mean in the Scheduler?  @cbunhok

**Comment by tgaertner** [comment]
I was refering to buildQueue command

**Comment by tomasnorre** [comment]
I'll update the Documentation for this.

**Comment by cbunhok** [comment]
Yes, Mr. @tgaertner I just posted a few questions in the slack.
Thank for your response.

**Comment by tomasnorre** [comment]
I'm not sure if this can be closed @tgaertner ?
