### ISSUE TITLE
[TAKS] Update License to GPL2+

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#503]
As we want to update the license for the #TYPO3 Crawler we need accept from everyone contributing.

We want to switch to following license `GPLv2+` to be better compatible with the TYPO3 Core.
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#VersionTwoOrLater

Please give your 👍 or 👎 if you accept/reject this change.

Thanks.

Have done a mention of all listed as contributors for the typo3v9 branch or code still left from the old version. 

Thanks to everyone who has contributed so far, wouldn't be possible without you.

@srotsch 
@bmack 
@CDRO
@stucki 
@chetan-thapliyal 
@TomasVotruba 
@tstahn 
@markus-k 
@macjohnny 
@vzz3 
@tmotyl 
@tgaertner 
@tbal 
@t3easy 
@stuartmcfarlane 
@samowitsch 
@rvock 
@maximilian-walter 
@maechler 
@fl3s 
@felixsemmler 
@domin1101 
@cweiske 
@christianfutterlieb 
@chesio 
@ayacoo 
@SomeBdyElse

**Comment by bmack** [comment]
So what do you propose? It's not clear from the issue. Change from "GPL3-only" to "GPL2 or later"?

And in case somebody is wondering:
- TYPO3 Core is using "GPLv2 or later" (meaning: If you bundle TYPO3 Core with GPL2only-code it is no license violation, and if somebody else bundles TYOP3 Core with GPL3only (like current crawler) it is no license violation, however bundling core with both is violating one of the packages' license.
- In order to change a license officially, every contributor needs to consent

**Comment by tomasnorre** [comment]
Sorry.. I want to go with "GPL2 or later" License

**Comment by TomasVotruba** [comment]
Personally I'd go with MIT as it's more clear than any GPLx for open-source, but I :+1:

**Comment by bmack** [comment]
👍 for MIT or GPLv2+

**Comment by tomasnorre** [comment]
The Problem with this voting is, that I cannot see who the "7 More" is, so I would not know whom to contact if not everyone votes. 

Would a Documented with a commit from everyone be an option. e.g. 

File: Licence-update.md

```
Update from GPL3 to GPL2+, please add you name to the list if you accept

2019.12.11 - Tomas Norre Mikkelsen @tomasnorre 
```

This way it could be documented, and one could not remove the consent, be removing the thumbs up.

**Comment by cweiske** [comment]
+1 for GPLv2+

**Comment by cweiske** [comment]
```
curl -s -H "Accept: application/vnd.github.squirrel-girl-preview+json" https://api.github.com/repos/AOEpeople/crawler/issues/503/reactions|jq 'reduce .[] as $i ({}; .[$i.user.login] = $i.content)'
{
  "markus-k": "+1",
  "macjohnny": "+1",
  "christianfutterlieb": "+1",
  "cweiske": "+1",
  "TomasVotruba": "+1",
  "CDRO": "+1",
  "chesio": "+1",
  "maechler": "+1",
  "ayacoo": "+1",
  "stucki": "+1",
  "samowitsch": "+1",
  "tomasnorre": "+1",
  "tgaertner": "+1",
  "rvock": "+1",
  "t3easy": "+1",
  "maximilian-walter": "+1",
  "vzz3": "+1"
}
```

**Comment by tomasnorre** [comment]
Thanks @cweiske Didn't think about that :)

**Comment by tomasnorre** [comment]
@infabo Do you accept the License update as well.? 
For some reason I didn't have you one my first list of contributors. Sorry. 

Please 👍 or 👎  at the top post. 

Thanks.

**Comment by tomasnorre** [comment]
I'll close this issue and try to get connected with those still not accepting.
