### ISSUE TITLE
Userinformation in alternative baseurl are stripped. 

### ISSUE THREAD

**Issue by aseemann** [AOEpeople/crawler#510]
## Bug Report

**Current Behavior**
The user information in the alternative base-url are stripped on pushing urls into queue.

**Expected behavior/output**
The user information should kept in base-url if the url is pushed into the queue. 

**Environment**
- Crawler version: typo3v9 (b9b5fa1a17984d49477b67798b7570231679cb73) 
- TYPO3 version: 9.5.x
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
````
commit 23dabf64d18585460beb10c3722703d8e94286e5 (HEAD -> typo3v9)
Author: Axel Seemann <axel.seemann@netresearch.de>
Date:   Thu Jan 9 07:29:25 2020 +0100

    Add userinfo from alternativeBaseUrl to crawled url.

diff --git Classes/Controller/CrawlerController.php Classes/Controller/CrawlerController.php
index e8ea258..dbbd4eb 100644
--- Classes/Controller/CrawlerController.php
+++ Classes/Controller/CrawlerController.php
@@ -2085,6 +2085,9 @@ protected function getUrlFromPageAndQueryParameters(int $pageId, string $querySt
                 $url = $url->withHost($alternativeBaseUrl->getHost());
                 $url = $url->withScheme($alternativeBaseUrl->getScheme());
                 $url = $url->withPort($alternativeBaseUrl->getPort());
+                if ($userInfo = $alternativeBaseUrl->getUserInfo()) {
+                    $url = $url->withUserInfo($userInfo);
+                }
             }
         } else {
             // Technically this is not possible with site handling, but kept for backwards-compatibility reasons
````

**Comment by tomasnorre** [comment]
Thanks you fix looks like it works from my manual testing. 

I'll add Tests for it, and have it commited and merged.
Thanks for reporting @aseemann

**Comment by tomasnorre** [comment]
This looks fine to me and works with my manual tests. 
I'll add a todo, to create tests for this code section, not only your new suggestion.

**Comment by tomasnorre** [comment]
I've added testes for this now too #525
