### ISSUE TITLE
Crawler should ignore unresolveable mount-points

### ISSUE THREAD

**Issue by tgaertner** [AOEpeople/crawler#513]
## Bug Report

**Current Behavior**
If there is mount-point in page tree, which target was deleted, the crawler crashes with a Fatal-Error.

**Expected behavior/output**
IMO the crawler should ignore those mount-point like the fronted rendering does. Otherwise its very easy for an editor to destroy the crawling process without even noticing.

**Environment**
- Crawler version(s): dev-typo3v9
- TYPO3 version(s): 9.5.13
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
Hi @tgaertner 

Could you please paste the error message and a little more detailed on how to reproduce ?

Thanks.

**Comment by tgaertner** [comment]
Rechecking this, I think its not really related to the crawler... 

Reproduce:
- create a moint-point to a page
- delete the target page
- go to INFO module -> Site Crawler
- select your website (containing the mount-point) e.g. select root page and level infinite
-  select your config
- hit one of the buttons e.g. "Crawl URLs"

This results in a fatal error:


(1/1) #1534710048 TYPO3\CMS\Core\Exception\SiteNotFoundException
No pseudo-site found in root line of page 963

- where 963 is the UID of the mouint-point.

I don't get this error on normal using the backend or calling the frontend. It also not happen when calling the crawling process via CommandController. So I think its just the BackendModule that crashes. Could be a core bug, too.

It would be nice if you could check this - if its a general problem with the core I will create a ticket there...

**Comment by tomasnorre** [comment]
Thanks for following up. Will check this.

**Comment by tomasnorre** [comment]
Hi @tgaertner 
I cannot reproduce this problem. Does it always happen ? and do you have more information perhaps that could help me?

**Comment by tgaertner** [comment]
With current TYPO3 9.5.15 and latest crawler its gone - don't know where its "solved" but this ticket can be closed I think.
