### ISSUE TITLE
sleep time and sleep after finished are swapped

### ISSUE THREAD

**Issue by allesmeins89** [AOEpeople/crawler#515]
`$sleeptime` and `$sleepAfterFinish` are swapped in Classes/Command/CrawlerCommandController.php in version 6.7.0 in lines 223 and 224.

`$sleeptime` is calculated with `usleep(intval($sleepTime))` that's are microseconds not milliseconds as the help says. Line 203 also in Classes/Command/CrawlerCommandController.php in version 6.7.0.

**Comment by tomasnorre** [comment]
Hi @allesmeins89 

Could you please create a PR for this, then I'll be happy to test this.

**Comment by tomasnorre** [comment]
This is fixed with commit https://github.com/AOEpeople/crawler/commit/618f3d8291e8d73f621d7bfaf2c4b401bedbecbc, could you please verify @allesmeins89

**Comment by tomasnorre** [comment]
Fixed for typo3v9 with commit https://github.com/AOEpeople/crawler/commit/565ddcb73d739b162f033d9af58642b54f3785d9
