### ISSUE TITLE
[FEATURE] Support for tx_news with speaking URLs for TYPO3 9.x

### ISSUE THREAD

**Issue by tgaertner** [AOEpeople/crawler#516]
I tried to setup crawler for tx_news Records. With the current documented configuration possibilities I was not able to get this done because afaik it is only possible to add get params to the detail page call.
With that its possible to carwl URLs like
`http://dev.projectdomain.de/de/nachrichten/detail?tx_news_pi1%5Bnews%5D=2542&cHash=d717026c94c2d20e08ea62e44db7bca0`

Site configured with SiteConfiguration gives URLs like
`http://dev.projectdomain.de/de/nachrichten/detail/some-news-title`

Crawling the URL with get params results in a different cache entry then calling the nice URL, so the URL used in FE is not cached by the crawler.

I tried this config:
`tx_crawler.crawlerCfg.paramSets {
    default = [_TABLE:tx_news_domain_model_news;_PID:11;_FIELD:path_segment]
    default {
        procInstrFilter =
    }
}`
which does not work.

Maybe its a missing feature or could me missing documentation.

**Comment by tomasnorre** [comment]
Thanks, Will check it out and make sure to get either the code or documentation adjusted.

**Comment by tomasnorre** [comment]
I've been looking into this, and you're right, it's not working anymore as mentioned in the documentation.

I'll make sure this gets implemented. But it's not my first priority. But I'll take care of it.

**Comment by lsascha** [comment]
Hi. i am having some issues with the crawler extension (v9.0.1) on TYPO3 v9.5.17

I have the following configuration:
tx_crawler.crawlerCfg.paramSets {
    tx_news = &tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news; _PID:118; _WHERE: hidden = 0]
    tx_news {
        procInstrFilter = tx_indexedsearch_reindex
        pidsonly = 121
        cHash = 1
    }
    recipes = &tx_recipes_recipe[recipe]=[_TABLE:tx_recipes_domain_model_recipe; _PID:76; _WHERE: hidden = 0]
    recipes {
        procInstrFilter = tx_indexedsearch_reindex
        pidsonly = 77
        cHash = 1
    }
}

And added 3 scheduler tasks (buildQueue, processQueue and flushQueue)
In the buildQueue i set the "conf" field to default,tx_news,recipes , depth to 99 and number to 200 (but don't think that matters. Even though i am not sure how to change the "output mode" mentioned there)

Now when i run the buildQueue, and after that multiple times the processQueue, i still don't get the news or recipes entries into the search index.
If i access it by browser it gets indexed correctly, so in theory it should work when it would crawl these pages.

the "_PID" in the pageTS part is where the database entries are saved, the "pidsonly" part is where the detail pages are in the pagetree.


the recipes extension is a custom extension.
But i would guess the news and recipes extension should work pretty similar in processing the urls.

**Comment by lsascha** [comment]
got it crawling now.
First thing was not checking the checkbox `Add option` on top of the "depth" field in the scheduler task. as it then only added the root page to the queue. So

1. set depth to 99 and check the "add option" checkbox.
2. in the TS its called "pidsOnly" and not "pidsonly" like mentioned in the docs.

What i am now still missing is the crawling of regular pages. I would have guessed adding "default" to the "conf" input field in the scheduler would do that. but it seems its not.

**Comment by tomasnorre** [comment]
Thanks for the update. 
The non-speaking part is surely part of this issue, see main description. 

The regular pages, I've never done with PageTS, so would need to check up on that, how it would look like. 

I've always done that with a crawler-configuration record. 
Does it work when you do it like that?

**Comment by lsascha** [comment]
Yes. regular pages seem to be added to the queue now as well.

Only remaining problem are speaking urls for realurl.

Another thing i haven't checked yet is multi-language and if everything is crawled there too.

**Comment by tomasnorre** [comment]
This config works for news. 

```
tx_crawler.crawlerCfg.paramSets {
    tx_news = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news; _PID:118; _WHERE: hidden = 0]
    tx_news {
        procInstrFilter = tx_indexedsearch_reindex
        # pidsOnly = pageid of detail pages
        pidsOnly = 121
        cHash = 1
    }
}
```

**Comment by tomasnorre** [comment]
@tgaertner Should I interpreted this as it works for you? 
Then I'll make sure that the documentation will get updated.

**Comment by tgaertner** [comment]
Sorry for just hitting the close button - was in a hurry. We dropped the crawler from that project (for other reasons) and have atm no possibility and time to test this further. I think if it works for you its fine to add this to the docs.

**Comment by tomasnorre** [comment]
Thanks for the update. Will still need someone to confirm though.

**Comment by brotkrueml** [comment]
Maybe I am doing something wrong, but the example from above doesnt't work for me. I am using this snippet in TSconfig (the same as above, only page ids have changed):

    tx_crawler.crawlerCfg.paramSets {
        tx_news = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news; _PID:473; _WHERE: hidden = 0]
        tx_news {
            # pidsOnly = pageid of detail pages
            pidsOnly = 474
            cHash = 1
        }
    }

``473`` is the storage folder of the news, ``474`` the detail page id. Then I run the command

    crawler:buildQueue 474 tx_news

and get the answer: ``Putting 0 entries in queue``.

Another try with

    crawler:buildQueue 3 tx_news --depth 99

has the same result (3 is the start page id of the website).

**Comment by tomasnorre** [comment]
Thanks for the input. I'll look into this again.

**Comment by tomasnorre** [comment]
In the crawler-devbox setup it worked with the snippet you posted @brotkrueml (Just adjusted the ids) 
![Screenshot from 2020-08-05 17:47:01](https://user-images.githubusercontent.com/1212481/89434378-c4a2b680-d743-11ea-9d95-58fca2cd2c88.png)

**Comment by tomasnorre** [comment]
From cli it also works, the second one does not as it doesn't know about the tx_news configuration on the start page.
![Screenshot from 2020-08-05 17:50:08](https://user-images.githubusercontent.com/1212481/89434775-3ed33b00-d744-11ea-9b0f-95ca25ac156a.png)

**Comment by brotkrueml** [comment]
Argh, found the problem: The detail page was on the page veto list. Perhaps it would be nice to output the result of CrawlerController->getPageTreeAndUrls() in the buildQueue command (strip HTML first)?

**Comment by tomasnorre** [comment]
Glad to hear that it works. I'll make sure that the documentation gets update with the tt_news example. 

Can you please create a new issue with the suggestion you made, then I'll look into this.

**Comment by brotkrueml** [comment]
See #615

**Comment by tomasnorre** [comment]
Resolved with commit: https://github.com/AOEpeople/crawler/commit/4532464cbb3282946742c582509cfd2512809261
