### ISSUE TITLE
Option "Force HTTPS for all pages" not respected

### ISSUE THREAD

**Issue by t3easy** [AOEpeople/crawler#517]
## Bug Report

**Current Behavior**
Despite that the option "Force HTTPS for all pages" is set in the config, the urls added to the queue are all http.

**Expected behavior/output**
All URLs should have https urls.

**Environment**
- Crawler version(s): 6.7.0
- TYPO3 version(s): 8.7.30
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

**Additional context**
We are using `indexed_search`.

**Comment by tomasnorre** [comment]
Thanks for the report, will check this.

**Comment by t3easy** [comment]
I used the Database config and "Get Baseurl from Domainrecord" option.
Switched to "Base url" and added Url with https as a workaround.

**Comment by tomasnorre** [comment]
Thanks for the additional info.. Can be important for the debugging.

**Comment by tomasnorre** [comment]
Hi @t3easy 

I cannot reproduce this, can you provide me with more information. 

When setting `Force HTTPS for all pages` all my crawler entries is with `https://` when setting it to `Force HTTP for all pages` there are all with `http://` so to me it looks like it works.

**Comment by tbal** [comment]
Had the same problem. Luckily this is fixed in current master thanks to PR #494 
Issue can be closed.

P.S.: Would love to see a new TER release 6.7.1 of the current master :)

**Comment by tomasnorre** [comment]
Thanks for confirming. 
Will see when I get to creating a new release.

**Comment by tomasnorre** [comment]
@tbal a 6.7.1 version is release in TER and Packagist.

**Comment by tbal** [comment]
Many thanks @tomasnorre for your quick response and the new release!
