### ISSUE TITLE
Is it ok to delete Wiki page?

### ISSUE THREAD

**Issue by sypets** [AOEpeople/crawler#520]
There is still a Wiki page for the crawler extension: https://wiki.typo3.org/Crawler

The crawler documentation is https://docs.typo3.org/p/aoepeople/crawler/master/en-us/

Generally, we try to delete Wiki pages, if the information has moved elsewhere, the page is outdated or no longer relevant. In this case, the information is elsewhere. However I would hate for information to get removed that is still relevant. Can you have a look?

Duplicate and outdated documentation is an ongoing problem, which is being addressed. I hope this will make it easier to find documentation and easier to use TYPO3 in the future ...

Thanks. 

(With the deletion of the Wiki page, we set up a redirect to the new location, which would be https://docs.typo3.org/p/aoepeople/crawler/master/en-us/)

**Comment by tomasnorre** [comment]
Hi @sypets,

Ja that can be deleted, and redirected.
