### ISSUE TITLE
[BUG] Extensions throws "Dependency Order" Exception with TYPO3 v10.2.2

### ISSUE THREAD

**Issue by koernchen02** [AOEpeople/crawler#523]
## Bug Report

**Current Behavior**
After activating the extension the backend is no longer accessible and throws the following error:

```
#1381960494 UnexpectedValueException

Your dependencies have cycles. That will not work out. Cycles found: aoe/crawler/initialization->typo3/cms-frontend/authentication, aoe/crawler/initialization->typo3/cms-frontend/tsfe, typo3/cms-core/normalized-params-attribute->typo3/cms-frontend/timetracker, typo3/cms-frontend/authentication->typo3/cms-frontend/backend-user-authentication, typo3/cms-frontend/authentication->typo3/cms-frontend/maintenance-mode, typo3/cms-frontend/authentication->typo3/cms-frontend/site, typo3/cms-frontend/backend-user-authentication->typo3/cms-frontend/site, typo3/cms-frontend/base-redirect-resolver->typo3/cms-frontend/site-resolver, typo3/cms-frontend/eid->typo3/cms-core/normalized-params-attribute, typo3/cms-frontend/maintenance-mode->typo3/cms-core/normalized-params-attribute, typo3/cms-frontend/maintenance-mode->typo3/cms-frontend/eid, typo3/cms-frontend/page-argument-validator->typo3/cms-frontend/page-resolver, typo3/cms-frontend/page-resolver->aoe/crawler/initialization, typo3/cms-frontend/page-resolver->typo3/cms-frontend/authentication, typo3/cms-frontend/page-resolver->typo3/cms-frontend/backend-user-authentication, typo3/cms-frontend/page-resolver->typo3/cms-frontend/site, typo3/cms-frontend/page-resolver->typo3/cms-frontend/static-route-resolver, typo3/cms-frontend/site->typo3/cms-core/normalized-params-attribute, typo3/cms-frontend/static-route-resolver->typo3/cms-frontend/base-redirect-resolver, typo3/cms-frontend/tsfe->typo3/cms-frontend/authentication, typo3/cms-frontend/tsfe->typo3/cms-frontend/eid, typo3/cms-frontend/tsfe->typo3/cms-frontend/page-argument-validator, typo3/cms-frontend/tsfe->typo3/cms-frontend/page-resolver
```

**Expected behavior/output**
I'm expecting the backend to be accessible after the extension activation.

**Environment**
- Crawler version(s): [9.0.0-dev]
- TYPO3 version(s): [10.2.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Additional context**
I do want to use the extension with `indexed_search` and since the **ext_emconf.php** states a dependency on `'typo3' => '9.5.9-10.4.99',` I was trying to configure the auto-index setup since I'm in the middle of an TYPO3 Site upgrade from 8.7.x to 10 LTS

**Comment by tomasnorre** [comment]
Thanks for letting me know. Will look into this.

**Comment by tomasnorre** [comment]
I can reproduce this, I don't know why this is happening, but will of course try to figure it out. 

We have changed the way that the crawler can be used in the Core, and I think it's related to this update.

I think it's regarding the Middleware and how they are registered. 
Will need to debug this to be able to give you a better answer or even a solution to the Problem, but it's for sure a bug in the Crawler in some way.

**Comment by koernchen02** [comment]
I commented out the `after 'typo3/cms-frontend/tsfe'` line in the RequestMiddlewares config to have a look at where the CrawlerInitialization was then placed at (and to have access to the BE again):

![screenshot-vw-it-rich-pad_32768-2020 03 05-15_45_16](https://user-images.githubusercontent.com/312900/75992809-d237e400-5ef8-11ea-9c7f-d373a99b09e5.png)
Looking at that ordering, it seems logical that the middleware cant be placed **after** `tsfe` and **before** the `page-resolver` since the page-resolver middleware is invoked before the tsfe middleware. I would create a pull request, but I assume you are much faster fixing the ordering since I assume you know where it should be placed and I would have to keep on tinkering...

Would be great if you could give me a feedback considering this upfront, so I can test around before you merge a fix!
Best regards and thanks in advance!

**Comment by koernchen02** [comment]
I forgot to say that I therefore assume:
`Your dependencies have cycles.` seems to mean your config results in your middleware beeing invoked multiple times... which I would say is an interesting wording ;)

**Comment by tomasnorre** [comment]
Thanks, it have been located to the Middleware as you mentioning and load order, just need to figure out what the correct one is. :)

**Comment by koernchen02** [comment]
OK Cool! I'm currently trying to get everything up and running with the middleware being placed simply **after** tsfe, but this seems to be contradicting the commit https://github.com/AOEpeople/crawler/commit/176da363530f419ef74e856c461720e7a049f215 ?!

**Comment by tomasnorre** [comment]
It's direct related to that commit, talked to @ichhabrecht and she will have a look at it and give me some advice on the load order, it's not my area of expertise with the Middleware, still quite new to me.

**Comment by tomasnorre** [comment]
@koernchen02 could you please test and verify the PR from @ichHabRecht  #527  

Then I'll make sure it gets merged.

**Comment by tomasnorre** [comment]
Should be fixed with commit https://github.com/AOEpeople/crawler/commit/b5443c33c635958635009c4d36ba30f5d97bebd0

Thank @IchHabRecht

**Comment by koernchen02** [comment]
Thanks a lot for the fix! It's working as expected! I'm sorry that I didn't get back to you!
I was very busy the last weeks implementing all sorts of online collaboration tools for my employer and just got back to working on their site-upgrade!

**Comment by tomasnorre** [comment]
Don't stress. I'm doing this in my spare time too. 

Thanks for the feedback.
