### ISSUE TITLE
Items per Page -> htmlspecialchars() expects parameter 1

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#528]
Installing aoepeople/crawler (dev-typo3v9 995fa4a): Cloning 995fa4af61
on TYPO3v9.5.14

Crawler-Log -> Checkbox "Items per page" -> change selection

htmlspecialchars() expects parameter 1 to be string, int given

**Comment by tomasnorre** [comment]
Thanks for you report.

Could you perhaps make a PR?
Thanks

**Comment by tomasnorre** [comment]
Your "steps to reproduce" showed me that bad UX that the crawler module is having.. 

It isn't the "Items Per Page" that makes it break, but the 

![Screenshot 2020-04-06 at 19 55 41](https://user-images.githubusercontent.com/1212481/78589772-07f62280-7841-11ea-8bc8-5b1cf3034d3c.png)
I'll make a new issue for that.

**Comment by tomasnorre** [comment]
This is still an issue, reopened.
