### ISSUE TITLE
getUrlsForPageId() must be of the type int, null given

### ISSUE THREAD

**Issue by varioous** [AOEpeople/crawler#529]
**Environment**
- Crawler version(s): 9.0.0-dev
- TYPO3 version(s): 9.5.14
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

/var/www/html/public/typo3$ sysext/core/bin/typo3 crawler:buildQueue

Uncaught TYPO3 Exception Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageId() must be of the type int, null given, called in /var/www/html/public/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php on line 401
thrown in file /var/www/html/public/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php
in line 574

Pagetree:
![image](https://user-images.githubusercontent.com/7273899/77571376-8fe93d80-6ecd-11ea-9274-bfeb5862f76a.png)

Crawler Config:
![image](https://user-images.githubusercontent.com/7273899/77571495-c2933600-6ecd-11ea-865e-5988c1c95cb8.png)

![image](https://user-images.githubusercontent.com/7273899/77571521-ccb53480-6ecd-11ea-97b1-c0615121c574.png)

**Comment by tomasnorre** [comment]
The command isn't called with the right parameters.
https://github.com/AOEpeople/crawler/blob/typo3v9/Documentation/ExecutingTheQueue/RunningViaCommandController/Index.rst#create-queue

This should of course trigger an error on cli level, instead of an php-error.

Will look into this.

**Comment by tomasnorre** [comment]
@varioous Can you please test, i've pushed a fix for this. 

Please pay attention to the updated documentation as it's switched from options to arguments.
https://github.com/AOEpeople/crawler/commit/e0ae3eb2293755c238fe8c00ef208e1258ea9f2c#diff-cbac2bee565b1f754fe3285bc52cd9e9R24

**Comment by varioous** [comment]
Hi @tomasnorre,

thanks. No error message on CLI level is displayed.

Issue can be closed.

Thanks and best regards,
Harald
