### ISSUE TITLE
module:info htmlspecialchars() NULL given - for file entries

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#545]
## Bug Report
module:info -> SiteCrawler -> Crawler-Log

**Current Behavior**
Core: Exception handler (WEB): Uncaught TYPO3 Exception: htmlspecialchars() expects parameter 1 to be string, null given | TypeError thrown in file /var/www/html/../current/webroot/web/typo3conf/ext/crawler/Classes/Backend/BackendModule.php in line 659. Requested URL: http:/mydomain.tld/typo3/index.php?route=%%2Fweb%%2Finfo%%2F&token=--AnonymizedToken--&id=1 

**Expected behavior/output**
the $parameter['url'] is not set for files.

**Environment**
- Crawler version(s): [e.g. 9.0.0]
- TYPO3 version(s): [e.g. 9.5.15]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Comment by tomasnorre** [comment]
Do you always get this error when going to the Crawler Log and did you do something before the error happend?

**Comment by TrueType** [comment]
As I mentioned the problem occurs for files only. As you process pages, which contain links to files, for each file an additional entry is put into the queue. At the point in code mentioned serialized data is processed for every entry and for files there is not "url" index given. There is only a path on the server.
To reproduce: create a page with file reference. Get the page in the queue. Index it by processing the queue. It should create an entry in the queue for the file found while indexing the page. I guess that is enough to crash the Crawler Log already.

**Comment by tomasnorre** [comment]
Thanks for the update, I will check.
Edited the text to make it a little easier to read.

**Comment by tomasnorre** [comment]
Hi @TrueType,

I cannot reproduce this. Do I do anything different than want to meant? 
Please see video linked.
https://www.dropbox.com/s/k8w9anpvl3cbzrd/issue-545.mp4?dl=0

**Comment by TrueType** [comment]
Hi Tomas,

sry, for coming back to you that late.

I checked your video. Makes me wonder why your processing does to work on the pdf file? As I come back from starting a process I see two entries. One is for the page, which is on status OK, one is newly created - not yet processed - and is for the file found while processing the page. 

So your system does not yet process files. 

You may check for the settings on EXT:indexed_search:

`basic.useCrawlerForExternalFiles = 1`

And the binary to handle pdf files

`/usr/bin/pdftotext`

**Comment by tomasnorre** [comment]
Thanks for the follow up I will check, I'm unfortunately not really experienced with indexed_search so all input is helpful.

**Comment by TrueType** [comment]
I will close this issue .. the only thing I can do here ... the issue was fixed here - 0f3fa7a012e5ed60726d72ae3aadf24ea1e22624

**Comment by tomasnorre** [comment]
Glad that it has been solved. 
I'll try to fix the `@noRector` problem asap, but don't have time tonight. 

I'll have a new release done (9.0.1) beginning of next week.
