### ISSUE TITLE
Links on refresh icon/queue id do not work in TYPO3 7.6

### ISSUE THREAD

**Issue by christianfutterlieb** [AOEpeople/crawler#56]
The links on the refresh icon/queue id in the crawler log list do not contain all needed parameters:
`index.php?id=1&qid_read=1&setID=0`
should be:
`/typo3/index.php?M=web_info&moduleToken={token}&qid_read=1&setID=0&id=1`

I hope I'm in the right place here on github, I'll sumbit a pull request with a fix. If you prefer, I can submit the patch to gerrit, just let me know.

**Comment by tomasnorre** [comment]
This is the right place..

Thanks for you contribution.
