### ISSUE TITLE
[BUG] @noRector was never imported

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#566]
just quick feedback on f04fad5

[CRITICAL] request="5d9311f3c8c65" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: [Semantical Error] The annotation "@noRector" in property AOE\Crawler\Service\ProcessService::$deprecatedPublicProperties was never imported. Did you maybe forget to add a "use" statement for this annotation? | Doctrine\Common\Annotations\AnnotationException thrown in file /var/www/html//web/current/webroot/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php in line 54.

**Comment by tomasnorre** [comment]
I'm fighting this issue right now my self, but don't see it failing in master, only in a branch. 
But thanks for letting me know. I'll have this fixed asap. 

When do you see this error? I see it by executing the tests on CLI.

**Comment by TrueType** [comment]
I cannot open the backend module INFO -> Site Crawler

**Comment by tomasnorre** [comment]
ok. Strange, you are on dev-master I suppose?

I'm currently testing with dev-master and I have no problem with the backend module currently. 

But I can confirm the problem you are referring to when running the test on cli, so there is for sure a problem.

**Comment by tomasnorre** [comment]
Fixed with commit: https://github.com/AOEpeople/crawler/commit/10ea05aec1e3eec3c4ccc084250bb9cae5f1aeac
