### ISSUE TITLE
[BUG] Return value of Process::getTimeForFirstItem() 

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#568]
Uncaught TYPO3 Exception: Return value of AOE\Crawler\Domain\Model\Process::getTimeForFirstItem() must be of the type integer, null returned | TypeError thrown in file /var/www/html//web/current/webroot/web/typo3conf/ext/crawler/Classes/Domain/Model/Process.php in line 210.

To reproduce: Backend-Module start process. I guess if the process did not finish and ones calls the log dialog this happens. Recall the dialog may not show the error any more.

**Comment by tomasnorre** [comment]
All write a test covering this and fix respectively.

**Comment by tomasnorre** [comment]
@TrueType Can you please review and verify this fix ?

**Comment by TrueType** [comment]
Sry, don't have time for it. I am not sure, if I could reproduce it anyway. Got that only once. If you cannot identify the possible situation it may occurs /reproduce it I can't help.

**Comment by tomasnorre** [comment]
I could reproduce it with mocking tests as you described when a process didn't exist.
Thanks for fast feedback anyway, I'll merge it when I have reviewed it ones more myself.
