### ISSUE TITLE
dealing with proxy settings

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#575]
Setup has proxy settigs by .env file:

```
TYPO3_CONF_VARS__HTTP__proxy__http=http://10.xx:8080
TYPO3_CONF_VARS__HTTP__proxy__https=http://10.xx:8080
TYPO3_CONF_VARS__HTTP__proxy__no__0=.mydomain.tld
```
Running from scheduler or backend module everything is fine. Running on the CLI is does not work.

So the scheduler commands pretty directly go into the same code the CLI does. Yeah, course. But then I don't get it why it is falling apart?

Mezzo: There is a strategy selection in QueueExecutor. I guess all goes in Guzzle, though. I took a look into the alternative SubProcess strategy. And the code gets really ugly here. I suppose you just drop the setting 'makeDirectRequests' and remove all related code thoroughly. haha.

Back to the Guzzle: In GuzzleExecutionStrategy a Response object is created and requested with some little options. The $httpOptions used in the RequestFactory are overridden. As I see it. 

I suggest the handling of the httpOptions is not quite ok, here. But then, I still don't understand why starting the command by scheduler does work?

**Comment by TrueType** [comment]
Ah, ok. I entered the missing proxy configuration by hand and mistreated the 'headers' options(dropped them). But they are important... 
`'X-T3Crawler' => $crawlerId,`
is used to activate some FrontendUserAuthenticator middleware. Which itself handles the indexing.

**Comment by tomasnorre** [comment]
I'm not sure I get what your problem is here. 

The DirectReqeust is important, as some crawling happens behind load balancers etc. so they cannot do GuzzleRequest. The directRequests are also faster, so for larger sites I can be helpful. 

Can you please try to explain to me which use case you have and why this/what isn't working?

**Comment by TrueType** [comment]
Hey. Please look into RequestFactory. See $httpOptions taken from TYPO3_CONF_VARS. They handle proxy settings and possibly other http settings. They don't make it into the request created for the crawler process.

**Comment by tomasnorre** [comment]
Thanks will check.

**Comment by TrueType** [comment]
Yes. This is core. Once you get the response object I do not see how you retrieve the options to array_merge them. I guess you have to build up the httpoption from confvars yourself and then array_merge.

**Comment by tomasnorre** [comment]
Ok. Will check this out. Thanks for point this out.

**Comment by tomasnorre** [comment]
Would need to find a setup where I can actually test this.

**Comment by tomasnorre** [comment]
Looks like the issue is within this function. 
https://github.com/AOEpeople/crawler/blob/master/Classes/CrawlStrategy/SubProcessExecutionStrategy.php#L101

**Comment by TrueType** [comment]
I guess what you say is: the subprocess strategy and code has the same problem. Or possibly a similar problem.

**Comment by tomasnorre** [comment]
I stumbled upon this function, and this for sure doesn't respect the proxy settings. Not sure if that the only problem, but that's at least also a problem. 

I would need to add more tests, otherwise, it gets difficult to prove.

**Comment by TrueType** [comment]
Wondering what hell of a test setup this is to test for proxy? One easier test may be to set an invalid proxy, which then would not allow a valid request and then to set 'no-proxy' and get it running again?

**Comment by tomasnorre** [comment]
I've never worked with proxies before in the context of the crawler, so need to find a way to test this. 
I'll for sure try to do automated tests and not only manual tests. In my opinion manual tests only are good for confirming an issue and automated for fixing and making sure it's not happening again.

**Comment by TrueType** [comment]
Maybe find some travis configuration for dealing with proxy and going backwards from there. And, of course, an automated test is a mile more worth than testing manually. ;)

**Comment by bmack** [comment]
@TrueType OK so this basically means: Guzzle does not work in your proxy environment because the TYPO3_CONF_VARS settings are not applied to the client created by the RequestFactory?

**Comment by TrueType** [comment]
Oh well. Looks like I messed up. Checking the guzzle client, it is obvious the default options (TYPO3_CONF_VARS) are array_merged with $options passed with a request() call. Very probably I was confused with the response while crawling. For the correct crawling the request only returns some statistics. And I took the full HTML page for a successful crawling request. What it is not.

Closing this.
