### ISSUE TITLE
[BUG]  running crawler causes typeerror htmlspecialchars() expects parameter 1 to be string, integer given

### ISSUE THREAD

**Issue by Gohil-Aayushi** [AOEpeople/crawler#576]
## Bug Report

**Current Behavior**
after the crawler had been successfully run, when selecting the root page record with the info module, there is the error shown.
when selecting another page, it is not.

**Environment**
- Crawler version(s): [9.0.1]
- TYPO3 version(s): [9.5.17]

**Comment by tomasnorre** [comment]
Thanks for reporting @Gohil-Aayushi,
Could you perhaps paste a little from the stacktrace, so that I can easier see where this is happening?

**Comment by Gohil-Aayushi** [comment]
Please check the attached file.
[TYPO3 Exception.pdf](https://github.com/AOEpeople/crawler/files/4644057/TYPO3.Exception.pdf)

**Comment by tomasnorre** [comment]
Does a PDF file exists on the page that gives you problems? 
See issue #545, sounds a little similar, and not completely solved.

**Comment by Gohil-Aayushi** [comment]
This error occurs when we crawl URL on the root page when we press continue & show log button but on subpages, crawler works properly

**Comment by tomasnorre** [comment]
I got that from your first description, but do the Root page contain PDF or other files? that are linked?

**Comment by Gohil-Aayushi** [comment]
yes, root page contains files and that are linked.

**Comment by daeff** [comment]
Hello,
I run into the same error.
TYPO3 9.5.17
crawler 9.0.1

**Comment by tomasnorre** [comment]
@Gohil-Aayushi @daeff which Info Module are you at? If the crawler as I expect, which of the 3 crawler options then. 

Start Crawling
Crawler Log
Crawling Processes

**Comment by tomasnorre** [comment]
Can you please check what the value of the $parameters['url'] is in your setup? 
In the crawler devbox it's `https://crawler-typo3v9.ddev.site/`  

The screenshot is from the BackendModule.php

![Screenshot from 2020-05-20 21:01:39](https://user-images.githubusercontent.com/1212481/82486551-556edc00-9add-11ea-9691-c5191eda2878.png)

**Comment by tomasnorre** [comment]
We could add a (string) cast before the two inputs, but I would like to understand what the issue is instead of just "fixing" without understanding.

**Comment by Gohil-Aayushi** [comment]
Here I got page uid in the URL field of one of the pages.

**Comment by tomasnorre** [comment]
so e.g. a `20` and nothing else ?

**Comment by Gohil-Aayushi** [comment]
yes

**Comment by tomasnorre** [comment]
Could you please share the following:

1. Crawler Settings
2. Crawler Configuration
3. Site Configuration. 

This would help me to debug this further. Sounds to me like a misconfiguration, but not sure. 
If this is the case, I want to make sure that users get informed in such cases.

**Comment by xerc** [comment]
https://github.com/AOEpeople/crawler/blob/744c705d2af46271eb5dac2a932b0138706515cf/Classes/Backend/BackendModule.php#L633
will be executed twice ..
```
print_r($parameters);
```
> Array ( [url] => https://[..] [procInstructions] => Array ( [0] => tx_indexedsearch_reindex ) [procInstrParams] => Array ( ) )

> Array ( [indexConfigUid] => 1 [url] => 619 [procInstructions] => Array ( [0] => [Index Cfg UID#1] ) [depth] => 2 [_CALLBACKOBJ] => TYPO3\CMS\IndexedSearch\Hook\CrawlerHook )

**Comment by tomasnorre** [comment]
Thanks for the information, looks like I have missed something in my debugging.

**Comment by xerc** [comment]
btw/ might be related
``php vendor/bin/typo3cms crawler:processQueue``
> TypeError: Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageRow() must be of the type array, null given, called in typo3/sysext/indexed_search/Classes/Hook/CrawlerHook.php on line 438

**Comment by tomasnorre** [comment]
I've added the 3rd party ext label, to make it visible that it's related not necessarily caused by indedex_search

**Comment by tomasnorre** [comment]
Have any of you tested if this also is a problem with version 9.0.0 of the crawler? Or if something broke between the two releases?

**Comment by xerc** [comment]
not me; straight to 9.0.1

**Comment by tomasnorre** [comment]
Could you please test it with 9.0.0 for me as well?

**Comment by tomasnorre** [comment]
This is how my looks like

```php
array (
  'document' => '/var/www/html/public/fileadmin/introduction/images/streets/kimon-maritz-193428.jpg',
  'alturl' => '/fileadmin/introduction/images/streets/kimon-maritz-193428.jpg',
  'conf' => 
  array (
    'id' => 36,
    'type' => 0,
    'sys_language_uid' => 0,
    'MP' => '',
    'gr_list' => '0,-1',
    'cHash' => NULL,
    'cHash_array' => 
    array (
    ),
    'staticPageArguments' => 
    array (
    ),
    'crdate' => 1557072507,
    'page_cache_reg1' => 0,
    'rootline_uids' => 
    array (
      0 => 1,
      1 => 6,
      2 => 32,
      3 => 36,
    ),
    'indexedDocTitle' => 'File downloads',
    'metaCharset' => 'utf-8',
    'mtime' => 1557072507,
    'index_externals' => '1',
    'index_descrLgd' => NULL,
    'index_metatags' => '1',
    'recordUid' => 0,
    'freeIndexUid' => 0,
    'freeIndexSetId' => 0,
  ),
  '_CALLBACKOBJ' => 'TYPO3\\CMS\\IndexedSearch\\Hook\\CrawlerFilesHook',
)

Cannot get it to have `$parameters['url']` nor `$parameters['altulr']` to be integer. 
```

**Comment by xerc** [comment]
``print_r($rowData);`` @ 9.0.0
> Array ( [scheduled] => 22-05-20 16:22 [exec_time] => 22-05-20 16:24 [result_status] => - )

**Comment by Gohil-Aayushi** [comment]
I upgraded the crawler's latest version but my issue is not resolved.
Please check the attached file of the configuration.
[Crawler Extension Configuration.pdf](https://github.com/AOEpeople/crawler/files/4680521/Crawler.Extension.Configuration.pdf)

**Comment by tomasnorre** [comment]
I didn't expect it to be resolved. Will check your configuration thanks for sharing.

**Comment by tomasnorre** [comment]
@Gohil-Aayushi I just read through you Configuration.pdf, I didn't find the problem directly, but noticed that you have your 

BuildQueue scheduler called with parameter mode: exec, this means that you processQueue job is not needed as the queue will always be empty if you are executing them at ones. 

The only thing that will land in the queue then is external files like jpgs, which only needs crawling for the indexed_search.

I would recommend you to set the mode to queue. But this is all not related to the problem here. Just an advice.

**Comment by Gohil-Aayushi** [comment]
Yes, I set the mode to queue. But the bug is not fixed .

**Comment by tomasnorre** [comment]
As mentioned I didn't expect that just noticed it by reading through them.

**Comment by tomasnorre** [comment]
Can you confirm that the patch from works like expected? I'm still not sure how I feel about the casting of a int as string, but I could be a work around for now. 

```patch
Index: Classes/Backend/BackendModule.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Classes/Backend/BackendModule.php	(revision e324a3aaa0f21acb557ac04c81d657a23d937bb9)
+++ Classes/Backend/BackendModule.php	(date 1590994778551)
@@ -630,7 +630,7 @@
                     $rowData['exec_time'] = $vv['exec_time'] ? BackendUtility::datetime($vv['exec_time']) : '-';
                 }
                 $rowData['result_status'] = GeneralUtility::fixed_lgd_cs($resStatus, 50);
-                $url = htmlspecialchars($parameters['url'] ?? $parameters['alturl']);
+                $url = htmlspecialchars((string) ($parameters['url'] ?? $parameters['alturl']));
                 $rowData['url'] = '<a href="' . $url . '" target="_newWIndow">' . $url . '</a>';
                 $rowData['feUserGroupList'] = $parameters['feUserGroupList'] ?: '';
                 $rowData['procInstructions'] = is_array($parameters['procInstructions']) ? implode('; ', $parameters['procInstructions']) : '';
```

**Comment by linawolf** [comment]
@tomasnorre Once the faulty values landet into the database each display of them causes the here called error. And this causes that the Backend Module cannot be opened anymore. 
Casting the integer that made its way into the json in the database to string before displaying it through htmlspecialchars will merely display the faulty value in the Backend Module now instead of displaying a php error and hindering the backend Module.

As of why the integers made their way into the database. I truncated the tables tx_crawler_queue and tx_crawler_process and tried to reproduce what happened here. However the faulty json did not reappear.

I recently updated from TYPO3 8 and older versions of the crawler. It might be that the faulty urls stem from older crawler versions? It might be a good idea to truncate the said tables when updating a major version.

**Comment by tomasnorre** [comment]
Truncating the Crawler Queue on updates is always a good idea. 

I haven't been able to reproduce this myself yet, so cannot verify the patch you submitted, but from a code review perspective, I can.

**Comment by xerc** [comment]
fyi/ the wrong data is generated when filling the DB @ SET[crawlaction]=start
the error at `htmlspecialchars` is caused by loading these false information

**Comment by tomasnorre** [comment]
Thanks for the information, can you perhaps link to the code you are referring to?

**Comment by tomasnorre** [comment]
Can someone please list the concrete steps to reproduce this? I haven't managed to make it fail yet in the crawler devbox.

**Comment by schliesser** [comment]
I get the same error in a multisite instance with TYPO3 9.5.21 & crawler 9.1.0 on the root pages. This is since I created also `Indexing Configuration` with PageTree Mode. I have also `Crawler Configuration` set up for each root page.

**Comment by tomasnorre** [comment]
Can you please add steps to reproduce @schliesser ?

**Comment by schliesser** [comment]
Hey, sorry for late response. Had to finish a go-live ;-)

Tested in [TYPO3 cms 9.5 branch](https://github.com/TYPO3/TYPO3.CMS/tree/9.5) with introduction package and crawler 9.1.0:

1. List: Create Crawler configuration on root page
![Bildschirmfoto 2020-09-22 um 11 38 37](https://user-images.githubusercontent.com/11655823/93867185-f7d7df80-fcc8-11ea-8396-3f2b8f58b6c0.png)

2. Info > Site crawler: queue root page & process the queue

The log is shown correctly:
![Bildschirmfoto 2020-09-22 um 11 39 45](https://user-images.githubusercontent.com/11655823/93867492-6cab1980-fcc9-11ea-9bcf-dce91218a072.png)

3. List: Create Indexing Configuration on root page
![Bildschirmfoto 2020-09-22 um 11 41 07](https://user-images.githubusercontent.com/11655823/93867560-8187ad00-fcc9-11ea-8a90-a467fcef6964.png)

4. Info > Site crawler: The unprocessed item of the indexed configuration is shown in the log as pending

![Bildschirmfoto 2020-09-22 um 11 41 33](https://user-images.githubusercontent.com/11655823/93867652-a2e89900-fcc9-11ea-8e96-5e55cf7cf205.png)

5. Info > Site crawler: Process the queue and switch back to log:

```
(1/1) TypeError
htmlspecialchars() expects parameter 1 to be string, integer given
```

If I clear the table `tx_crawler_queue` the error is gone. Here you find a small dump with the false record:
[tx_crawler_queue.sql.zip](https://github.com/AOEpeople/crawler/files/5260496/tx_crawler_queue.sql.zip)

**Comment by tomasnorre** [comment]
I can reproduce this locally. And the problem is that with the "indexing configuration" an additional information is added to the params in the database in the beginning of the params 

```
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------+
| qid | parameters                                                                                                                                    |
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------+
| 109 | {"url":"https:\/\/crawler-devbox.ddev.site\/","procInstructions":["tx_indexedsearch_reindex"],"procInstrParams":[]}                           |
| 110 | {"url":"https:\/\/crawler-devbox.ddev.site\/","procInstructions":["tx_indexedsearch_reindex"],"procInstrParams":[]}                           |
| 111 | {"indexConfigUid":1,"procInstructions":["[Index Cfg UID#1]"],"url":1,"depth":0,"_CALLBACKOBJ":"TYPO3\\CMS\\IndexedSearch\\Hook\\CrawlerHook"} |
| 112 | {"url":"https:\/\/crawler-devbox.ddev.site\/","procInstructions":["tx_indexedsearch_reindex"],"procInstrParams":[]}                           |
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------+

``` 

Will need to check why this is added though, as is doesn't look like a valid record. 

It's does not happen in TYPO3 10.4 by the way. But you never claimed that ;) Just wanted to let you know.

**Comment by tomasnorre** [comment]
Strange I could reproduce it the first time, but not again.. :(

**Comment by xerc** [comment]
yea.. this is why most of us could not generate this extended report afterwards // thx @schliesser

**Comment by tomasnorre** [comment]
I found the problem, but not the solution yet. 

https://github.com/AOEpeople/crawler/blob/master/Classes/Hooks/IndexedSearchCrawlerHook.php#L439

**Comment by tomasnorre** [comment]
Still relevant

**Comment by freshworkx** [comment]
I can confirm this behavior (bug?) for TYPO3 10.4.15 and Crawler 9.2.4.
The faulty database entry in field 'parameters' comes up, if 'indexed_search configuration data set' is placed on a 'normal' page that should be crawled. 
My simplest solution is to move this 'index_search configuration data set' from the (root) page into a separate sys-folder.

**Comment by tomasnorre** [comment]
Hi @freshworkx 
Thanks for confirming, not sure if I understand what you mean though as solution?

**Comment by freshworkx** [comment]
In my case the configuration of indexed_search and crawler was placed on the root page of pagetree. This page is crawled itself. I just moved the records to a sys-folder, a picture is worth a thousand words:

<img width="626" alt="crawler" src="https://user-images.githubusercontent.com/12698815/114868681-7aa3c180-9df6-11eb-8ad5-1e8b59a9cea0.png">

The problem seems to be to crawl a page that has an indexed_search config placed on.

**Comment by tomasnorre** [comment]
Thanks, Will check out if I can find a way to prevent this error from happening, or at least give a hint when people are doing so.
A report generated, would be a fairly easy fix, just don't know if people read the TYPO3 Reports.

It could perhaps be something for the Crawler Widget as warning? 
https://github.com/tomasnorre/typo3-crawler-widget

But that would require people to install that too.

**Comment by freshworkx** [comment]
In my opinion the best way is 'spread the word', given hints in documentation and widget (maybe also in reports). I could also think about to give a (colored) warning in tree of protocol view (like the 404 error).

**Comment by tomasnorre** [comment]
Thanks for the feedback, will consider what I can do. 
Your indexed_search hasn't suffered from moving it's config to a different location?

**Comment by freshworkx** [comment]
No, of course not. For me the important thing is not to crawl those pages with an index_config on it because it breaks the crawling process!

**Comment by tomasnorre** [comment]
I see. I'll see what I can figure out. 
Thanks for your feedback.

**Comment by tomasnorre** [comment]
I have added documentation on this, in the troubleshooting section. As this section of the TYPO3 Core is already removed in TYPO3 11. I'll not provide a fix for this, but a workaround. 

Please see documentation. 
https://github.com/AOEpeople/crawler/blob/25a0e5f3c0b7c9e63fd6d617acff14f0db0de1da/Documentation/Troubleshooting/Index.rst#id19
