### ISSUE TITLE
Command "crawler:crawler:flushqueue" registered by "crawler" is already in use

### ISSUE THREAD

**Issue by echavaillaz** [AOEpeople/crawler#577]
Hi,

I use crawler and typo3_console on the same instance of TYPO3 9 and when I make a `composer update`, I got this error:

```
[TYPO3\CMS\Core\Console\CommandNameAlreadyInUseException]
Command "crawler:crawler:flushqueue" registered by "crawler" is already in use
```

Any idea?
Thanks a lot.

**Comment by tomasnorre** [comment]
Sorry I don't have see this problem before, the Crawler Devbox is also having both the typo3 and typo3cms binary. 

https://github.com/AOEpeople/crawler/blob/master/.devbox/composer.json

And I never seen this error before. 

which version of the TYPO3 Console are you using?

**Comment by echavaillaz** [comment]
It is strange indeed. I use `5.8.5`.
I will check mor deep with this issue.
Thanks

**Comment by tomasnorre** [comment]
That's the same version as the Crawler Devbox
`helhum/typo3-console  v5.8.5`

**Comment by echavaillaz** [comment]
Perhaps I am not up to date with the ext crawler.

**Comment by tomasnorre** [comment]
You mean version vice? The latest release is 9.0.1

**Comment by tomasnorre** [comment]
Do you have more info regarding this issue @echavaillaz?

**Comment by echavaillaz** [comment]
No, we can close. If I have new information, I will come back here.

Thanks

**Comment by TheNaderio** [comment]
I had exactly the same error, but with "ke_search:ke_search:indexing" command.
Not sure why - the error appears after a nightly update-task. Maybe composerer did something unexpected.

I uninstalled ke_search via composer, installed it again and after that, everything is back to normal again.

Just posting this here to make sure ppl stumbling over this on their research :)
