### ISSUE TITLE
BackendModule throws error when url is a numeral

### ISSUE THREAD

**Issue by linawolf** [AOEpeople/crawler#583]
## Bug Report

**Current Behavior**
Root Page of my site -> Info Module -> Site crawler -> Crawler Log leads to the following error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: htmlspecialchars() expects parameter 1 to be string, integer given | TypeError thrown in file /var/www/html/private/typo3conf/ext/crawler/Classes/Backend/BackendModule.php in line 633.

My Rootpage is a link to the first subpage. On debugging I found that the url in the log Entry of the page is a numeral, not an url. The jsonCompatibilityConverter converts this one into an integer. htmlspecialchars only accepts strings.

**Expected behavior/output**
As it seems to be possible that the url is an integer (why it is is still to be debugged) the display should not throw an error but either display the integer or an error

**Environment**
- Crawler version(s): [9.0.1, master] confirmed this to occur with both 9.0.1 and master
[8785486.diff.zip](https://github.com/AOEpeople/crawler/files/4709892/8785486.diff.zip)

- TYPO3 version(s): [e.g. 9.5.18]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

**Possible Solution**
convert the argument to a string before throwing it into htmlspecialchars. See attached patch

**Additional context**
 "typo3/cms-indexed-search": "^9.5"

**Comment by linawolf** [comment]
Here is the patch: [8785486.diff.zip](https://github.com/AOEpeople/crawler/files/4710057/8785486.diff.zip)

**Comment by tomasnorre** [comment]
This is a duplicate to https://github.com/AOEpeople/crawler/issues/576.

Please reopen the issue if I'm wrong. 
Thanks for the patch file, will have a look.
