### ISSUE TITLE
Serialized string served instead of markup

### ISSUE THREAD

**Issue by infabo** [AOEpeople/crawler#585]
## Bug Report

**Current Behavior**
Frontend of website return the following instead of HTML-markup:

```
a:4:{s:7:"running";b:1;s:10:"parameters";a:3:{s:3:"url";s:146:"https://www.example.com/news/this-is-so-awesome";s:16:"procInstructions";a:1:{i:0;s:24:"tx_indexedsearch_reindex";}s:15:"procInstrParams";a:0:{}}s:3:"log";a:1:{i:0;s:13:"User Groups: ";}s:4:"vars";a:3:{s:2:"id";i:35;s:7:"gr_list";s:4:"0,-1";s:8:"no_cache";b:0;}}
```

**Expected behavior/output**

I should see the website instead of the serialized string.

**Environment**
- Crawler version(s): 9.0.1
- TYPO3 version(s): 9.5.18
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

**Additional context**

ext:staticfilecache is installed. But I guess this should do no harm.

I already executed

```
 $ vendor/bin/typo3 crawler:flushQueue all
```

But this did not help. Still the same issue after the daily scheduled crawler-run.

**Comment by tomasnorre** [comment]
Thanks for reporting this. As we already talked about I'm sure if it's related to the crawler or not, but could be. 

I'll see when I find the time to look into this.

**Comment by tomasnorre** [comment]
How does your crawler configuration look like @infabo ? 
Earlier it was possible similar to the indexed_search processing instruction to have one for staticcache, back when it was nc_staticfile_cache. But that it's the case anymore.

We/I removed some nc_staticfile_cache hooks some time ago:
https://github.com/AOEpeople/crawler/commit/aea5559

**Comment by infabo** [comment]
Hey, just discovered: https://github.com/lochmueller/staticfilecache/commit/d925be8e47da0355c9ffa3ca85ac9a7dd47d8705

**Comment by infabo** [comment]
I guess we can close here. thanks @tomasnorre
