### ISSUE TITLE
flush visible entries in BE info module crawler log

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#586]
TYPO3v.9.5.18

There are two buttons for flushing queue entries. One says "flush entire queue", which I guess would wipe the queue table clean. The other says "flush visible entries", which I figure should delete just the entries visible for the page/pagetree shown. But it does NOT restrict on these records but wipes the table clean.  Can someone confirm?

**Comment by tomasnorre** [comment]
I think you have the dropdown to "all" and therefore it flushed all.
if you switched that to "pending" or "finished" it should only flush that type.

It can be that all of the respected types gets deleted, as we still have this bug: 
https://github.com/AOEpeople/crawler/issues/539

Can you please confirm that the type selection works? if that works, I'll make this a duplicate and close it.
