### ISSUE TITLE
Crawler exits with an error

### ISSUE THREAD

**Issue by kusiboss** [AOEpeople/crawler#587]
## Bug Report

**Current Behavior**
Crawler exits with an error when trying to fetch certain pages. 
	
`Call to a member function getStatusCode() on null`

**Expected behavior/output**
Crawler should continue and log the error.

**Environment**
- Crawler version: 9.5.14
- TYPO3 version: 9.0.1
- Composer mode: yes

**Possible Solution**
It happens when a request doesn't return a status code because for example there is a redirect loop.

**Comment by tomasnorre** [comment]
Hi,

Thanks for your information. Redirect loops isn't wanted regardless of crawler or not.  I would suggest you solve that first, and test if you still have an issue.

If still an issue, please let me know and add more description on how to reproduce this.

**Comment by kusiboss** [comment]
Hi,
In my opinion the crawler shouldn't stop in any case when there a problem accessing a page. Redirects are made by authors and mistakes can happen. The error doesn't happen only with redirect loops, it happens when a request doesn't return a status code.

class GuzzleExecutionStrategy
```
catch (RequestException $e) {
            $this->logger->debug(
                sprintf('Error while opening "%s" - ' . $e->getResponse()->getStatusCode() . chr(32) . $e->getResponse()->getReasonPhrase(), $url),
                ['crawlerId' => $crawlerId]
            );
            return $e->getResponse()->getStatusCode() . chr(32) . $e->getResponse()->getReasonPhrase();
        }
```
The catch part shouldn't throw an exception by itself.

Reproduce:
Add a redirect with target to itself (redirect loop). Start crawling. Crawler will stop as soon as it tries to access that page.

**Comment by tomasnorre** [comment]
Thanks for the additional information, I'll have a look at this.

**Comment by brotkrueml** [comment]
See #584, I will provide a PR shortly.

**Comment by tomasnorre** [comment]
I was thinking that it could be related but wasn't sure.
