### ISSUE TITLE
Indexing of Cached pages does not work

### ISSUE THREAD

**Issue by rvock** [AOEpeople/crawler#595]
## Bug Report

**Current Behavior**
This bug is a bit complicated to describe. Maybe this even is a bug of TYPO3 and not of the crawler extension itself.

When a page is cached in TYPO3's page cache and the indexing process runs, the page will not be indexed.

**Steps to reproduce**
1. Add a crawler queue entry for a cacheable page
2. Call the `Indexing` Module and ensure the page is not indexed
3. Call the `Crawler log` within the `Info`-Module (In TYPO3 backend)
4. You see the Queue-Id, Scheduled-Time, URL etc for the page
5. Click the URL to open the page in the frontend (and cache the page)
6. Click the `Reload` icon to try to index the page using crawler
7. Calll the `Indexing` Module to check if the page is indexed

**Expected behavior/output**
I expect the page to be indexed. The Indexing module still shows the page as "Not indexed"

**Environment**
- Crawler version: 9.0.1
- TYPO3 version: 9.5.19
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

The page itself is indexed by `indexed_search` in the Hook `['tslib/class.tslib_fe.php']['pageIndexing']`. This hook is called in `TSFE->generatePage_postProcessing`:
[TypoScriptFrontendController.php:L3657](https://github.com/TYPO3/TYPO3.CMS/blob/e3505066548317a5a0c125d5db3d6893401b7895/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L3657)

This method is called from the FrontendRequestHandler:
[RequestHandler.php:175](https://github.com/TYPO3/TYPO3.CMS/blob/e3505066548317a5a0c125d5db3d6893401b7895/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L175)

But only if the page is not cached
[RequestHandler.php:155](https://github.com/TYPO3/TYPO3.CMS/blob/e3505066548317a5a0c125d5db3d6893401b7895/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L155)

**Additional context**
As I said, it's possible that this should be fixed in TYPO3.

**Comment by rvock** [comment]
`indexed_search` has a hook, which disables the cache, if the current request is a crawler request:
[TypoScriptFrontendHook.php:L34](https://github.com/TYPO3/TYPO3.CMS/blob/e3505066548317a5a0c125d5db3d6893401b7895/typo3/sysext/indexed_search/Classes/Hook/TypoScriptFrontendHook.php#L34)
This hook checks if `TSFE->applicationData['tx_crawler']['running']` is set. This is no longer the case with Crawler 9.0.1.
It will get set in `CrawlerInitialization.php`, but it looks that Middleware is called too late.

I changed the `RequestMiddleware.php` to:

```
'aoe/crawler/initialization' => [
    'target' => CrawlerInitialization::class,
    'after' => [
        'typo3/cms-frontend/tsfe',
    ],
    'before' => [
        'typo3/cms-frontend/prepare-tsfe-rendering',
    ],
],
```

This works, but I am not sure if this is really correct or not.

**Comment by tomasnorre** [comment]
Hi @rvock,
Thanks for reporting your problem. Unfortunately, I'm not really sharp in the middleware concept yet, so I would need to ask for someone to way in here.

I'll see whom I can reach.

**Comment by rvock** [comment]
This issue can be closed, because it was implemented with https://github.com/AOEpeople/crawler/pull/610

**Comment by tomasnorre** [comment]
Thanks for the update. I thought I had seen some issue from the #610 before, but didn't find it. My bad. 
But thanks for doing a little gardening for me.
