### ISSUE TITLE
Something went wrong: process did not appear within 10 seconds.

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#6]
Hi,

Just upgraded the crawler from 3.2.0 (TYPO3 4.5.22) to the latest 3.5.0 and it seems it does not work anymore.
When trying to add a process the error:

"Something went wrong: process did not appear within 10 seconds."

appears.

I have tried this on my local Windows dev machine and on the Linux server itself, and both seem to fail.

PHP version 5.3.15 on Windows and 5.3.3 on Linux.

IMPORTANT: See dicussion/questions at: https://forge.typo3.org/issues/44875

**Comment by vdespa** [comment]
https://forge.typo3.org/issues/44875 is not public available.

Steps to reproduce in crawler version 5.0.1:

1. Add pages to the crawler queue.
2. Manually start crawling processes (Add process)
3. Click reload
4. When the processes are finished and die, you will start seeing the error:

![screen shot 2016-01-20 at 16 54 42](https://cloud.githubusercontent.com/assets/1197635/12454196/c46ef184-bf96-11e5-86ce-bcd752e7075f.png)

It seems that the action which is executed on "Refresh" is still "Add process". 

system($completePath) evaluates to "" (empty string).

**Comment by tomasnorre** [comment]
Closed as the referred release is quite old.. If you still experience the problem with latest release 5.0.2 please create new ticket.
