### ISSUE TITLE
error with processqueue

### ISSUE THREAD

**Issue by netti251** [AOEpeople/crawler#602]
## Bug Report

**Current Behavior**
I installed the extension and configured it according to the manual.
Furthermore:
```
[index_enable] = 1
[index_externals] = 1
[index_metatags] = 1
[no_cache] = 0
```
I can execute buildqueue and flushqueue in the Backend as well as in the command line.

```
_..................................
....................... crawler:buildqueue 2 crconfig3 --depth 2 --number 100 --mode queue
Putting 11 entries in queue:
...
...
..._
```
When I execute processqueue there is no result. In the commandline I get this error:
```
_.................................
..................... crawler:processqueue --amount 50
Unprocessed Items remaining:0 (1eb4ac4154)
2
add process 1eb4ac4154 (1/1)
Rows: 11 (1eb4ac4154)_

_Uncaught TYPO3 Exception Return value of "AOE\Crawler\Command\ProcessQueueCommand::execute()" must be of the type int, "NULL" returned.
thrown in file /var/typo3_src-10.4.2/vendor/symfony/console/Command/Command.php
in line 258
........................_
```

No indexed element at all.

**Expected behavior/output**
I expected to process the queue without errors and get the index

**Environment**
- Crawler version(s): 9.0.1
- TYPO3 version(s): 10.4.2 / 10.4.4
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**

**Additional context**
Using indexed_search. The crawler should serve for indexing pages because frontend indexing has a severe bug (https://forge.typo3.org/issues/84541) - and therefore frontend indexing is disabled.
Using bootstrap package 11.0.2

**Comment by tomasnorre** [comment]
Hi @netti251 
Thanks for reporting. I have allowed myself to edit your post to have better formatting/readability. 

I'll have to check if I can reproduce this. I have seen it before, but the issue on this was already closed as they could be reproduced anymore. I'll get back to you.

**Comment by brotkrueml** [comment]
It should be fixed with bd4a1637627baaf83c67e0c9c948c190fe3d213a in current master.

**Comment by tomasnorre** [comment]
You're right, I know I had notice/seen something regarding that. Thanks for pointing this out. 

Can you please verify with dev-master @netti251?

**Comment by netti251** [comment]
Thanks a lot to all.

Of course this error ist eliminated now. It was the only point to find out why the crawler dos not produce the index. But it is still the fact that the crawler seems to process the queue - but I get no index.

Using the mode exec in the command line I will have this result (for all urls):

```
crawler:buildqueue 117 crconfig3 --depth 2 --number 100 --mode exec
Executing 1 requests right away:
[08-07-20 09:45] https://crtest/info/test

Processing

https://crtest/info/test (tx_indexedsearch_reindex) =>

<errror>Error checking Crawler Result:  ...
</errror>

```
Processing in the backend has no result in "status" (and produces no index) but corresponding to the time of execution there are several indentical messages in a log-file in 
/typo3temp/var/log
```
Wed, 08 Jul 2020 10:03:14 +0200 [ERROR] request="736fd754e29e1" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"treeLevel = 0"}
```
Nevertheless - for having no usefull error-message I cannot find the reason for not indexing.

For the original topic is not the reason I will close this issue in about 24 h.
Hope there could be further ideas...

**Comment by tomasnorre** [comment]
I'm off sick today, cannot help you futher today.

**Comment by netti251** [comment]
once again many thanks
@tomasnorre get well soon!

**Comment by netti251** [comment]
...no step further until today...

The actual Version of crawler (9.1.0) is installed. Typo3 is now 10.4.4.
Debian 9.13, bootstrap package 11.0.2

I could not find any reason why the crawler is not indexing - and no hint in the web.
It's still the same result.

```
https://crtest/info/test (tx_indexedsearch_reindex) =>

<errror>Error checking Crawler Result:  ...
</errror>
```
All but indexing works fine. 
flushQueue and buildqueue are o.k. In the backend as well as in the command line.

Without having an error message that says anything about the Problem there's no chance for me to get a solution.
Hence my question as to whether there are any known typical mistakes that I might have made in my installation.

Thanks a lot for your attention.

**Comment by tomasnorre** [comment]
you can activate CLI_debuging in the extension settings, don't know if that will help you further but worth a try.

**Comment by netti251** [comment]
thank you very much for comment.
This debugging has been activated from the beginning of my problem. But unfortunately it doesn't bring any additional information.

**Comment by tomasnorre** [comment]
ok. Can you paste my you configuration and the commands that you are executing?

**Comment by netti251** [comment]
Hi and thank you very much
I have attached a file with information about the server and the executed commands (as RTF-file)
[crawler-2.zip](https://github.com/AOEpeople/crawler/files/5040407/crawler-2.zip)
it would be nice if you could find something

**Comment by tomasnorre** [comment]
You're site configuration or baseUrl is not configured correctly. 

`https://wkbinfo/info/aktuelles` isn't a valid URL.

**Comment by netti251** [comment]
It's just for internal use, not a public website. Does this cause problems for indexing with crawler? All other parts of the installation work with this URL.

**Comment by tomasnorre** [comment]
The crawler needs a FQDN, I think, haven't proved it, or try to change it to makring direct request in the crawler settings, might work for your setup too.

**Comment by netti251** [comment]
The Crawler-Config is set to makeDirectRequests. 

When this is set to false I get 

```
https://wkbinfo/info/aktuelles (tx_indexedsearch_reindex) =>

Error checking Crawler Result:  "0 Error creating resource: [message] fopen(): SSL: Success\n[file] \/var\/typo3_src-10.4.4\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/StreamHandler.php\n[line] 323\n[message] fopen(https:\/\/wkbinfo\/info\/aktuelles): failed to open stream: Cannot connect to HTTPS server through proxy\n[file] \/var\/typo3_src-10.4.4\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/StreamHandler.php\n[line] 323"...
```

There is no proxy used for internal purposes.

**Comment by tomasnorre** [comment]
Please try to set up a valid hostname/FQDN for baseurl or Site Configuration for the "box" or what you are using, Otherwise I'm not sure I can help you further. 

A FQDN is expected for a webserver.

**Comment by netti251** [comment]
thanks

I tried with a different baseurl in our domain like
https://wkbinfo.xxx.yyy.de/info....

But still the same result when processing
```
Error checking Crawler Result:  ...
```

**Comment by tomasnorre** [comment]
Did you also make sure that it's used in the crawler config? 
Did you flush queue and build queue again? Changes like this doesn't effect the existing build queue

**Comment by netti251** [comment]
Yes, it was also laid down in the crawler config. I always flush the queue before starting a new test. And I even flush the complete typo3 cache.
 It is to be seen in the backend, that the new URL is used in the queue.

**Comment by tomasnorre** [comment]
I don't know what more I should suggest to you. 
You have to try with a debugger to get further.

Paid Support is also an option: 
If you have a devbox setup that I can get installed on my local environment I can try help out with that. 
The rates we can dicsuss in email.

**Comment by infabo** [comment]
I guess you have a problem that is not directly related to crawler. Check your system can access your website from CLI. Curl or alike

**Comment by netti251** [comment]
thanks for comments

I will answer as soon as possible

**Comment by netti251** [comment]
curl can read the pages in the commandline with or without FQDN.

@tomasnorre about the option paid support: First I would prefer one could have a look at my installation via TeamViewer or so. I still believe, the solution could be simple...
How can I get in contact with you to discuss the details? (rates and procedure)

**Comment by tomasnorre** [comment]
Please contact me over email: tomasnorre@gmail.com

**Comment by tomasnorre** [comment]
Follow up: @netti251 and I had a call yesterday and I couldn't find any misconfigurations in the setup. 
I have tried myself with the local crawler devbox to run without a FQDN which works as well for Direct Requests.

I'm unsure what the problem can be, sounds to me more like a server setting that a misconfiguration in the TYPO3, but I honestly don't know yet. And as long as it's not reproduceable locally, it hard to find the problem.

If anyone can way in here, that would be great.

**Comment by tomasnorre** [comment]
@netti251 

I don't recall is your server setup, apache? Nginx? or something else. Just trying to see what I could change to reproduce the problem.

**Comment by netti251** [comment]
Hi

it is currently like that:

Apache/2.4.25 (Debian)
PHP 7.4.8

Thanks a lot

**Comment by infabo** [comment]
1) get the requested page or pages indexed when you visit the page in the browser?
2) did you set any configuration which results in a no-cache situation? No cache -> No index.
3) did you set the baseurl in the crawler indexing db-record?

**Comment by netti251** [comment]
@infabo 

1. yes, frontendindexing works. I disabled it because of the bug mentioned at the start of this issue (https://forge.typo3.org/issues/84541). But in general the pages can be indexed.
2. no (amongst other things verified by no 1)
3. we tried all combiantions of set/not set the baseurl in Extension Configuration and Crawler Configuration as well as with FQDN or simple server name

Once again we checked the network configuration of the server but could not find any problem. Everything else works as expected.

Thanks a lot

**Comment by infabo** [comment]
Just to clarify: crawler does not Index anything by itself. It just visits URLs. So for indexed_search `Index.enable=1` is a requirement to build up the index. Or did I get that wrong?

**Comment by netti251** [comment]
You are right:

It is set in the template setup
```
[index_enable] = 1
[index_externals] = 1
[index_metatags] = 1
[no_cache] = 0
```


In the extension config for indexed search is set
```
disableFrontendIndexing = true
```

This means only that there is no indexing via frontent. The ability to index the pages is not affected. (but of course I tested this also with disableFrontendIndexing = false - without any difference in the behaviour)

**Comment by netti251** [comment]
OK - here is an update

Some earlier I mentioned I have a proxy entry to reach the TER. It was set in

Settings
Configure Installation-Wide Options ([HTTP][proxy])

Some more processes obviously try to use this proxy although there is no need for it.

The setting now is 
```
[HTTP][proxy] =
```
and in Crawlers Extension Configuration
```
settings.makeDirectRequests = false
```


Now it seemed that the Crawler works fine in the command line. (with and without FQDN)

with
```
settings.makeDirectRequests = true
```

there is no change in Crawlers behaviour

I was so happy
but anyway:

1.
Now I get an error using curl:
```
curl: (56) Received HTTP code 502 from proxy after CONNECT
```

(before curl could read the page)

2.
And when we look into the administration log we will find sometimes an error like this:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'INSERT INTO `index_words` (`wid`, `baseword`, `metaphone`) VALUES (?, ?, ?)' with params [119172293, "versicherungsbeginn", "138802834"]: Duplicate entry '119172293' for key 'PRIMARY' | Doctrine\DBAL\Exception\UniqueConstraintViolationException thrown in file /var/typo3_src-10.4.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 55. Requested URL: https://.....

```

In the command line its shown as "500 Internal Server Error"

This just looks like the above mentioned bug: https://forge.typo3.org/issues/84541

I have found no other effects concerning the work of my installation.

**Comment by tomasnorre** [comment]
I'm happy to hear that you found the problem.
I'm not sure how to help you further.

**Comment by netti251** [comment]
OK, so I will go on this way.

Thanks to all - especially to @tomasnorre - for your help and patience!
