### ISSUE TITLE
[DOC] Troubleshooting - Crawler shows error if the php path is not correct

### ISSUE THREAD

**Issue by PhilippKuhlmay** [AOEpeople/crawler#618]
## Feature Request

**Is your feature request related to a problem? Please describe.**
After I added the ext:crawler at my homepage, I got an TYPO3 exception in Info-Module.

**Describe the solution you would like**
The reason was, that I needed to add the PHP path within the extension configuration. After adding this it worked.

**Describe alternatives you've considered**
There is no known alternative.

**Teachability, Documentation, Adoption, Migration Strategy**
I would suggest to add this to the troubleshooting area within the documentation.

**TYPO3 Error in backend:**
![Bildschirmfoto 2020-08-12 um 17 17 06](https://user-images.githubusercontent.com/57705869/90222314-1adebc00-de0c-11ea-84c3-0b0e14d63aed.png)

**Solution:**
![Bildschirmfoto 2020-08-12 um 17 16 50](https://user-images.githubusercontent.com/57705869/90222150-c4717d80-de0b-11ea-80da-81725d5f69cb.png)

**Comment by tomasnorre** [comment]
@PhilippKuhlmay Could you perhaps provide a PR with the change? 
https://github.com/AOEpeople/crawler/blob/master/Documentation/Troubleshooting/Index.rst

**Comment by PhilippKuhlmay** [comment]
@tomasnorre Yes I can do this.

**Comment by PhilippKuhlmay** [comment]
This is merged in #619

**Comment by tomasnorre** [comment]
Sorry forgot to close this. Thanks for taking care.
