### ISSUE TITLE
[BUG] Type Error Exception when localizing FAL resources

### ISSUE THREAD

**Issue by typecat** [AOEpeople/crawler#620]
## Type Error Exception when localizing FAL resources

**Current Behavior**
When using the  "Localize all records"  button for FAL resources in a localized record following exception is thrown:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageId() must be of the type integer, null given, called in /.../typo3conf/ext/crawler/Classes/Controller/CrawlerController.php on line 394 | TypeError thrown in file /.../typo3conf/ext/crawler/Classes/Controller/CrawlerController.php in line 535. Requested URL: http://.../typo3/index.php?route=%%2Fajax%%2Frecord%%2Finline%%2Fsynchronizelocalize&token=--AnonymizedToken--

The FAL resources get  localized anyway, but the editor receives an "Error 500 Internal Server Error" flash message and needs to reload the form to see that the localization happened.

**Expected behavior/output**
The FAL resources get localized without an exception.

**Environment**
- Crawler version: 9.1.0
- TYPO3 version: 9.5.20
- Composer Mode: yes

**Comment by tomasnorre** [comment]
hi @typecat 

Can you please add steps on how to reproduce this? I don't find the "Localize all Records" button. And not sure what you mean by a FAL resource.

**Comment by rintisch** [comment]
I get this error (only sometimes) when starting a symfony command via CLI and now I also got this error when deleting multiple pages with list module (this seems to happen every time).

Here's a screenshot, hope this helps.

![grafik](https://user-images.githubusercontent.com/44193208/92915698-1a4a3d00-f42d-11ea-9f61-ee3cb84a9d5d.png)

**Comment by tomasnorre** [comment]
Thanks for your input @rintisch. I have an idea where the problem lies, but as long I don't have good steps to reproduce, I cannot be sure all use cases are caught. 

But the deleting pages I would need to test manually, that can be added to an automated test as well, so thank a lot for the additional information.

**Comment by rintisch** [comment]
@tomasnorre You're welcome. And: As I wrote the comment above I forgot that my console command deletes (multiple) pages with as well so I guess it's the same problem as deleting them manually. 

Thanks for digging into it!

**Comment by tomasnorre** [comment]
@rintisch Do you have the cli command that you can share? Would help me.

**Comment by rintisch** [comment]
That's the code which delete the pages:

```
public function removeExistingPages(int $rootPid)
    {
        // allow to delete whole tree recursively
        $this->dataHandler->deleteTree = true;

        $pagesQueryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable("pages");
        $statement = $pagesQueryBuilder
            ->select("uid")
            ->from("pages")
            ->where(
                $pagesQueryBuilder->expr()->eq("pid", $pagesQueryBuilder->createNamedParameter($rootPid, \PDO::PARAM_INT))
            )
            ->execute();

        while ($row = $statement->fetch()) {
            $cmd["pages"][$row["uid"]]["delete"] = 1;
        }

        $this->dataHandler->start([], $cmd);
        $this->dataHandler->process_cmdmap();

        $this->dataHandler->deleteTree = false;
    }
```

**Comment by tomasnorre** [comment]
oh. Now I get you @rintisch , thought it was a generic cli command from typo3 or typo3cms. 

I'll will test it with this snippet.

**Comment by typecat** [comment]
Hi @tomasnorre the error occurs e.g. in a filed with following TCA configuration:

```php
'gallery_images' => [
            'exclude' => true,
            'label' => $languageFile . 'tx_myextension_domain_model_reference.gallery_images',
            'config' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig(
                'galleryImages',
                [
                    'appearance' => [
                        'createNewRelationLinkTitle' => 'LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:images.addFileReference',
                        'showPossibleLocalizationRecords' => true,
                        'showAllLocalizationLink' => true
                    ],
                    'overrideChildTca' => [
                        'types' => [
                            '0' => [
                                'showitem' => '
                                --palette--;LLL:EXT:lang/locallang_tca.xlf:sys_file_reference.imageoverlayPalette;imageoverlayPalette,
                                --palette--;;filePalette'
                            ],
                            \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE => [
                                'showitem' => '
                                --palette--;LLL:EXT:lang/locallang_tca.xlf:sys_file_reference.imageoverlayPalette;imageoverlayPalette,
                                --palette--;;filePalette'
                            ]
                        ]
                    ]
                ],
                $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']
            )
        ],
```

**Comment by tomasnorre** [comment]
Hi @typecat and @rintisch ,

Could you please check this PR to see if that solves your issue here? 
https://github.com/AOEpeople/crawler/pull/667

I don't find a way to reproduce, so I'm trying to solve it from how I read the stacktrace.

**Comment by rintisch** [comment]
Hi @tomasnorre,
sorry for the delay. 
I can just report: It's working on my machine now 👍

**Comment by tomasnorre** [comment]
Thanks for confirming, I'll have this merged and released soonish then.
