### ISSUE TITLE
exclude of tx_crawler_configuration does not work

### ISSUE THREAD

**Issue by vzz3** [AOEpeople/crawler#625]
## Bug Report

**Current Behavior**
The `crawler:buildQueue` command returns URLs for pages that are listed in the `tx_crawler_configuration.exclude` field.

The problem occurs in the method `drawURLs_addRowsForPage()` from class `AOE\Crawler\Controller\CrawlerController` in line 1458.
```php
if (! in_array($pageRow['uid'], $this->expandExcludeString($confArray['subCfg']['exclude']), true)) {
```
The problem is that  `$pageRow['uid']` contains an **integer** while the method `$this->expandExcludeString()`call returns the excluded page IDs as array with **strings**. Since `in_array()` is used in strict type checking mode (`true` as third param) it returns `false` for page IDs which are actually included in the  `tx_crawler_configuration.exclude` database field.

**Expected behavior/output**
If a page pid is listed in a crawler configuration in the exclude field, I expect that a `crawler:buildQueue` run for that configuration does not produce URLs for the excluded pages. 

**Environment**
- Crawler version(s): 9.1.0
- TYPO3 version(s): 9.5.22
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Use `in_array()` in non strict mode:
```php
if (! in_array($pageRow['uid'], $this->expandExcludeString($confArray['subCfg']['exclude']), false)) {
```

**Additional context**
My typical use case for the `tx_crawler_configuration.exclude` feature: I wan't to exclude typical single view pages, (e.g. a page that only contains the single view plugin for news records) from being crawled. At leas in some crawler configurations. Since it makes no sense to request pages that only contain a plugin that should display a single record without the GET parameter that specifies the record that should be displayed. Furthermore, requests for pages that contains single view plugins without the required GET parameters of the plugin, usually leads to unnecessary errors.

**Comment by tomasnorre** [comment]
Thank you for your information @vzz3, I think some text/words are missing in the last sentence about Additional Context, I'm not sure how to understand that information. 

Could you please update this.

**Comment by tomasnorre** [comment]
@vzz3 Could you please check that the PR solves your problem? I think this is the cleanest solution with the current state of code.

**Comment by vzz3** [comment]
I have update the additional context section of my bug report. However, i think it is not important for the bug report. I only have explained my use case for the *exclude page*, because your bug report template "asked" for *Additional context*.

**Comment by vzz3** [comment]
I tested your PR #626 and it solves my problem.

**Comment by tomasnorre** [comment]
Thanks for testing. I'll have it merge and see when I'll do a release.

**Comment by vzz3** [comment]
Thank you for your fast fix!

**Comment by tomasnorre** [comment]
Thank you for testing it. :) Wish all fixed was that fast, but I have many that is way to old :(
