### ISSUE TITLE
[BUG] getUrlsForPageId() must be of the type int, null given

### ISSUE THREAD

**Issue by ayacoo** [AOEpeople/crawler#634]
## Bug Report

**Current Behavior**
Due to a wrong setting I got the following error message in the page properties:

`Argument 1 passed to AOE\Crawler\Controller\CrawlerController::getUrlsForPageId() must be of the type int, null given, called in [...]web/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php on line 394`

`$res = $this->getUrlsForPageId($pageRow['uid']);`

Reproducable with a misconfigured TsConfig (non existing page)

`TCEMAIN {
    clearCacheCmd = 123456
}`

The crawler API then tries to reach the non-existent page (123456) by the hook and passes a null array. Crawler would have an integer (Page UID)

**Expected behavior/output**
Crawler catches empty/null pages

**Environment**
- Crawler version(s): 9.1.0
- TYPO3 version(s): 9.5.22
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

`        if ($message === false && ((int) $pageRow['uid'] > 0)) {
            $res = $this->getUrlsForPageId($pageRow['uid']);
            $skipMessage = '';
        } else {
            $skipMessage = $message;
            $res = [];
        }`

If there are still questions, please contact me.

**Comment by tomasnorre** [comment]
Thanks will check it out.

**Comment by tomasnorre** [comment]
Hi @ayacoo,

How do you reproduce the error besides adding the 
```
TCEMAIN { clearCacheCmd = 123456 }
```
to the Page TsConfig?

**Comment by ayacoo** [comment]
@tomasnorre I use an import of TsConfig in a sysfolder outside of root pages. When I change a page, I get the error. Crawler 
then tries to call up page 123456 and this does not work. 

![screen](https://user-images.githubusercontent.com/5963331/96310457-a987d900-1007-11eb-8477-11738b10ff32.png)

**Comment by tomasnorre** [comment]
Thanks will check it out.

**Comment by tomasnorre** [comment]
I've found the problem. In the https://github.com/AOEpeople/crawler/blob/master/Classes/Hooks/DataHandlerHook.php#L29 we do not check if the page exists or not and if it gets added to the queue and doesn't exist the function getUrlsForPageId() cannot figure out if it should be skipped or not.

So I need to add a check for if the page exists, I'm currently working on added tests to prove that my fix works.

**Comment by tomasnorre** [comment]
@ayacoo Could you please check if this PR solves your problem?

**Comment by ayacoo** [comment]
@tomasnorre Can confirm it via 9.5.22 :-) Thanks!

**Comment by tomasnorre** [comment]
Super. I'll merge it and have a new release done this weekend.
