### ISSUE TITLE
Usage of PHP 8 Function str_contains

### ISSUE THREAD

**Issue by Freshmeat-ch** [AOEpeople/crawler#657]
## Bug Report

**Current Behavior**
Backend Module "Log" can not be used.

**Expected behavior/output**
When switching to Crawler Log the Backend > Info shows an Error / no content.

**Environment**
- Crawler version(s): 9.1.3
- TYPO3 version(s): 9.5.23
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Possible Solution**
Replace
`if (str_contains($resStatus, 'Error:')) {`
with
`if (strpos($resStatus, 'Error:') !== false) {`

**Comment by tomasnorre** [comment]
Thanks for your report @Freshmeat-ch you are indeed correct, I was a little to fast there. 

Will change this and have a new release done.

**Comment by tomasnorre** [comment]
As the crawler requires the `symfony/console` which again requires the `symfony/polyfill-php80` this is "only" an issue i non-composer mode. 

https://packagist.org/packages/symfony/console

**Comment by tomasnorre** [comment]
@Freshmeat-ch Please test with version 9.1.4
