### ISSUE TITLE
Flushing queue not working - caused by Class Assert\Assert not found

### ISSUE THREAD

**Issue by Freshmeat-ch** [AOEpeople/crawler#658]
## Bug Report

**Current Behavior**
In a non-composer context, flushing the queue runs into an Error caused by an ussage of beberlei/assert. 
`Assert::that($crawlAction)
            ->inArray(['start', 'log', 'multiprocess']);`
crawler/Classes/Value/CrawlAction.php:33
crawler/Classes/Value/QueueFilter.php:33

**Expected behavior/output**
No Error should be thrown.

**Environment**
Crawler version(s): 9.1.3
TYPO3 version(s): 9.5.23
Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Possible Solution**
Replace it with a simple in_array()?

**Comment by tomasnorre** [comment]
Thanks for reporting @Freshmeat-ch

**Comment by tomasnorre** [comment]
This is resovled with #660

**Comment by tomasnorre** [comment]
@Freshmeat-ch please test with version 9.1.4
