### ISSUE TITLE
Bug in cli command 'crawler:processQueue' related to 'trustedHostsPattern'

### ISSUE THREAD

**Issue by gelbehexe** [AOEpeople/crawler#662]
## Bug Report

**Current Behavior**
When using cli command 'crawler:processQueue' the following exception is thrown

Uncaught TYPO3 Exception #1396795884: The current host header value does not match the configured trusted hosts pattern! Check the pattern defined in $GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] and adapt it, if you want to allow the current host header 'mydomain.de:8077' for your installation.
thrown in file /mypath/to/typo3root/typo3/sysext/core/Classes/Utility/GeneralUtility.php
in line 2722

It's only affected if no standard port is used

**Expected behavior/output**
No exception is throw.

**Environment**
- Crawler version(s): 9.1.4
- TYPO3 version(s): 10.4.10
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
In file 'cli/bootstrap.php' line 73 just convert '$_SERVER['SERVER_PORT']' to string as in TYPO3 port is only comparing this value to a string.
`$_SERVER['SERVER_PORT'] = (string)$urlParts['port'];`

**Additional context**

See: `\TYPO3\CMS\Core\Utility\GeneralUtility::hostHeaderValueMatchesTrustedHostsPattern()`:
```php
            $parsedHostValue = parse_url('http://' . $hostHeaderValue);
            if (isset($parsedHostValue['port'])) {
                $hostMatch = (strtolower($parsedHostValue['host']) === strtolower($_SERVER['SERVER_NAME']) && (string)$parsedHostValue['port'] === $_SERVER['SERVER_PORT']);
            } else {
                $hostMatch = (strtolower($hostHeaderValue) === strtolower($_SERVER['SERVER_NAME']) && $defaultPort === $_SERVER['SERVER_PORT']);
            }

´´´

**Comment by tomasnorre** [comment]
Thanks for your bug report @gelbehexe. I'll take a look at this.
