### ISSUE TITLE
While accessing crawler log from backend module "info"

### ISSUE THREAD

**Issue by mihirbhatt** [AOEpeople/crawler#669]
![crawler-bug1](https://user-images.githubusercontent.com/2562193/100993449-6e237880-357b-11eb-99a3-1b0fbef0b070.png)

## Bug Report

**Current Behavior**
While accessing crawler log from backend module "info", It throws error of htmlspecialchars function

**Expected behavior/output**
It should show the crawler logs of all the urls

**Environment**
- Crawler version(s): 9.1.4
- TYPO3 version(s): 9.5.23
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by tomasnorre** [comment]
Thanks for your input @mihirbhatt, 

Can you provide steps on how so reproduce this? 
Do you e.g. use indexed_search together with it? 
If so might it be a duplicate of https://github.com/AOEpeople/crawler/issues/576 ?
