### ISSUE TITLE
[BUG] Labels in scheduler module contains html

### ISSUE THREAD

**Issue by PhilippKuhlmay** [AOEpeople/crawler#671]
## Bug Report

**Current Behavior**
The labels within a task in the scheduler module contains html.
<img width="725" alt="Bildschirmfoto 2020-12-03 um 22 13 18" src="https://user-images.githubusercontent.com/57705869/101089341-52d55f00-35b5-11eb-9749-8db08f0ad008.png">

**Expected behavior/output**
The labels should not contain html.

**Environment**
- Crawler version(s): 9.1.4
- TYPO3 version(s): 10.4.10
- Is your TYPO3 installation set up with Composer (Composer Mode): yes, composer mode

**Possible Solution**
No known solution yet

**Additional context**
-

**Comment by tomasnorre** [comment]
Hi @PhilippKuhlmay 

This is a core problem, haven't found a ticket on forge for it yet. But will create one. 
![Screenshot from 2020-12-04 05:32:58](https://user-images.githubusercontent.com/1212481/101122241-49b6b300-35f2-11eb-9876-54beafa37161.png)

**Comment by tomasnorre** [comment]
I've added a issue on forge now. 
https://forge.typo3.org/issues/92983
