### ISSUE TITLE
Sites/URLs get crawled but not indexed 

### ISSUE THREAD

**Issue by bh-teufels** [AOEpeople/crawler#679]
## Bug Report

**Current Behavior**
Pages get crawled (URLs in crawler log correct) but not indexed.
If i call the URLs from the log manually the page/record get indexed

**Expected behavior/output**
all generated queue (urls) will be indexed automatically

**Environment**
- Crawler version(s): 9.1.4
- TYPO3 version(s): 9.5.22
- PHP Version: 7.3
- Composer Mode: yes

**Configuration**
- Multi-Domain for test setup on one Domain only (RootID = 10)
- Page 10 (Root) -> Crawler Configuration "default"
Processing instruction filter > Re-Indexing Off
Base-URL: https://user:pw@staging.test-domain.de/
No additional Configuration
- Page 92 (News-Detail) -> Crawler Configuration "news"
Processing instruction filter > Re-Indexing On
Base-URL: https://user:pw@staging.test-domain.de/
Pids only: 92
Configuration: &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]=[_TABLE:tx_news_domain_model_news; _PID:90; _WHERE: hidden = 0] 
(90 = Storage of the news)
- Page 102 (Detail Records Own Ext) -> Crawler Configuration "product"
Processing instruction filter > Re-Indexing On
Base-URL: https://user:pw@staging.test-domain.de/
Pids only: 102
Configuration: &tx_myext_pi1[action]=show&tx_myext_pi1[controller]=Product&tx_myext_pi1[product]=[_TABLE:tx_myext_domain_model_product; _PID:100; _WHERE: hidden = 0 and show_in_search = 1]
(100 = Storage of the records)
- Crated tasks:
crawler:buildQueue 10 'default,news,product' --depth=99 --mode=exec
with mode exec the queue should be executed directly and call the generated URLs correct?
Also tried it with additional task crawler:processQueue but did not work either
- In global EXT Settings settings.makeDirectRequests is set to TRUE 

**Additional context**
- using `indexed_search`
- caching/indexing in general is working. manual visit of the page creates an index entry.
- If i set settings.makeDirectRequests to FALSE i get the error:
Uncaught TYPO3 Exception: #1518472181: No crawler entry found | TYPO3\CMS\Core\Error\Http\ServiceUnavailableException thrown in file /var/www/clients/client12/web34/web/ws/20/staging/releases/20201211163503/web/typo3/sysext/frontend/Classes/Controller/ErrorController.php in line 49. Requested URL: https://staging.test-domain.de/demo-page
- if i visit the page https://staging.test-domain.de/demo-page manual page get indexed

**Comment by bh-teufels** [comment]
Hello @tomasnorre did you need further informations?

**Comment by tomasnorre** [comment]
No, I don't need further information atm, but I need to verify the problem to be able to label and address it correctly. 
Didn't get to it yet.

**Comment by vincentvega123** [comment]
Hello, same problem here with a Typo3 10.4-Installation and crawler 9.1.4 (PHP 7.3). Configuration is quite similar to the given one above, but I am only crawling the Pagetree (no records, etc.). After crawling the pages (status OK afterwards), no pages are indexed. If I turn off „disable indexing in frontend“ in the indexed_search config, pages are indexed (while accessing manually in the frontend and also from the crawler queue). Additionaly I am using the ext secure_downloads and files (pdf,doc, etc) are only indexed when I deactivate this extension. This worked also fine before I made an upgrade from 8.7 to 10.4.

**Comment by tomasnorre** [comment]
Thanks for confirming. 
Upgrade from 8.7 -> 10.4 is also two quite different crawler versions. 

I'll see if find a way to added tests for this to make it reproducible, this is the best way to have it fixed. 

PRs are of course more than welcome.

**Comment by tomasnorre** [comment]
>  Processing instruction filter > Re-Indexing Off
@bh-teufels Do I read this correct, that the checkbox for Re-indendex is not checked? 

Like this? 
![Screenshot from 2020-12-18 21:34:22](https://user-images.githubusercontent.com/1212481/102658931-d88e0880-4178-11eb-9089-861aad5df902.png)

If that's the case that would explain why it's not indexed. 

The direct request = false problem sounds like unrelated and perhaps a different problem.

**Comment by vincentvega123** [comment]
In my Case the re-indexing is active. If it helps for debugging, I can install a clone of the website and give you access to the backend and FTP. I am sorry, that I can not contribute further, since I am not a coder.

**Comment by tomasnorre** [comment]
Don't need to worry. That you are confirming and offering help is also a huge help. Not every contribution needs to be code. 
I'll see if I find a way to debug before you have the hassle of giving me access.

**Comment by bh-teufels** [comment]
i tried with both option (Re-indexing on and off) neither worked.
i will try to reproduce the errors with crawler devbox in the next days

**Comment by tomasnorre** [comment]
Thanks that could be really helpful. If you can reproduce it there, it's just me not getting the problem correct. And that I can learn from :)

**Comment by bh-teufels** [comment]
in my case it seems to had a conflict with the lochmueller/staticfilecache Extension.
I deactivated the staticfilecache Extension and give the crawler a run overnight and it seems to working.
i tired reactivate the staticfilecache Extension to reproduce the arrow but strangely enough now i could not reproduce it.
Maybe it was something with class autoload and fixed it by deactivate/activate of the extension.

I now have staticfilecache reactivated and will check if crawler/indexing works overnight

**Comment by tomasnorre** [comment]
Could it be related to this? 
https://github.com/AOEpeople/crawler/issues/642 
https://github.com/AOEpeople/crawler/commit/0f7cb6abac4d8d6e228b0385665dc02f17cdfdcb

This is released yesterday in the 9.1.5 version. But was in default branch for some time.

**Comment by bh-teufels** [comment]
i could reproduce the error

An error occurred trying to process items for field "Processing instruction filter" (TYPO3 Fatal Error: Extension key "tx_staticfilecache_clearstaticfile" is NOT loaded!).

I am on 
lochmueller/staticfilecache : 9.0.0
crawler: 9.1.4

Maybe i had to update staticfilecache and give it a try

**Comment by tomasnorre** [comment]
The fix I'm talking about is in the Crawler and not StaticFilecache. 

Try to update the Crawler.

**Comment by bh-teufels** [comment]
still got the error 
`An error occurred trying to process items for field "Processing instruction filter" (TYPO3 Fatal Error: Extension key "tx_staticfilecache_clearstaticfile" is NOT loaded!).`
on 
lochmueller/staticfilecache : 9.0.0
crawler: 9.1.5

**Comment by tomasnorre** [comment]
Just seeing this `tx_staticfilecache_clearstaticfile` where is this coming from? Which extension is that? 
The extension key for the Staticfilecache is `staticfilecache` so not sure where this is coming from. 

If there is a new version for the `lochmueller/staticfilecache` that is supported on your setup I would try to update that too.

**Comment by bh-teufels** [comment]
simple update of staticfilecache to version 10.* or 11.* not working 
getting error FE/BE with both versions so have to see when I find the time to examine it more closely

**Comment by tomasnorre** [comment]
ok. I'll see if I can get further locally.

**Comment by tomasnorre** [comment]
I have `"lochmueller/staticfilecache": "^11.1"`  in the Crawler Devbox.

**Comment by kraemer-igroup** [comment]
Hello, I have the same problem with TYPO3 10.4.13 and crawler 9.2.2 (PHP 7.3) like @vincentvega123 . It only works with activating frontend indexing in indexed_search extension configuration (basic.disableFrontendIndexing = 0), which I wanted to avoid by using the crawler extension:
![indexed_search-disable-indexing](https://user-images.githubusercontent.com/10868556/108198639-26dd6a80-711c-11eb-92ea-ae317f173ad0.png)

For my last crawler project I used TYPO3 9.5 with crawler 9.1.0 and basic.disableFrontendIndexing = 1 and pages get indexed as they should. Both projects also have staticfilecache installed (version 11.1.7 with TYPO3 9.5 and version 12.0.4 with TYPO3 10.4). After deinstalling staticfilecache on the 10.4 installation pages still do not get indexed.

Maybe this helps with troubleshooting this issue.

**Comment by tomasnorre** [comment]
@kraemer-igroup 

> Update2 17.02. 16:35: sorry, one more thing. It is working with staticfilecache (on my installation) if the crawler extension is installed after staticfilecache was installed. When I reinstalled staticfilecache it broke the indexing. Before I installed the crawler extension after the staticfilecache extension and it worked fine (but only with basic.disableFrontendIndexing = 0).

Would this mean that adding the load order over the suggestion in `ext_emconf.php` would be a valid fix for you? 

I'm not sure how to understand your last comment.

**Comment by tomasnorre** [comment]
Just in case it's enough, this would be the change needed in `ext_emconf.php`

```diff
- 'suggests' => [],
+ 'suggests' => [
+     'staticfilecache' => '10.0.0-0.0.0'
+ ],
```

**Comment by twestner** [comment]
In my project changing the install order has not solved the issue.

**Comment by tomasnorre** [comment]
Thanks for confirming. Will dig further into this.

**Comment by tomasnorre** [comment]
@twestner @kraemer-igroup Could you please check that this PR fixes the problem for you? 
https://github.com/AOEpeople/crawler/pull/735

**Comment by twestner** [comment]
hm, here the bugfix does not change anything. But as another user has confirmed, that it looks fine for him, I can go into detail in my project this evening. maybe I can tell more then.

**Comment by tomasnorre** [comment]
Which user? @CDRO "just" did the Code Review, not verified it. 

More information would be helpful, thanks. It can also be that it's two different problem, just though they were related, so that's why I asked you to test as well.

**Comment by twestner** [comment]
I think this issue is quite simple: indexing stops, when disableFrontendIndexing is true or when forceIndexing is not set.
-> disableFrontendIndexing = 0 -> works, but that's not what we want
-> forceIndexing = 1 -> would work, but is not set by the crawler anywhere, I think.


[issue-679-set-forceIndexing.txt](https://github.com/AOEpeople/crawler/files/6313418/issue-679-set-forceIndexing.txt)
EXT:indexed_search/Classes/Hooks/TypoScriptFrontendHook.php, L71 ff
```
if ($disableFrontendIndexing && !$forceIndexing) {
            $timeTracker->setTSlogMessage('Index page? No, Ordinary Frontend indexing during rendering is disabled.');
            return;
}
```

with this patch everything works for me with LTS 10.4.15 and crawler 9.2.4

**Comment by tomasnorre** [comment]
Hi @twestner 

Thanks for digging more into this. 
From reading the code you are referring to, it looks like it should work. 

Would you mind making a PR of it, so that you will get the credit for the fix too?

**Comment by bjo3rnf** [comment]
The patch provided by @twestner works for me as well. Thank you.

**Comment by vitd** [comment]
The patch works for me as well. TYPO3 10.4.17 / crawler 9.2.5.

**Comment by tomasnorre** [comment]
Thanks for confirming both of you. I'll have this added to the next release of the Crawler, will be version 10.0.0
