### ISSUE TITLE
Remove auto-created fields in ext_tables.sql definition

### ISSUE THREAD

**Issue by helsner** [AOEpeople/crawler#710]
Mini-Improvement:

The `tx_crawler_configuration` table definition in `ext_tables.sql`
can be adapted as fields like `cruser_id` are provided by TCA and thus will be created automatically.
They can safely be removed.

**Comment by tomasnorre** [comment]
Thanks @helsner. 

I didn't know about that, can you give me an example? Not 100% sure what you mean.

**Comment by helsner** [comment]
yes - here's the official docu
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Feature-85160-AutoCreateManagementDBFieldsFromTCACtrl.html
