### ISSUE TITLE
503 error on buildQueue with mode=exec after update to 9.2.1

### ISSUE THREAD

**Issue by brotkrueml** [AOEpeople/crawler#714]
## Bug Report

**Current Behavior**
After updating from 9.1.2 to 9.2.1 I experienced an error on executing the command

`vendor/bin/typo3 crawler:buildQueue 3 deployment --mode exec`:

    https://website.ddev.site:8443/en/ () => 
    Error checking Crawler Result:  "503 Service Unavailable"...

However executing

`vendor/bin/typo3 crawler:buildQueue 3 deployment --depth 99` and then
`vendor/bin/typo3 crawler:processQueue`

it works.

I am using a PageTS configuration.

**Expected behavior/output**
The pages should be crawled without an error like in 9.1.2. In 9.1.3 I experienced the same behavior, so maybe something in between was introduced.

**Steps to reproduce**
My PageTS configuration (3 is the page uid of the home page):

    tx_crawler.crawlerCfg.paramSets {
        deployment = &L=[0-3]
        deployment {
            pidsOnly = 3
        }
    }

Command executed:
`vendor/bin/typo3 crawler:buildQueue 3 deployment --mode exec`

**Environment**
- Crawler versions: 9.1.3-9.2.1
- TYPO3 version: 10.4.12
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
I've seen this behaviour too. Will see if I can come up with a fix for the next release.

**Comment by tomasnorre** [comment]
Hi @brotkrueml 

I can confirm that the bug is introduced between 9.1.2 and 9.1.3, more precise this commit: 
https://github.com/AOEpeople/crawler/commit/2299e9900b4a6c938387b0afe6a4b4f9f04f89b1

I haven't found out why yet. But getting closer.

**Comment by tomasnorre** [comment]
hi @brotkrueml 

I found the problem, can you please very that it works for you? Then I'll be added a PR and do a new release.

```diff
diff --git a/Classes/Controller/CrawlerController.php b/Classes/Controller/CrawlerController.php
index b62ad8b..e874411 100644
--- a/Classes/Controller/CrawlerController.php
+++ b/Classes/Controller/CrawlerController.php
@@ -1285,7 +1285,7 @@ class CrawlerController implements LoggerAwareInterface
             $this->tableName,
             $field_array
         );
-        $queueId = $connectionForCrawlerQueue->lastInsertId($this->tableName, 'qid');
+        $queueId = $field_array['qid'] = $connectionForCrawlerQueue->lastInsertId($this->tableName, 'qid');
         $result = $this->queueExecutor->executeQueueItem($field_array, $this);
 
         // Set result in log which also denotes the end of the processing of this entry.
```

**Comment by brotkrueml** [comment]
Thanks for the quick patch. I tested it and it works :-)

**Comment by tomasnorre** [comment]
Super. I'll see if I can get a release out this week.
