### ISSUE TITLE
Installation breaks without composer 

### ISSUE THREAD

**Issue by npostnik** [AOEpeople/crawler#726]
If composer mode is off, the following code in ext_localconf.php is executed:
`if (!\TYPO3\CMS\Core\Core\Environment::isComposerMode()) {
    require \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('crawler') . '/Resources/Private/Php/Libraries/vendor/autoload.php';
}`
There is no file at this path and the installation is broken.

**Comment by tomasnorre** [comment]
Hi @npostnik 

Thanks for your issue. I need a little more information. 

TYPO3 Version?
Crawler Version?

**Comment by npostnik** [comment]
Hi @tomasnorre, 
thank you for the quick reply. 

It a TYPO3 9.5.24. It was a composer installation, but now my client wants it to be a 'no-composer' installation.

Crawler is installed in version 9.2.1. But the mentioned lines of code are in the lastest master as well and the required file at this path is missing. Should it be generated during extension installation?

https://github.com/AOEpeople/crawler/blob/main/ext_localconf.php

**Comment by tomasnorre** [comment]
Hi @npostnik 

No it should be created as part of the extension release.
https://github.com/AOEpeople/crawler/blob/main/composer.json#L108

How did you download, with a git-clone or from TER? 
If from git-clone that would explain the issue.

**Comment by npostnik** [comment]
The issue is resolved - I reinstalled the crawler extension from TER. Problem was, that the extension was initially installed with composer. In order to switch off composer mode, I removed the TYPO3_COMPOSER_MODE part from autoload file. Then the issue occured.

Thank you for your help!

**Comment by tomasnorre** [comment]
No problem. Let me know if you run into other issues.
