### ISSUE TITLE
Wrong evaluation in TCA for processing_instruction_filter

### ISSUE THREAD

**Issue by jyskweb** [AOEpeople/crawler#727]
## Bug Report

**Current Behavior**
Can not save configuration record due to wrong eval-property in TCA.

**Environment**
- Crawler version(s): 9.2.2
- TYPO3 version(s): 10.4.13
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
In _tx_crawler_configuration.php_ line 75: 
Remove:  `'eval' => 'required',`
Add:  `'minitems'=> 1,`

**Doc**
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Select/CheckBox/Properties.html

**Comment by tomasnorre** [comment]
Thanks will have a look.
