### ISSUE TITLE
"sofort" could not be parsed by \DateTime constructor

### ISSUE THREAD

**Issue by Patta** [AOEpeople/crawler#728]
## Bug Report

**Current Behavior**
After making changes on a page and try to open the crawler info module, an error occurred.

`Oops, an error occurred!
"sofort" could not be parsed by \DateTime constructor: DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character
More information regarding this error might be available online.`
https://docs.typo3.org/typo3cms/exceptions/master/en-us/Exceptions/1241722579.html

warning.log:
`[CRITICAL] request="2a055eea54ad5" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1241722579: "sofort" could not be parsed by \DateTime constructor: DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /var/www/vhosts/REMOVED/private/typo3/sysext/fluid/Classes/ViewHelpers/Format/DateViewHelper.php in line 163. Requested URL: https://REMOVED/typo3/index.php?route=%2Fmodule%2Fweb%2Finfo&token=--AnonymizedToken--&id=13980 - {"TYPO3_MODE":"BE","exception":"TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception: \"sofort\" could not be parsed by \\DateTime constructor: DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character in /var/www/vhosts/REMOVED/private/typo3/sysext/fluid/Classes/ViewHelpers/Format/DateViewHelper.php:163\ ...`

**Expected behavior/output**
After making changes on a page and try to open the crawler info module, the module is visible.

**Steps to reproduce**
- Crawler config on root page without special configuration. Just config name and usergroup for cache warmup.
- Edit a subpage and save and exit.
- Open the info module on this or the root page
- The error is shown

**Environment**
- Crawler version(s): 9.2.2
- TYPO3 version(s): 10.4.13
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- PHP 7.4.14

**Possible Solution**
none

**Additional context**
none

**Comment by tomasnorre** [comment]
Thank you for your report @Patta, 
I have a feeling that I have seen this issue before. Would need to dig into it.

**Comment by Patta** [comment]
Maybe the wrong dates in the crowler log are related?

`crawler:buildQueue` scheduler for this site is set to `10 4 * * *`
`crawler:processQueue` is set to `0 */1 * * *`

![Screenshot-2021-03-15-092458](https://user-images.githubusercontent.com/2151127/111124713-1a103300-8571-11eb-8dcc-cb4eed6b63bc.jpg)

**Comment by rvock** [comment]
Relevant code positions:
https://github.com/AOEpeople/crawler/blob/04dfad88f1ab5f1e2b80dd185dea7f4ecd7a2523/Classes/Backend/RequestForm/LogRequestForm.php#L365
https://github.com/AOEpeople/crawler/blob/04dfad88f1ab5f1e2b80dd185dea7f4ecd7a2523/Resources/Private/Templates/Backend/ShowLog.html#L131

The LogRequestForm sets the translated string for now (german: "sofort") as value for `$row[scheduled]`. The template then feeds that value to the `DateTime` constructor.

I think the check should be moved from the controller to the view (or the view should always get a formatted time).

**Comment by tomasnorre** [comment]
@Patta could you please verify that the fix is working for you? Please see PR
https://github.com/AOEpeople/crawler/pull/734

**Comment by Patta** [comment]
@tomasnorre yes, the PR seems to fix this issue.

**Comment by tomasnorre** [comment]
Thanks for letting me know: I'll release a new version of the crawler one of the next days.
