### ISSUE TITLE
Info Module crawler protocol throws `htmlspecialchars() expects parameter 1 to be string, integer given`

### ISSUE THREAD

**Issue by t3easy** [AOEpeople/crawler#739]
## Bug Report

**Current Behavior**
If I open the Info module, select Site Crawler > crawler protocol and then select the root page (uid 1), I get `htmlspecialchars() expects parameter 1 to be string, integer given`.
This happens even with only this site, without subpages.
All other tested sites shows the protocol.
![image](https://user-images.githubusercontent.com/3628035/116849122-5ade0d00-abee-11eb-8550-7579e3385477.png)  
![image](https://user-images.githubusercontent.com/3628035/116849132-62051b00-abee-11eb-9f11-89e4b42f3a12.png)

**Expected behavior/output**
Get the crawler protocol.

**Steps to reproduce**
Info module, select Site Crawler > crawler protocol > select the root page (uid 1)

**Environment**
- Crawler version(s): 9.2.4
- TYPO3 version(s): 9.5.26
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional context**
Indexed_search is in use.

**Comment by tomasnorre** [comment]
Hi,

Thanks for reporting. 
This sounds similar/related to https://github.com/AOEpeople/crawler/issues/576 

I'll have a look at it.

**Comment by tomasnorre** [comment]
I don't know if it's the same, but the other day some reported to me that something similar happened when the indexed_search configuration was on the same page. 

Can you confirm that the case here too ?

**Comment by t3easy** [comment]
Yes, that's also the case in my setup. Seams to be a duplicate of #576. Sorry, haven't checkt the issue deeper because of the title with `running crawler...` which is not.

**Comment by tomasnorre** [comment]
No worries.

I'll see to find time to get it fixed.

**Comment by tomasnorre** [comment]
I have added documentation on this, in the troubleshooting section. As this section of the TYPO3 Core is already removed in TYPO3 11. I'll not provide a fix for this, but a workaround. 

Please see documentation. 
https://github.com/AOEpeople/crawler/blob/25a0e5f3c0b7c9e63fd6d617acff14f0db0de1da/Documentation/Troubleshooting/Index.rst#id19
