### ISSUE TITLE
No scheduler tasks available

### ISSUE THREAD

**Issue by derBoogie** [AOEpeople/crawler#756]
Hi,
I'm trying to add scheduler tasks for crawler, but there are no "crawer"-tasks available, as you can see in this screenshot: <img src="https://www.bugfree-systems.de/tmp/scheduler.png" />

Extension crawler is running and there are no errors in protocol.

**Environment**
- Crawler version: 9.2.5
- TYPO3 version: 10.4.17
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- The development environment is running over http and not over https. Could this be the cause for the missing scheduler tasks?

**Additional context**
`indexed_search` is installed in version 10.4.17

**Comment by tomasnorre** [comment]
As the Crawler have switched to Symfony Console Commands, they are not listed on that list any more. 
You can set them up using the `Execute Console Commands` and then select them in the dropdown (see screenshot)

![Screenshot from 2021-06-27 23:48:46](https://user-images.githubusercontent.com/1212481/123560430-56734200-d7a2-11eb-9421-003f939a750c.png)

I'll close this issue for now. Please let me know if it's not working for you, and then re-open the issue.
