### ISSUE TITLE
Crawler progress state after completly finished always "Process was cancelled"

### ISSUE THREAD

**Issue by eckonator** [AOEpeople/crawler#762]
## Bug Report

**Current Behavior**
Crawler progress state after completly finished always "Process was cancelled"

<img width="2452" alt="cancelled" src="https://user-images.githubusercontent.com/13748683/127633855-cfce8f58-ae03-4f6a-afb6-e816595f2ecf.png">

**Expected behavior/output**
After the crawler progress ist completed, the State should be "Progress completed sucessfully"

<img width="2458" alt="sucessfully" src="https://user-images.githubusercontent.com/13748683/127635204-0df1ea0c-97cf-4d9b-b0f6-2fe11d13ec46.png">

**Steps to reproduce**
Just run the crawler process.

**Environment**
- Crawler version(s): 9.2.6
- TYPO3 version(s): 10.4.18
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**
Following Changes solved the problem for me:

File: `/typo3conf/ext/crawler/Classes/Controller/CrawlerController.php`

I changes this code (line 384):

```
    /**
     * @param string $filenameWithPath
     * @deprecated
     */
    public function setProcessFilename($filenameWithPath): void
    {
        $this->processFilename = $filenameWithPath;
    }
```

to this:

```
    /**
     * @param string $filenameWithPath
     * @deprecated
     */
    public function setProcessFilename($filenameWithPath): void
    {
        $this->processFilename = $filenameWithPath;
    }

    /**
     * @param string $processID
     * @deprecated
     */
    public function setProcessID($processID): void
    {
        $this->processID = $processID;
    }
```

And as second step i changed this code:

```
       if (isset($this->processID)) {
            //if mulitprocessing is used we need to store the id of the process which has handled this entry
            $field_array['process_id_completed'] = $this->processID;
        }
```

to this:

```
       $this->setProcessID($queueRec['process_id']);

       if (isset($this->processID)) {
            //if mulitprocessing is used we need to store the id of the process which has handled this entry
            $field_array['process_id_completed'] = $this->processID;
        }
```

Maybe it helps someone else...

**Comment by tomasnorre** [comment]
Hi @eckonator 

Thanks for your report, would you mind to make PR with the suggested changes, then they are easier to review and test.

**Comment by tomasnorre** [comment]
I have never seen this before, and cannot reproduce this on the crawler dev box.

Could you please check if you can reproduce it with the dev box? 
https://github.com/AOEpeople/crawler/blob/main/CONTRIBUTING.md#devbox

**Comment by tomasnorre** [comment]
It's a regression build in some when after 9.2.0

**Comment by eckonator** [comment]
Pull request to main Branch created: https://github.com/AOEpeople/crawler/pull/764

**Comment by tomasnorre** [comment]
Thanks will have a look. Will dig into it right away, will see if I find exactly where the problem is introduced. Thanks to bi-sect, it should not take that long.

**Comment by tomasnorre** [comment]
This is the commit breaking it. 
https://github.com/AOEpeople/crawler/commit/d75d73b

**Comment by tomasnorre** [comment]
It's embarrassing. 
I even have tests for that, but ignored that they were red, as I thought it was due to instability of the CodeCeption tests.

**Comment by eckonator** [comment]
Making mistakes is human :-) Learning from them is the art.
