### ISSUE TITLE
"crawl" context menu doesn't work - fatal error on TYPO3 6.2.19

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/crawler#79]
Steps:
1. Go to a page where you have crawler configuration record
2. open a context (right click) menu on the crawler record
3. choose "crawler" from the menu

Result:
Fatal error: Class 'TYPO3\CMS\Core\Utility\GeneralUtility' not found in typo3/sysext/info/mod1/index.php on line 21

**Comment by tomasnorre** [comment]
Thanks @tmotyl ,

Will look into this.
