### ISSUE TITLE
Fatal error: Class 'tx_crawler_auth' not found (Typo3 6.2.14)

### ISSUE THREAD

**Issue by inceddy** [AOEpeople/crawler#86]
Some times the whole system crashes due to class 'tx_crawler_auth' can not be found by typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4434.

Deleting the typo3conf folder solves the randomly occuring problem.

**Comment by tomasnorre** [comment]
Hi @inceddy 

Which version of the Crawler extension are you using?

**Comment by inceddy** [comment]
5.0.4 - Which I was only able to install after setting the Composer dependency to "typo3/cms-core": "~6.2".

**Comment by tomasnorre** [comment]
Hi @inceddy Thanks for your feedback, we will take a look.

**Comment by Sampaguita** [comment]
I have a similar issue on TYPO3 v7.6.9: Directly after installing the crawler extension the whole system breaks _class 'tx_crawler_auth' can not be found by typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4533_. Only removing the extensioncompletely from typo3conf/ext/ and inside typo3conf/LocalConfiguration.php will get the system up again.

**Comment by tomasnorre** [comment]
Thanks we will look into this asap, we need to release a new version soonish.

**Comment by tomasnorre** [comment]
@inceddy @Sampaguita 

Can you provide some information on how to reproduce this.. 

I cannot trigger the error, in any case I have tried out till now.
