### ISSUE TITLE
Figure out how to keep compatibility for both 1.x and 2.x (RealURL)

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/crawler#88]

**Comment by samowitsch** [comment]
I would drop support for v1.x of realurl. People still use realurl v1 should use a compatible version of crawler.

**Comment by tomasnorre** [comment]
@samowitsch I see, that would be a breaking change, so we would need to consider how to deal with this. 

I'll talk to @srotsch about this, thanks for you input.

**Comment by tomasnorre** [comment]
Sorry, but we will not add support for RealURL 2.x, we will focus on getting a TYPO3 9 LTS release out instead.
