### ISSUE TITLE
split screen instead of second page by process states

### ISSUE THREAD

**Issue by rreichen** [AOEpeople/crawler#89]
When process states exceed the first page choosing the second one shows a split screen instead of the processes in second page.

My Versions are:
php: 5.5.14
TYPO3: 7.6.6
crawler: 5.0.4

**Comment by tomasnorre** [comment]
Hi @rreichen 

Can you add a screenshot of what you mean?

**Comment by rreichen** [comment]
There are two screenshots - one before and one after selection the second page. 

![crawler_01](https://cloud.githubusercontent.com/assets/18324572/15015947/0186a934-120f-11e6-82ca-f6f9b9a0866d.jpg)
![crawler_02](https://cloud.githubusercontent.com/assets/18324572/15015964/179f4adc-120f-11e6-8f03-d9a732ab46c1.jpg)

**Comment by tomasnorre** [comment]
Thanks, we will have a look.

**Comment by tomasnorre** [comment]
This most likely have to do with the way the link is generated in:
crawler/template/pagination.php
