### ISSUE TITLE
Cannot create crawler config if workspaces are not enabled

### ISSUE THREAD

**Issue by npostnik** [AOEpeople/crawler#90]
It is not possible to create a 'crawler configuration' if the extension workspaces is deactivated. It would be great, if this dependancy was configurable.

**Comment by tomasnorre** [comment]
Hi @npostnik 

It should be possible, but i will of course check this and get back to you. 

If it's not possible it for sure make sense to add the functionality for that.

**Comment by ses** [comment]
i have the same problem :(

> Oops, an error occurred!
>
> Field sys_workspace_uid of table tx_crawler_configuration reference to foreign table sys_workspace, > but this table is not defined in TCA

**Comment by tomasnorre** [comment]
Related if not duplicate of #93

**Comment by tomasnorre** [comment]
Related #82
