### ISSUE TITLE
set_id in indexed search not resetted

### ISSUE THREAD

**Issue by hartundweich** [AOEpeople/crawler#91]
When using crawler to index a fluid based extension there is a problem in indexing configuration setting field "set_id" back to 0 after crawling has finished.
set is holding the last ID and ist not resetted to 0 after crawling, therfore no additional crawling is happening after 24 hours.
Just noticed: field set_id is also not being resetted if crawling page tree.

Just noticed: field set_id is being resetted if crawler is run again. But if I manually reset the "next time indexing" field in indexing configuration the field "set_id" is not being resetted.

**Comment by tomasnorre** [comment]
Hi @hartundweich Thanks for reporting we will have a look.

**Comment by tomasnorre** [comment]
Sorry that this is talking so long, I'm trying to cleanup the issue tracker.

@hartundweich Can you please provide me with a way to reproduce the steps, please include the extension that is causing you problem. 

Then I'll look into this asap.

**Comment by hartundweich** [comment]
@tomasnorre 
It is not simple an issue with my extension, it also concers standard typo3 content. I think it is an issue not indexing all necessary documents when the indexer is first called - so I have to start the indexer again and again and again until all documents are indexed. 
Even if I configure indexer to index eg. 1000 documents in one run, it does not, it stops without error and the task has to be restarted - I can say that this is not an issue of PHP script execution time out.

**Comment by tomasnorre** [comment]
That's fair @hartundweich,

But can you please tell me step by step what to do to reproduce the problem.  I'm not sure i fully get it, from the description I have so far.

**Comment by tomasnorre** [comment]
@hartundweich

Can you please provide us with steps to reproduce please, other wise I will close issue.

**Comment by tomasnorre** [comment]
Ping @hartundweich

**Comment by tomasnorre** [comment]
As this issue has been inactive for quite a while, I will close it as no feedback was given.

Please reopen if still having problems.
